unpackaged/main/default/objects/Account/fields/RICSC_Email__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Email__c</fullName>
        <description>email field to capture the email of the Boutique</description>
        <label>Email</label>
        <type>Email</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Golden Record</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RICSC_IsGoldenRecord__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.RICSC_NotToBeGrouped__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Accounts (Local Records)</relationshipLabel>
        <relationshipName>RICSC_AccountGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_HighJewelleryClient__c.field-meta.xml
<CustomField>
        <fullName>RICSC_HighJewelleryClient__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Technical field to identify High Jewellery client records and exclude them from the sharing rules</description>
        <label>High Jewellery Client</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_IsGoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_IsGoldenRecord__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Golden Record</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_RecomputeFlagsPropagation__c.field-meta.xml
<CustomField>
        <fullName>RICSC_RecomputeFlagsPropagation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to indicate whether there is a pending job to recompute VIP, HJ, COO flags on the account's related objects</description>
        <label>Recompute Flags Propagation</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_VIP__c.field-meta.xml
<CustomField>
        <fullName>RICSC_VIP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Client categorization based on perceived value</description>
        <label>VIP</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Activity__c/RICSC_Activity__c.object-meta.xml
<CustomObject>
    <description>Activity object is used to collect the interaction between Sales assistant and the customers.</description>
    <label>Activity</label>
    <nameField>
        <label>Activity Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RICSC_Activity__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Direct lookup to an account  from  which the activity originated - Release 1 SC</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>RICSC_ActivitiesAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Activity__c/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to a Golden Record which has been created for the Account - Release 1 SC</description>
        <label>Golden Record</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>RICSC_ActivitiesGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Address__c/RICSC_Address__c.object-meta.xml
<CustomObject>
    <description>This object is used to collect  the Addresses of the related Local records.</description>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Address__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to Account (Contact)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>RICSC_AddressesAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Address__c/fields/RICSC_Address__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Address__c</fullName>
        <description>Field to capture the full address</description>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Address__c/fields/RICSC_HighJewelleryClient__c.field-meta.xml
<CustomField>
        <fullName>RICSC_HighJewelleryClient__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Technical field to identify High Jewellery client records and exclude them from the sharing rules</description>
        <label>High Jewellery Client</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Email__c/RICSC_Email__c.object-meta.xml
<CustomObject>
    <description>This object is used to collect  the Emails of the related Local records.</description>
    <label>Email</label>
    <nameField>
        <displayFormat>E-{000000000}</displayFormat>
        <label>Email</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to the Account (contact)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Emails</relationshipLabel>
        <relationshipName>RICSC_EmailsAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_Email__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Email__c</fullName>
        <description>Standard email type field</description>
        <label>Email</label>
        <length>80</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_VIP__c.field-meta.xml
<CustomField>
        <fullName>RICSC_VIP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It identifies if the Record is VIP or not . It is recalculated at the GR record level based on Maisons' rules</description>
        <label>VIP</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Phone__c/RICSC_Phone__c.object-meta.xml
<CustomObject>
    <description>This object is used to collect  the Phones of the related Local records.</description>
    <label>Phone</label>
    <nameField>
        <displayFormat>P-{000000000}</displayFormat>
        <label>Phone</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Phones</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Phone__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to Account (Contact)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Phones</relationshipLabel>
        <relationshipName>RICSC_PhonesAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Phone__c/fields/RICSC_Phone__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Phone__c</fullName>
        <description>Standard phone field</description>
        <label>Phone</label>
        <type>Phone</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Relation__c/RICSC_Relation__c.object-meta.xml
<CustomObject>
    <description>Relation object is used to track the relations between 2 Customers (e.g. father, husband etc)</description>
    <label>Relationship</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Relationship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RICSC_Relation__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to to link the related Person account (the one that has the role in the relation type)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationship</relationshipLabel>
        <relationshipName>RICSC_RelationsAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Relation__c/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to to link the related Golden Record (the one that has the role in the relation type)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationship</relationshipLabel>
        <relationshipName>RICSC_RelationsGR</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_SocialMediaID__c/RICSC_SocialMediaID__c.object-meta.xml
<CustomObject>
    <description>This object is used to collect  the Social ID of the related Local records.</description>
    <label>Social Media ID</label>
    <nameField>
        <displayFormat>S-{000000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Social Media IDs</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_SocialMediaID__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to Account (Contact)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Social Media IDs</relationshipLabel>
        <relationshipName>RICSC_SocialMediaIDsAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Wishlist__c/RICSC_Wishlist__c.object-meta.xml
<CustomObject>
    <label>Wishlist</label>
    <nameField>
        <displayFormat>Wishlist-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wishlists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RICSC_Wishlist__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to an Account - Release 1 SC</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Wishlists</relationshipLabel>
        <relationshipName>RICSC_WishlistsAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Wishlist__c/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to a Golden Record which has been created for the Account - Release 1 SC</description>
        <label>Golden Record</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Wishlists</relationshipLabel>
        <relationshipName>RICSC_WishlistsGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/classes/BatchFlagsPropagation_Test.cls
@isTest
private class BatchFlagsPropagation_Test {
    @testSetup
    static void setup() {
      List<RICSC_Address__c> addresses = new List<RICSC_Address__c>();
      List<RICSC_Activity__c> activities = new List<RICSC_Activity__c>();
      List<RICSC_Phone__c> phones = new List<RICSC_Phone__c>();
      List<RICSC_Relation__c> relations = new List<RICSC_Relation__c>();
      List<RICSC_Email__c> emails = new List<RICSC_Email__c>();
      List<RICSC_Wishlist__c> wishlists = new List<RICSC_Wishlist__c>();
      List<RICSC_SocialMediaID__c> socialmediaIDs = new List<RICSC_SocialMediaID__c>();


      Account accGR = UtilityTests.getPersonAccount();
      accGR.LastName = 'GRAccount';
      insert accGR;
      Account acc = UtilityTests.getPersonAccount();
      acc.LastName = 'LRAccount';
      acc.RICSC_GoldenRecord__c = accGR.id;
      acc.RICSC_IsGoldenRecord__c = false;
      insert acc;

      RICSC_Address__c adr1 = UtilityTests.getAddress();
      adr1.RICSC_Account__c = acc.Id;
      addresses.add(adr1);
      RICSC_Address__c adr2 = UtilityTests.getAddress();
      adr2.RICSC_Account__c = acc.Id;
      addresses.add(adr2);
      insert addresses;
      RICSC_Activity__c act1 = UtilityTests.getActivity();
      act1.RICSC_Account__c = acc.Id;
      act1.Name='Activity1';
      activities.add(act1);
      RICSC_Activity__c act2 = UtilityTests.getActivity();
      act2.RICSC_Account__c = acc.Id;
      act2.Name='Activity2';
      activities.add(act2);
      insert activities;
      RICSC_Email__c em1 = UtilityTests.getEmail();
      em1.RICSC_Account__c = acc.Id;
      emails.add(em1);
      RICSC_Email__c em2 = UtilityTests.getEmail();
      em2.RICSC_Account__c = acc.Id;
      emails.add(em2);
      insert emails;
      RICSC_Phone__c ph1 = UtilityTests.getPhone();
      ph1.RICSC_Account__c = acc.Id;
      phones.add(ph1);
      RICSC_Phone__c ph2 = UtilityTests.getPhone();
      ph2.RICSC_Account__c = acc.Id;
      phones.add(ph2);
      insert phones;
      RICSC_SocialMediaID__c soc1 = UtilityTests.getSocialMediaID();
      soc1.RICSC_Account__c = acc.Id;
      socialmediaIDs.add(soc1);
      RICSC_SocialMediaID__c soc2 = UtilityTests.getSocialMediaID();
      soc2.RICSC_Account__c = acc.Id;
      socialmediaIDs.add(soc2);
      insert socialmediaIDs;
      RICSC_Relation__c rel1 = UtilityTests.getRelation();
      rel1.RICSC_Account__c = acc.Id;
      relations.add(rel1);
      RICSC_Relation__c rel2 = UtilityTests.getRelation();
      rel2.RICSC_Account__c = acc.Id;
      relations.add(rel2);
      insert relations;
      RICSC_Wishlist__c wis1 = UtilityTests.getWishlist();
      wis1.RICSC_Account__c = acc.Id;
      wishlists.add(wis1);
      RICSC_Wishlist__c wis2 = UtilityTests.getWishlist();
      wis2.RICSC_Account__c = acc.Id;
      wishlists.add(wis2);
      insert wishlists;
    }

    static testmethod void testSync() {
      Test.startTest();
      TRG_TriggerDispatcher.skipTriggerMap.put('Account',true);
      Account ac2 = [SELECT Id FROM Account WHERE LastName = 'LRAccount'];
      ac2.put('RICSC_VIP__c',true);
      ac2.put('RICSC_HighJewelleryClient__c',true);
      update ac2;
      BatchFlagsPropagation uca = new BatchFlagsPropagation(true,null);
      Id batchId = Database.executeBatch(uca);
      Test.stopTest();
      System.assert([SELECT RICSC_VIP__c FROM Account WHERE LastName = 'GRAccount'][0].RICSC_VIP__c, 'Account is not VIP');
      System.assert([SELECT RICSC_VIP__c FROM RICSC_Email__c][0].RICSC_VIP__c, 'Email is not VIP');
      System.assert([SELECT RICSC_HighJewelleryClient__c FROM RICSC_Email__c][1].RICSC_HighJewelleryClient__c, 'Email is not high jewelery');
      System.assert([SELECT RICSC_VIP__c FROM RICSC_Activity__c][0].RICSC_VIP__c, 'Activity is not VIP');
      System.assert([SELECT RICSC_VIP__c FROM RICSC_SocialMediaID__c][0].RICSC_VIP__c, 'Social Media ID is not VIP');
      System.assert([SELECT RICSC_VIP__c FROM RICSC_Address__c][0].RICSC_VIP__c, 'Address is not VIP');
      System.assert([SELECT RICSC_HighJewelleryClient__c FROM RICSC_Wishlist__c][0].RICSC_HighJewelleryClient__c, 'Wishlist is not high jewelery');
      System.assert([SELECT RICSC_VIP__c FROM RICSC_Relation__c][0].RICSC_VIP__c, 'Relation is not VIP');
      System.assert([SELECT RICSC_VIP__c FROM RICSC_Phone__c][0].RICSC_VIP__c, 'Phone is not VIP');
    }
    static testmethod void testAsync() {
      Test.startTest();
      TRG_TriggerDispatcher.skipTriggerMap.put('Account',true);
      Account ac2 = [SELECT Id FROM Account WHERE LastName = 'LRAccount'];
      ac2.put('RICSC_VIP__c',true);
      ac2.put('RICSC_HighJewelleryClient__c',true);
      ac2.put('RICSC_RecomputeFlagsPropagation__c', true);
      update ac2;
      Integer batchSize = 50;
      BatchFlagsPropagation batch = new BatchFlagsPropagation(false, 'SELECT Id, RICSC_RecomputeFlagsPropagation__c FROM Account WHERE isPersonAccount = true AND RICSC_RecomputeFlagsPropagation__c = true');
      ID batchprocessid = Database.executeBatch(batch,batchSize);
      Test.stopTest();
      System.assert([SELECT RICSC_VIP__c FROM Account WHERE LastName = 'GRAccount'][0].RICSC_VIP__c, 'Account is not VIP');
      System.assert([SELECT RICSC_VIP__c FROM RICSC_Email__c][0].RICSC_VIP__c, 'Email is not VIP');
      System.assert([SELECT RICSC_HighJewelleryClient__c FROM RICSC_Email__c][1].RICSC_HighJewelleryClient__c, 'Email is not high jewelery');
      System.assert([SELECT RICSC_VIP__c FROM RICSC_Activity__c][0].RICSC_VIP__c, 'Activity is not VIP');
      System.assert([SELECT RICSC_VIP__c FROM RICSC_SocialMediaID__c][0].RICSC_VIP__c, 'Social Media ID is not VIP');
      System.assert([SELECT RICSC_VIP__c FROM RICSC_Address__c][0].RICSC_VIP__c, 'Address is not VIP');
      System.assert([SELECT RICSC_HighJewelleryClient__c FROM RICSC_Wishlist__c][0].RICSC_HighJewelleryClient__c, 'Wishlist is not high jewelery');
      System.assert([SELECT RICSC_VIP__c FROM RICSC_Relation__c][0].RICSC_VIP__c, 'Relation is not VIP');
      System.assert([SELECT RICSC_VIP__c FROM RICSC_Phone__c][0].RICSC_VIP__c, 'Phone is not VIP');
    }

}