unpackaged/main/default/objects/Account/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Golden Record</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RICSC_IsGoldenRecord__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.RICSC_NotToBeGrouped__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Accounts (Local Records)</relationshipLabel>
        <relationshipName>RICSC_AccountGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_HasLocalRecords__c.field-meta.xml
<CustomField>
        <fullName>RICSC_HasLocalRecords__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Local Records</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_IsGoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_IsGoldenRecord__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Golden Record</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Case/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to a Golden Record which has been created for the Account</description>
        <label>Golden Record</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>RICSC_TicketsGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Wishlist__c/RICSC_Wishlist__c.object-meta.xml
<CustomObject>
    <label>Wishlist</label>
    <nameField>
        <displayFormat>Wishlist-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wishlists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RICSC_Wishlist__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to an Account - Release 1 SC</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Wishlists</relationshipLabel>
        <relationshipName>RICSC_WishlistsAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Wishlist__c/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to a Golden Record which has been created for the Account - Release 1 SC</description>
        <label>Golden Record</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Wishlists</relationshipLabel>
        <relationshipName>RICSC_WishlistsGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/classes/WishlistTriggerHandler_Test.cls
@isTest
public with sharing class WishlistTriggerHandler_Test {

@testSetup

static void setup() {
  Account accWithoutGoldenRecord = UtilityTests.getPersonAccount();
  accWithoutGoldenRecord.LastName = 'accWithoutGoldenRecord';
  insert accWithoutGoldenRecord;

  Account goldenRecordAcc =  UtilityTests.getPersonAccount();
  GoldenRecordAcc.LastName = 'GoldenRecordAcc';
  GoldenRecordAcc.RICSC_HasLocalRecords__c = true;
  GoldenRecordAcc.RICSC_IsGoldenRecord__c = true;
  insert GoldenRecordAcc;

  Account accWithGoldenRecordLookUp =  UtilityTests.getPersonAccount();
  accWithGoldenRecordLookUp.LastName = 'accWithGoldenRecordLookUp';
  accWithGoldenRecordLookUp.RICSC_GoldenRecord__c = GoldenRecordAcc.Id;
  accWithGoldenRecordLookUp.RICSC_IsGoldenRecord__c = false;
  insert accWithGoldenRecordLookUp;

  Case testCase = new Case();
  insert testCase;

}

  static testmethod void populateGoldenRecordWithLocalRecordId() {
    Test.startTest();
    Account accWithoutGoldenRecord = [SELECT Id FROM Account WHERE Name = 'accWithoutGoldenRecord'];
    RICSC_Wishlist__c wslt = UtilityTests.getWishlist();
    wslt.RICSC_Account__c = accWithoutGoldenRecord.Id;
    insert wslt;
    Test.stopTest();

    RICSC_Wishlist__c wishListAfterPopulate = [SELECT RICSC_GoldenRecord__c,RICSC_Account__c FROM RICSC_Wishlist__c];
    System.assertEquals(wishListAfterPopulate.RICSC_GoldenRecord__c,wishListAfterPopulate.RICSC_Account__c);
  }


  static testmethod void populateGoldenRecordWithAccountsGoldenRecordId() {
    Test.startTest();
    Account accWithGoldenRecord = [SELECT Id FROM Account WHERE Name = 'accWithGoldenRecordLookUp'];
    RICSC_Wishlist__c wslt = UtilityTests.getWishlist();
    wslt.RICSC_Account__c = accWithGoldenRecord.Id;
    insert wslt;
    Test.stopTest();

    RICSC_Wishlist__c wishListAfterPopulate = [SELECT RICSC_GoldenRecord__c,RICSC_Account__c,RICSC_Account__r.RICSC_GoldenRecord__c FROM RICSC_Wishlist__c];
    System.assertEquals(wishListAfterPopulate.RICSC_GoldenRecord__c,wishListAfterPopulate.RICSC_Account__r.RICSC_GoldenRecord__c);
  }

}