unpackaged/main/default/objects/Account/fields/RICSC_AverageBasket__c.field-meta.xml
<CustomField>
        <fullName>RICSC_AverageBasket__c</fullName>
        <description>Calculated field indicating the value of the average shopping session of the client</description>
        <label>Average Basket</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Golden Record</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RICSC_IsGoldenRecord__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.RICSC_NotToBeGrouped__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Accounts (Local Records)</relationshipLabel>
        <relationshipName>RICSC_AccountGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_HasLocalRecords__c.field-meta.xml
<CustomField>
        <fullName>RICSC_HasLocalRecords__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Local Records</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_IsGoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_IsGoldenRecord__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Golden Record</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_Maison__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Maison__c</fullName>
        <description>List of Maisons</description>
        <label>Account Maison</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Maison</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_Turnover__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Turnover__c</fullName>
        <description>Calculated field with sum of all customer purchases</description>
        <label>Turnover</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/RICSC_Transaction__c.object-meta.xml
<CustomObject>
    <description>capture transaction information.</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{000000000}</displayFormat>
        <label>Transaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to an Account - Release 1 SC</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>RICSC_TransactionsAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_AmountWithTax__c.field-meta.xml
<CustomField>
        <fullName>RICSC_AmountWithTax__c</fullName>
        <description>Total amount of the transaction coming from the source system</description>
        <label>Amount With Tax</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_CurrencyKey__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CurrencyKey__c</fullName>
        <description>Currency keycoming from the source system</description>
        <label>Currency Key</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Currency</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to a Golden Record which has been created for the Account - Release 1 SC</description>
        <label>Golden Record</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>RICSC_TransactionsGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_Maison__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Maison__c</fullName>
        <description>List of Maisons</description>
        <label>Maison</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Maison</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/globalValueSets/RICSC_Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AWG</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BOV</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BTN</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYR</fullName>
    </customValue>
    <customValue>
        <fullName>BZD</fullName>
    </customValue>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <customValue>
        <fullName>CDF</fullName>
    </customValue>
    <customValue>
        <fullName>CHE</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <description>Unit of measurecoming</description>
    <masterLabel>Currency</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/RICSC_Maison.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cartier</fullName>
    </customValue>
    <customValue>
        <fullName>Jaeger Le Coultre</fullName>
    </customValue>
    <customValue>
        <fullName>Van Cleef &amp; Arpels</fullName>
    </customValue>
    <masterLabel>Maison</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/BatchConventionRateCalculation_Test.cls
@isTest
private class BatchConventionRateCalculation_Test {

  @testSetup
  static void setup() {

    Account newCartierPersonAccountGR = new Account();
    newCartierPersonAccountGR.FirstName = 'FirstNameGoldenRecord';
    newCartierPersonAccountGR.LastName = 'LastNameGoldenRecord';
    newCartierPersonAccountGR.RICSC_Maison__c = 'Cartier';
    newCartierPersonAccountGR.RecordTypeId = RecordTypeHelper.getRTId('Account', 'RICSC_Cartier');
    newCartierPersonAccountGR.RICSC_IsGoldenRecord__c = true;
    newCartierPersonAccountGR.RICSC_HasLocalRecords__c = true;
    insert newCartierPersonAccountGR;

    Account newCartierPersonAccount = new Account();
    newCartierPersonAccount.FirstName = 'FirstNameLocalRecord';
    newCartierPersonAccount.LastName = 'LastNameLocalRecord';
    newCartierPersonAccount.RICSC_Maison__c = 'Cartier';
    newCartierPersonAccount.RecordTypeId = RecordTypeHelper.getRTId('Account', 'RICSC_Cartier');
    newCartierPersonAccount.RICSC_GoldenRecord__c = newCartierPersonAccountGR.Id;
    newCartierPersonAccount.RICSC_IsGoldenRecord__c = false;
    newCartierPersonAccount.RICSC_HasLocalRecords__c = false;
    insert newCartierPersonAccount;

    RICSC_Transaction__c testTransaction = new RICSC_Transaction__c(RICSC_Account__c = newCartierPersonAccount.Id,RICSC_AmountWithTax__c = 220000,RICSC_CurrencyKey__c = 'EUR', RICSC_Maison__c = 'Cartier');
    insert testTransaction;

    RICSC_Transaction__c testTransaction2 = new RICSC_Transaction__c(RICSC_Account__c = newCartierPersonAccount.Id,RICSC_AmountWithTax__c = 220000,RICSC_CurrencyKey__c = 'EUR', RICSC_Maison__c = 'Cartier');
    insert testTransaction2;
}

  static testmethod void conventionRateCalculationGoldenRecord() {
    Test.startTest();
    BatchConventionRateCalculation b = new BatchConventionRateCalculation(false, null);
    Id batchId = Database.executeBatch(b);
    Account accAfter = [SELECT Id,RICSC_Turnover__c,RICSC_AverageBasket__c FROM Account WHERE LastName = 'LastNameGoldenRecord'];
    Test.stopTest();
    System.assertEquals(220000, accAfter.RICSC_AverageBasket__c, 'Average basket assertion failed');
    System.assertEquals(440000, accAfter.RICSC_Turnover__c, 'Turnover assertion failed');
  }


  static testmethod void conventionRateCalculationLocalRecord() {
    Test.startTest();
    BatchConventionRateCalculation b = new BatchConventionRateCalculation(false, null);
    Id batchId = Database.executeBatch(b);
    Account accAfter = [SELECT Id,RICSC_Turnover__c,RICSC_AverageBasket__c FROM Account WHERE LastName = 'LastNameLocalRecord'];
    Test.stopTest();
    System.assertEquals(220000, accAfter.RICSC_AverageBasket__c, 'Average basket assertion failed');
    System.assert(accAfter.RICSC_Turnover__c!=null, 'Turnover should be caclulated on the local account');
  }
}