unpackaged/main/default/objects/Account/fields/RICSC_GR__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GR__c</fullName>
        <description>Formula field showing golden record icon if a the record is a golden one</description>
        <formula>if( RICSC_IsGoldenRecord__c , IMAGE('/resource/GRIcon?','Image not found', 25,25),'' )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GR</label>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_HasLocalRecords__c.field-meta.xml
<CustomField>
        <fullName>RICSC_HasLocalRecords__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Local Records</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/classes/BatchResidenceNonResidence.cls
public class BatchResidenceNonResidence implements Database.Batchable<SObject>, Schedulable {

    public static final Integer MAX_SCOPE = 100;
    private String query = 'SELECT Id, RICSC_HasLocalRecords__c FROM Account';
    public Boolean skipTriggersOnAccount = false;

    public Iterable<SObject> start(Database.BatchableContext bc) {
        return Database.getQueryLocator(this.query);
    }

    public BatchResidenceNonResidence(Boolean skipParam, String queryStr) {
      this.query = queryStr == null ? this.query : queryStr;
      skipTriggersOnAccount = skipParam;
    }

    public void execute(SchedulableContext sc) {
      BatchResidenceNonResidence b = new BatchResidenceNonResidence(false, null);
      Database.executeBatch(b, MAX_SCOPE);
    }

    public void execute(Database.BatchableContext bc, List<Account> scope) {
      Set<Id> accountsWithoutLocals = new Set<Id>();
      Set<Id> accountsWithLocals = new Set<Id>();
      for(Account acc : scope){
        if(acc.RICSC_HasLocalRecords__c) {
          accountsWithLocals.add(acc.Id);
        }
        else {
          accountsWithoutLocals.add(acc.Id);
        }
      }

      if(skipTriggersOnAccount){
        TRG_TriggerDispatcher.skipTriggerMap.put('Account',true);
      }

      Database.SaveResult[] srList = Database.update(CalculatingFieldsHandler.computeResidenceNonResidence(accountsWithoutLocals, 'RICSC_Account__c', true),false);
      UtilityLogger.logAllErrors(srList, false, 'BatchResidenceNonResidence','execute');

      srList = Database.update(CalculatingFieldsHandler.computeResidenceNonResidence(accountsWithLocals, 'RICSC_GR__c', true),false);
      UtilityLogger.logAllErrors(srList, false, 'BatchResidenceNonResidence','execute');

      if(skipTriggersOnAccount){
        TRG_TriggerDispatcher.skipTriggerMap.put('Account',false);
      }
    }

    public void finish(Database.BatchableContext bc) {

    }
}