unpackaged/main/default/objects/Account/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Golden Record</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RICSC_IsGoldenRecord__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.RICSC_NotToBeGrouped__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Accounts (Local Records)</relationshipLabel>
        <relationshipName>RICSC_AccountGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_HasLocalRecords__c.field-meta.xml
<CustomField>
        <fullName>RICSC_HasLocalRecords__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Local Records</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_IsGoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_IsGoldenRecord__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Golden Record</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_TotalNumberOfRepairs__c.field-meta.xml
<CustomField>
        <fullName>RICSC_TotalNumberOfRepairs__c</fullName>
        <description>Calculated number field of all the repairs (of all products)</description>
        <label>Total Number Of Repairs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_VIP__c.field-meta.xml
<CustomField>
        <fullName>RICSC_VIP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Client categorization based on perceived value</description>
        <label>VIP</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/classes/BatchSObjectCurrencySetToEUR_Test.cls
@isTest
private class BatchSObjectCurrencySetToEUR_Test {

  @testSetup
  static void setup() {

    Account newVanCleefAndArpelsGoldenRecord = UtilityTests.getPersonAccount();
    newVanCleefAndArpelsGoldenRecord.LastName = 'VanCleefAndArpelsGoldenRecordAccount';
    newVanCleefAndArpelsGoldenRecord.RICSC_VIP__c = true;
    newVanCleefAndArpelsGoldenRecord.RICSC_HasLocalRecords__c = true;
    newVanCleefAndArpelsGoldenRecord.RICSC_IsGoldenRecord__c = true;
    newVanCleefAndArpelsGoldenRecord.RICSC_TotalNumberOfRepairs__c = 2;
    newVanCleefAndArpelsGoldenRecord.RICSC_TotalNumberOfRepairs__c = 0;
    newVanCleefAndArpelsGoldenRecord.CurrencyIsoCode = 'CHF';
    insert newVanCleefAndArpelsGoldenRecord;

    Account newVanCleefAndArpelsAccount = UtilityTests.getPersonAccount();
    newVanCleefAndArpelsAccount.LastName = 'VanCleefAndArpelsLocalReordAccount';
    newVanCleefAndArpelsAccount.RICSC_VIP__c = true;
    newVanCleefAndArpelsAccount.CurrencyIsoCode = 'CHF';
    newVanCleefAndArpelsAccount.RICSC_IsGoldenRecord__c = false;
    newVanCleefAndArpelsAccount.RICSC_GoldenRecord__c = newVanCleefAndArpelsGoldenRecord.id;
    insert newVanCleefAndArpelsAccount;
  }

  static testmethod void currencyChangeFromCHFToEUR() {

    Account accGR = [SELECT CurrencyIsoCode FROM Account WHERE Name = 'VanCleefAndArpelsGoldenRecordAccount'];
    Account accLR = [SELECT CurrencyIsoCode FROM Account WHERE Name = 'VanCleefAndArpelsLocalReordAccount'];

    System.assertEquals(accGR.CurrencyIsoCode,'CHF');
    System.assertEquals(accLR.CurrencyIsoCode,'CHF');

    Test.startTest();
    BatchSObjectCurrencySetToEUR bas = new BatchSObjectCurrencySetToEUR(true,'SELECT CurrencyIsoCode FROM Account');
    Id batchId = Database.executeBatch(bas);
    Test.stopTest();

    Account accGRAfter = [SELECT CurrencyIsoCode FROM Account WHERE Name = 'VanCleefAndArpelsGoldenRecordAccount'];
    Account accLRAfter = [SELECT CurrencyIsoCode FROM Account WHERE Name = 'VanCleefAndArpelsLocalReordAccount'];

    System.assertEquals(accGRAfter.CurrencyIsoCode,'EUR');
    System.assertEquals(accLRAfter.CurrencyIsoCode,'EUR');

  }

}