unpackaged/main/default/objects/Account/fields/RICSC_CountryOfOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryOfOrigin__c</fullName>
        <description>Country where the record has been created. Used for the sharing rules (e.g. records created outside of China shouldn't be visible for the Chineese users) - Release 1 SC</description>
        <label>Account Country Of Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_Localisation__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Localisation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to the localisation object</description>
        <label>Localisation</label>
        <referenceTo>RICSC_Localisation__c</referenceTo>
        <relationshipLabel>Boutiques</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_Maison__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Maison__c</fullName>
        <description>List of Maisons</description>
        <label>Account Maison</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Maison</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_ReferenceBoutique__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ReferenceBoutique__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is populated with the SF ID correspondent to the respective SAP boutique coming from SAP as a consequence of a calculation</description>
        <label>Reference Boutique</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Reference Boutique)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_ReferenceMarket__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ReferenceMarket__c</fullName>
        <description>Text field to indicate the reference market of the client, calculated based on SF rules</description>
        <label>Reference Market</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_ReferenceRegion__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ReferenceRegion__c</fullName>
        <description>Text field to indicate the reference market of the client, calculated based on SF rules</description>
        <label>Reference Region</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Localisation__c/RICSC_Localisation__c.object-meta.xml
<CustomObject>
    <description>Object to represent localisation structure of each Maison on the country, market and region level</description>
    <label>Localisation</label>
    <nameField>
        <label>Localisation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Localisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RICSC_Localisation__c/fields/RICSC_LocalisationLevel__c.field-meta.xml
<CustomField>
        <fullName>RICSC_LocalisationLevel__c</fullName>
        <label>Localisation Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Country</fullName>
                </value>
                <value>
                    <fullName>Region</fullName>
                </value>
                <value>
                    <fullName>Market</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Localisation__c/fields/RICSC_Maison__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Maison__c</fullName>
        <description>Maison of the Localisation record</description>
        <label>Maison</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Maison</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Localisation__c/fields/RICSC_ParentLocalisation__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ParentLocalisation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relation to the higher level of Localisation</description>
        <label>Parent Localisation</label>
        <referenceTo>RICSC_Localisation__c</referenceTo>
        <relationshipLabel>Localisations</relationshipLabel>
        <relationshipName>RICSC_ParentLocalisation</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/globalValueSets/RICSC_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Amer.Virgin Is.</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua/Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia-Herz.</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Islands</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/RICSC_Maison.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cartier</fullName>
    </customValue>
    <customValue>
        <fullName>Jaeger Le Coultre</fullName>
    </customValue>
    <customValue>
        <fullName>Van Cleef &amp; Arpels</fullName>
    </customValue>
    <masterLabel>Maison</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/BatchVCAReferenceMarketRegion_Test.cls
@isTest
public with sharing class BatchVCAReferenceMarketRegion_Test {

@testSetup
  static void setup() {
    RICSC_Localisation__c franceLocalisationRegion = new RICSC_Localisation__c();
    FranceLocalisationRegion.RICSC_LocalisationLevel__c = 'Region';
    FranceLocalisationRegion.Name = 'Europe';
    FranceLocalisationRegion.RICSC_Maison__c = 'Cartier';
    insert FranceLocalisationRegion;

    RICSC_Localisation__c franceLocalisationMarket = new RICSC_Localisation__c();
    FranceLocalisationMarket.RICSC_LocalisationLevel__c = 'Market';
    FranceLocalisationMarket.Name = 'France';
    FranceLocalisationMarket.RICSC_ParentLocalisation__c = FranceLocalisationRegion.Id;
    FranceLocalisationMarket.RICSC_Maison__c = 'Cartier';
    insert FranceLocalisationMarket;

    RICSC_Localisation__c franceLocalisation = new RICSC_Localisation__c();
    FranceLocalisation.RICSC_LocalisationLevel__c = 'Country';
    FranceLocalisation.Name = 'France';
    FranceLocalisation.RICSC_ParentLocalisation__c = FranceLocalisationMarket.Id;
    FranceLocalisation.RICSC_Maison__c = 'Cartier';
    insert franceLocalisation;

    Account transactionBoutique = UtilityTests.getBoutique();
    transactionBoutique.Name = 'Boutique';
    transactionBoutique.RICSC_CountryOfOrigin__c = 'France';
    transactionBoutique.RICSC_Maison__c = 'Cartier';
    insert transactionBoutique;

    Account newVanCleefAndArpelsGoldenRecord = UtilityTests.getPersonAccount();
    newVanCleefAndArpelsGoldenRecord.LastName = 'VanCleefAndArpelsGoldenLocalAccount';
    newVanCleefAndArpelsGoldenRecord.RICSC_ReferenceBoutique__c = transactionBoutique.Id;
    insert newVanCleefAndArpelsGoldenRecord;
  }

  static testmethod void referenceMarketRegionChange() {

    Test.startTest();
    BatchVCAReferenceMarketRegion bc = new BatchVCAReferenceMarketRegion(true,null);
    Database.executeBatch(bc, 1000);
    Test.stopTest();

    Account acc = [SELECT RICSC_ReferenceMarket__c,RICSC_ReferenceRegion__c FROM Account WHERE LastName = 'VanCleefAndArpelsGoldenLocalAccount'];
    System.assertEquals('France', acc.RICSC_ReferenceMarket__c);
    System.assertEquals('Europe', acc.RICSC_ReferenceRegion__c);
  }
}