unpackaged/main/default/objects/Account/fields/RICSC_CountryOfOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryOfOrigin__c</fullName>
        <description>Country where the record has been created. Used for the sharing rules (e.g. records created outside of China shouldn't be visible for the Chineese users) - Release 1 SC</description>
        <label>Account Country Of Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_Email__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Email__c</fullName>
        <description>email field to capture the email of the Boutique</description>
        <label>Email</label>
        <type>Email</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_SourceCRM__c.field-meta.xml
<CustomField>
        <fullName>RICSC_SourceCRM__c</fullName>
        <description>Technical Field -  to indicate which CRM is the owner of the customer</description>
        <label>Source CRM</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Legacy_0050010</fullName>
                </value>
                <value>
                    <fullName>Legacy_0050050</fullName>
                </value>
                <value>
                    <fullName>Legacy_0050090</fullName>
                </value>
                <value>
                    <fullName>Legacy_0143090</fullName>
                </value>
                <value>
                    <fullName>Legacy_0153080</fullName>
                </value>
                <value>
                    <fullName>Legacy_0155000</fullName>
                </value>
                <value>
                    <fullName>Legacy_0163070</fullName>
                </value>
                <value>
                    <fullName>Legacy_0163170</fullName>
                </value>
                <value>
                    <fullName>Legacy_0163270</fullName>
                </value>
                <value>
                    <fullName>Legacy_0163370</fullName>
                </value>
                <value>
                    <fullName>Legacy_0174000</fullName>
                </value>
                <value>
                    <fullName>Legacy_0174010</fullName>
                </value>
                <value>
                    <fullName>Legacy_0174020</fullName>
                </value>
                <value>
                    <fullName>Legacy_0174030</fullName>
                </value>
                <value>
                    <fullName>Legacy_0186000</fullName>
                </value>
                <value>
                    <fullName>SAP_CRM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Activity__c/RICSC_Activity__c.object-meta.xml
<CustomObject>
    <description>Activity object is used to collect the interaction between Sales assistant and the customers.</description>
    <label>Activity</label>
    <nameField>
        <label>Activity Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RICSC_Activity__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Direct lookup to an account  from  which the activity originated - Release 1 SC</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>RICSC_ActivitiesAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Activity__c/fields/RICSC_CountryofOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryofOrigin__c</fullName>
        <description>Country where the record has been created. Used for the sharing rules (e.g. records created outside of China shouldn't be visible for the Chineese users) - Release 1 SC</description>
        <label>Country of Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Address__c/RICSC_Address__c.object-meta.xml
<CustomObject>
    <description>This object is used to collect  the Addresses of the related Local records.</description>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Address__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to Account (Contact)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>RICSC_AddressesAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Address__c/fields/RICSC_Address__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Address__c</fullName>
        <description>Field to capture the full address</description>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Email__c/RICSC_Email__c.object-meta.xml
<CustomObject>
    <description>This object is used to collect  the Emails of the related Local records.</description>
    <label>Email</label>
    <nameField>
        <displayFormat>E-{000000000}</displayFormat>
        <label>Email</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to the Account (contact)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Emails</relationshipLabel>
        <relationshipName>RICSC_EmailsAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_CountryofOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryofOrigin__c</fullName>
        <description>Picklist to capture the client's country of origin</description>
        <label>Country of Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_Email__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Email__c</fullName>
        <description>Standard email type field</description>
        <label>Email</label>
        <length>80</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Phone__c/RICSC_Phone__c.object-meta.xml
<CustomObject>
    <description>This object is used to collect  the Phones of the related Local records.</description>
    <label>Phone</label>
    <nameField>
        <displayFormat>P-{000000000}</displayFormat>
        <label>Phone</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Phones</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Phone__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to Account (Contact)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Phones</relationshipLabel>
        <relationshipName>RICSC_PhonesAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Phone__c/fields/RICSC_CountryofOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryofOrigin__c</fullName>
        <description>Country of origin of client</description>
        <label>Country of Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Phone__c/fields/RICSC_Phone__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Phone__c</fullName>
        <description>Standard phone field</description>
        <label>Phone</label>
        <type>Phone</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Relation__c/RICSC_Relation__c.object-meta.xml
<CustomObject>
    <description>Relation object is used to track the relations between 2 Customers (e.g. father, husband etc)</description>
    <label>Relationship</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Relationship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RICSC_Relation__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to to link the related Person account (the one that has the role in the relation type)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationship</relationshipLabel>
        <relationshipName>RICSC_RelationsAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Relation__c/fields/RICSC_CountryofOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryofOrigin__c</fullName>
        <description>Country where the record has been created. Used for the sharing rules (e.g. records created outside of China shouldn't be visible for the Chineese users) - Release 1 SC</description>
        <label>Country of Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/TRG_TriggerSettings__c/TRG_TriggerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom setting used to enable or disable all triggers/specific triggers for a given user/profile</description>
    <label>Trigger Settings</label>
</CustomObject>

unpackaged/main/default/objects/TRG_TriggerSettings__c/fields/CheckEnabledOnLeanLoad__c.field-meta.xml
<CustomField>
        <fullName>CheckEnabledOnLeanLoad__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CheckEnabledOnLeanLoad</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/TRG_TriggerSettings__c/fields/DisableAllProcessBuilders__c.field-meta.xml
<CustomField>
        <fullName>DisableAllProcessBuilders__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If true, all process builders managed by the Trigger Framework are skipped for all objects</description>
        <inlineHelpText>if true, all process builders managed by the Trigger Framework are skipped for all objects</inlineHelpText>
        <label>DisableAllProcessBuilders</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/TRG_TriggerSettings__c/fields/DisableAllTriggers__c.field-meta.xml
<CustomField>
        <fullName>DisableAllTriggers__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If true, all triggers managed by the Trigger Framework are skipped for all objects</description>
        <inlineHelpText>If true, all triggers managed by the Trigger Framework are skipped for all objects</inlineHelpText>
        <label>DisableAllTriggers</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/TRG_TriggerSettings__c/fields/DisableAllWorkflows__c.field-meta.xml
<CustomField>
        <fullName>DisableAllWorkflows__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If true, all workflows managed by the Trigger Framework are skipped for all objects</description>
        <inlineHelpText>If true, all workflows managed by the Trigger Framework are skipped for all objects</inlineHelpText>
        <label>DisableAllWorkflows</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/TRG_TriggerSettings__c/fields/DisableTriggerMethods__c.field-meta.xml
<CustomField>
        <fullName>DisableTriggerMethods__c</fullName>
        <description>List of newline separated fully specified class names of classes extending TriggerHandlerInterface to skip during execution</description>
        <inlineHelpText>List of newline separated fully specified class names of classes extending TriggerHandlerInterface to skip during execution</inlineHelpText>
        <label>DisableTriggerMethods</label>
        <type>TextArea</type>
    </CustomField>

unpackaged/main/default/objects/TRG_TriggerSettings__c/fields/DisableTriggerObjects__c.field-meta.xml
<CustomField>
        <fullName>DisableTriggerObjects__c</fullName>
        <description>List of newline separated fully specified object names to skip during trigger execution</description>
        <inlineHelpText>List of newline separated fully specified object names to skip during trigger execution</inlineHelpText>
        <label>DisableTriggerObjects</label>
        <type>TextArea</type>
    </CustomField>

unpackaged/main/default/objects/TRG_TriggerSettings__c/fields/PrintLimitsInDebug__c.field-meta.xml
<CustomField>
        <fullName>PrintLimitsInDebug__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If true, print limits in debug</description>
        <inlineHelpText>If true, print limits in debug</inlineHelpText>
        <label>PrintLimitsInDebug</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/globalValueSets/RICSC_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Amer.Virgin Is.</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua/Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia-Herz.</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Greece</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/BatchPopulateGoldenRecordLookup_Test.cls
@isTest
private class BatchPopulateGoldenRecordLookup_Test {
  @testSetup
  static void setup() {

    TRG_TriggerSettings__c triggerSetting = TRG_TriggerSettings__c.getOrgDefaults();

    triggerSetting.DisableAllProcessBuilders__c = false;
    triggerSetting.DisableAllTriggers__c = true;
    triggerSetting.DisableAllWorkflows__c = false;
    triggerSetting.CheckEnabledOnLeanLoad__c = false;
    triggerSetting.PrintLimitsInDebug__c = true;
    triggerSetting.DisableTriggerMethods__c = '';
    triggerSetting.DisableTriggerObjects__c = '';

    upsert triggerSetting  TRG_TriggerSettings__c.Id;

    List<RICSC_Address__c> addresses = new List<RICSC_Address__c>();
    List<RICSC_Activity__c> activities = new List<RICSC_Activity__c>();
    List<RICSC_Phone__c> phones = new List<RICSC_Phone__c>();
    List<RICSC_Relation__c> relations = new List<RICSC_Relation__c>();
    List<RICSC_Email__c> emails = new List<RICSC_Email__c>();
    List<RICSC_Wishlist__c> wishlists = new List<RICSC_Wishlist__c>();
    List<RICSC_SocialMediaID__c> socialmediaIDs = new List<RICSC_SocialMediaID__c>();

    Account acc = UtilityTests.getPersonAccount();
    acc.LastName = 'AccountTransactionOwner';
    acc.RICSC_CountryofOrigin__c='Greece';
    acc.RICSC_SourceCRM__c = UtilityConstants.SOURCE_CRM_SAP;
    insert acc;
    Account myowner = [SELECT id FROM Account WHERE LastName = 'AccountTransactionOwner'];
    RICSC_Address__c adr1 = UtilityTests.getAddress();
    adr1.RICSC_Account__c = myowner.Id;
    addresses.add(adr1);
    RICSC_Address__c adr2 = UtilityTests.getAddress();
    adr2.RICSC_Account__c = myowner.Id;
    addresses.add(adr2);
    insert addresses;
    RICSC_Activity__c act1 = UtilityTests.getActivity();
    act1.RICSC_Account__c = myowner.Id;
    act1.Name='Activity1';
    activities.add(act1);
    RICSC_Activity__c act2 = UtilityTests.getActivity();
    act2.RICSC_Account__c = myowner.Id;
    act2.Name='Activity2';
    activities.add(act2);
    insert activities;
    RICSC_Email__c em1 = UtilityTests.getEmail();
    em1.RICSC_Account__c = myowner.Id;
    emails.add(em1);
    RICSC_Email__c em2 = UtilityTests.getEmail();
    em2.RICSC_Account__c = myowner.Id;
    emails.add(em2);
    insert emails;
    RICSC_Phone__c ph1 = UtilityTests.getPhone();
    ph1.RICSC_Account__c = myowner.Id;
    phones.add(ph1);
    RICSC_Phone__c ph2 = UtilityTests.getPhone();
    ph2.RICSC_Account__c = myowner.Id;
    phones.add(ph2);
    insert phones;
    RICSC_SocialMediaID__c soc1 = UtilityTests.getSocialMediaID();
    soc1.RICSC_Account__c = myowner.Id;
    socialmediaIDs.add(soc1);
    RICSC_SocialMediaID__c soc2 = UtilityTests.getSocialMediaID();
    soc2.RICSC_Account__c = myowner.Id;
    socialmediaIDs.add(soc2);
    insert socialmediaIDs;
    RICSC_Relation__c rel1 = UtilityTests.getRelation();
    rel1.RICSC_Account__c = myowner.Id;
    relations.add(rel1);
    RICSC_Relation__c rel2 = UtilityTests.getRelation();
    rel2.RICSC_Account__c = myowner.Id;
    relations.add(rel2);
    insert relations;
    RICSC_Wishlist__c wis1 = UtilityTests.getWishlist();
    wis1.RICSC_Account__c = myowner.Id;
    wishlists.add(wis1);
    RICSC_Wishlist__c wis2 = UtilityTests.getWishlist();
    wis2.RICSC_Account__c = myowner.Id;
    wishlists.add(wis2);
    insert wishlists;
    wishlists = [SELECT Id, RICSC_Account__c, RICSC_GoldenRecord__c FROM RICSC_Wishlist__c];
    System.debug('==> wishlists: ' + wishlists);
  }

  static testmethod void test() {
    Test.startTest();
    BatchPopulateGoldenRecordLookup b = new BatchPopulateGoldenRecordLookup(false,null);
    b.skipTriggers = true;
    Id batchId = Database.executeBatch(b);
    Test.stopTest();

    List<SObject> objects = new List<SObject>();
    objects.addAll([SELECT RICSC_GR__c, RICSC_Account__c FROM RICSC_Email__c]);
    objects.addAll([SELECT RICSC_GoldenRecord__c, RICSC_Account__c FROM RICSC_Activity__c]);
    objects.addAll([SELECT RICSC_GR__c, RICSC_Account__c FROM RICSC_SocialMediaID__c]);
    objects.addAll([SELECT RICSC_GR__c, RICSC_Account__c FROM RICSC_Address__c]);
    objects.addAll([SELECT RICSC_GoldenRecord__c, RICSC_Account__c FROM RICSC_Wishlist__c]);
    objects.addAll([SELECT RICSC_GoldenRecord__c, RICSC_Account__c FROM RICSC_Relation__c]);
    objects.addAll([SELECT RICSC_GR__c, RICSC_Account__c FROM RICSC_Phone__c]);

    Boolean error = false;
    for(SObject obj : objects){
      if(obj.getSobjectType().getDescribe().fields.getMap().keySet().contains('ricsc_goldenrecord__c')){
        if(!obj.get('RICSC_GoldenRecord__c').toString().equals(obj.get('RICSC_Account__c').toString())){
          error = true;
        }
      }
      else if(obj.getSobjectType().getDescribe().fields.getMap().keySet().contains('ricsc_gr__c')){
        if(!obj.get('RICSC_GR__c').toString().equals(obj.get('RICSC_Account__c').toString())){
          error = true;
        }
      }
    }

    System.assert(!error, 'Lookup not populated correctly');
  }
}