unpackaged/main/default/objects/Account/fields/RICSC_CountryOfOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryOfOrigin__c</fullName>
        <description>Country where the record has been created. Used for the sharing rules (e.g. records created outside of China shouldn't be visible for the Chineese users) - Release 1 SC</description>
        <label>Account Country Of Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_ExtCreationDate__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ExtCreationDate__c</fullName>
        <description>Date and Time of the record creation in the source system</description>
        <label>Ext Creation Date</label>
        <type>Date</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Golden Record</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RICSC_IsGoldenRecord__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.RICSC_NotToBeGrouped__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Accounts (Local Records)</relationshipLabel>
        <relationshipName>RICSC_AccountGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_Maison__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Maison__c</fullName>
        <description>List of Maisons</description>
        <label>Account Maison</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Maison</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Asset/fields/RICSC_AmountWithTax__c.field-meta.xml
<CustomField>
        <fullName>RICSC_AmountWithTax__c</fullName>
        <description>Total amount of the transaction coming from the source system</description>
        <label>Amount With Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </CustomField>

unpackaged/main/default/objects/Asset/fields/RICSC_Boutique__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Boutique__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the Boutique</description>
        <label>Boutique</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Product Portfolios (Boutique)</relationshipLabel>
        <relationshipName>RICSC_AssetsBoutique</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Asset/fields/RICSC_CountryOfOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryOfOrigin__c</fullName>
        <description>Country where the record has been created. Used for the sharing rules (e.g. records created outside of China shouldn't be visible for the Chineese users) - Release 1 SC</description>
        <label>Country Of Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Asset/fields/RICSC_DistributionChannel__c.field-meta.xml
<CustomField>
        <fullName>RICSC_DistributionChannel__c</fullName>
        <label>Distribution Channel</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Asset/fields/RICSC_ExtCreationDate__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ExtCreationDate__c</fullName>
        <description>Date and Time of the record creation in the source system</description>
        <label>Ext Creation Date</label>
        <type>Date</type>
    </CustomField>

unpackaged/main/default/objects/Asset/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to a Golden Record which has been created for the Account - Release 1 SC</description>
        <label>Golden Record</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Product Portfolios</relationshipLabel>
        <relationshipName>RICSC_AssetsGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Asset/fields/RICSC_Maison__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Maison__c</fullName>
        <description>List of Maisons</description>
        <label>Maison</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Maison</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Asset/fields/RICSC_SalesAssociate__c.field-meta.xml
<CustomField>
        <fullName>RICSC_SalesAssociate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the Sales Associate</description>
        <label>Sales Associate</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Product Portfolios</relationshipLabel>
        <relationshipName>RICSC_ProductPortfoliosSalesAssociate</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Asset/fields/RICSC_TransactionID__c.field-meta.xml
<CustomField>
        <fullName>RICSC_TransactionID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction ID</label>
        <referenceTo>RICSC_Transaction__c</referenceTo>
        <relationshipLabel>Product Portfolios</relationshipLabel>
        <relationshipName>RICSC_AssetsTransaction</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Asset/fields/RICSC_TransactionNumber__c.field-meta.xml
<CustomField>
        <fullName>RICSC_TransactionNumber__c</fullName>
        <description>Transaction Number in external system</description>
        <label>Transaction Number</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Case/fields/RICSC_Boutique__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Boutique__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the Boutique</description>
        <label>Boutique</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Boutique)</relationshipLabel>
        <relationshipName>RICSC_TicketsBoutique</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Case/fields/RICSC_CountryofOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryofOrigin__c</fullName>
        <description>Origin of the Ticket</description>
        <label>Country of Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Case/fields/RICSC_ExtCreationDate__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ExtCreationDate__c</fullName>
        <description>Date and Time of the record creation in the source system</description>
        <label>Ext Creation Date</label>
        <type>Date</type>
    </CustomField>

unpackaged/main/default/objects/Case/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to a Golden Record which has been created for the Account</description>
        <label>Golden Record</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>RICSC_TicketsGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Case/fields/RICSC_Maison__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Maison__c</fullName>
        <description>List of Maisons to be able to drive</description>
        <label>Maison</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Maison</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/RICSC_Transaction__c.object-meta.xml
<CustomObject>
    <description>capture transaction information.</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{000000000}</displayFormat>
        <label>Transaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to an Account - Release 1 SC</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>RICSC_TransactionsAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_AmountWithTax__c.field-meta.xml
<CustomField>
        <fullName>RICSC_AmountWithTax__c</fullName>
        <description>Total amount of the transaction coming from the source system</description>
        <label>Amount With Tax</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_Boutique__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Boutique__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the Boutique</description>
        <label>Boutique</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transactions (Boutique)</relationshipLabel>
        <relationshipName>RICSC_TransactionsBoutique</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_Channel__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Channel__c</fullName>
        <description>Field to categorize the channel through which the transaction was handled</description>
        <label>Transaction Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Boutique</fullName>
                </value>
                <value>
                    <fullName>CC</fullName>
                </value>
                <value>
                    <fullName>Charity</fullName>
                </value>
                <value>
                    <fullName>Web</fullName>
                </value>
                <value>
                    <fullName>Wholesaler</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_CountryOfOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryOfOrigin__c</fullName>
        <description>Country where the record has been created. Used for the sharing rules (e.g. records created outside of China shouldn't be visible for the Chineese users) - Release 1 SC</description>
        <label>Country Of Transaction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to a Golden Record which has been created for the Account - Release 1 SC</description>
        <label>Golden Record</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>RICSC_TransactionsGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_Maison__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Maison__c</fullName>
        <description>List of Maisons</description>
        <label>Maison</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Maison</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_ProductName__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ProductName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the Product</description>
        <label>Product Name</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Names</relationshipLabel>
        <relationshipName>RICSC_ProductNames</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_SalesAssociate__c.field-meta.xml
<CustomField>
        <fullName>RICSC_SalesAssociate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the Sales Associate</description>
        <label>Sales Associate</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>RICSC_TransactionsSalesAssociate</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_SerialNumber__c.field-meta.xml
<CustomField>
        <fullName>RICSC_SerialNumber__c</fullName>
        <description>Serial Number of the product in the transaction</description>
        <label>Serial Number</label>
        <length>50</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_TransactionDate__c.field-meta.xml
<CustomField>
        <fullName>RICSC_TransactionDate__c</fullName>
        <description>Transaction Date in external system</description>
        <label>Transaction Date</label>
        <type>Date</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_TransactionNumber__c.field-meta.xml
<CustomField>
        <fullName>RICSC_TransactionNumber__c</fullName>
        <description>Transaction Number in external system</description>
        <label>Transaction Number</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/globalValueSets/RICSC_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Amer.Virgin Is.</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua/Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia-Herz.</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Islands</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/RICSC_Maison.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cartier</fullName>
    </customValue>
    <customValue>
        <fullName>Jaeger Le Coultre</fullName>
    </customValue>
    <customValue>
        <fullName>Van Cleef &amp; Arpels</fullName>
    </customValue>
    <masterLabel>Maison</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/ProductPortfolioIntegration.cls
/******************************************************************************
* @author       Silvan Sholla
* @date         28/11/2019
* @description  Creation or the update of Assets based on the following criteria
*               ** if there is a match of the Serial numbers then:
                Verify if the amount on the transaction is positive
                ** if yes = update Product Portfolio (Asset) with the values from Transaction
                else = Mark Product Portfolio (Asset) field Product Refunded
                ** if there is no match of the Serial numbers then:

                Create a new record in Product Portfolio (Asset) based
                on the fields queried in the transaction & mapping of
                Product Portfolio fields, link it to the same account as the transaction
                Insert Transaction ID in the lookup to link the records
******************************************************************************/

public without sharing class ProductPortfolioIntegration {
  public static List<Asset> productPortfolioTransactionPropagation(List<RICSC_Transaction__c> transactionList){


    Set<Id> accIdsGR = new Set<Id>();
    List<RICSC_Transaction__c> involvedTransaction = new List<RICSC_Transaction__c>();
    Map<Id, Account> assetsByAccountId = new Map<Id, Account>();
    Map<String,Asset> assetsToBeUpdatedMap = new Map<String,Asset>();

    //the golden record account will be always filled except the case it doesnt have any account id
    for(RICSC_Transaction__c tr : (List<RICSC_Transaction__c>) transactionList){
      if(tr.RICSC_GoldenRecord__c != null){
        accIdsGR.add(tr.RICSC_GoldenRecord__c);
        involvedTransaction.add(tr);
      }
    }

    if(accIdsGR.size() >0){
      if (Schema.sObjectType.Asset.isAccessible()) {
        // it creates a map with account id as key and list of assets as value per each id
        assetsByAccountId = new Map<Id, Account>([SELECT Id,(SELECT Id,SerialNumber,RICSC_GoldenRecord__c,AccountId FROM RICSC_AssetsGoldenRecord__r) FROM Account WHERE Id IN :accIdsGR ]);
      }
      for(RICSC_Transaction__c tr : involvedTransaction){
        Boolean hasAsset = false;
        //it checks if the certain account has related assets , in case it has and serial number
        //matches the assets it being updated based on the transaction
        if(assetsByAccountId.get(tr.RICSC_GoldenRecord__c).RICSC_AssetsGoldenRecord__r != null){
          for(Asset ast: assetsByAccountId.get(tr.RICSC_GoldenRecord__c).RICSC_AssetsGoldenRecord__r) {
            if(tr.RICSC_SerialNumber__c == ast.SerialNumber){
              hasAsset = true;
              Asset assetAfterConditionCheck = assetUpdateBasedOnTheTransaction(tr,ast);
              assetsToBeUpdatedMap.put(assetAfterConditionCheck.SerialNumber,assetAfterConditionCheck);
              // assets with same serial number its not possible so in case the account got 1000 assets
              // it doesnt have to search for all if the asset with same id is in first row
              break;
            }
          }
        }

        //in case that doesnt have any asset totally create a new asset even if there is not any asset with same lookup
        if(!hasAsset){
          Asset assetAfterConditionCheck = assetCreationBasedOnTheTransaction(tr);
          assetsToBeUpdatedMap.put(assetAfterConditionCheck.SerialNumber,assetAfterConditionCheck);
        }
      }
    }
    return assetsToBeUpdatedMap.values();
  }

  public static Asset assetUpdateBasedOnTheTransaction(RICSC_Transaction__c tr,Asset ast){
    Asset updatedAsset = new Asset();

    updatedAsset.Id = ast.Id;
    updatedAsset.RICSC_GoldenRecord__c = tr.RICSC_GoldenRecord__c;
    updatedAsset.AccountId = tr.RICSC_Account__c;
    updatedAsset.Name = 'PP-'+tr.RICSC_SerialNumber__c;
    updatedAsset.RICSC_CountryOfOrigin__c = tr.RICSC_CountryOfOrigin__c;
    updatedAsset.RICSC_Maison__c = tr.RICSC_Maison__c;
    updatedAsset.RICSC_SalesAssociate__c = tr.RICSC_SalesAssociate__c;
    updatedAsset.Product2Id = tr.RICSC_ProductName__c;
    updatedAsset.PurchaseDate = tr.RICSC_TransactionDate__c;
    updatedAsset.RICSC_DistributionChannel__c = tr.RICSC_Channel__c;
    updatedAsset.RICSC_Boutique__c = tr.RICSC_Boutique__c;
    updatedAsset.RICSC_ExtCreationDate__c = tr.RICSC_ExtCreationDate__c;
    updatedAsset.RICSC_TransactionID__c = tr.Id;
    updatedAsset.SerialNumber = tr.RICSC_SerialNumber__c;
    updatedAsset.RICSC_TransactionNumber__c = tr.RICSC_TransactionNumber__c;
    updatedAsset.RICSC_AmountWithTax__c = tr.RICSC_AmountWithTax__c;
    if(tr.RICSC_AmountWithTax__c < 0){
      updatedAsset.RICSC_ProductsReturned__c = true;
    }else{
      updatedAsset.RICSC_ProductsReturned__c = false;
    }

    return updatedAsset;
  }

  public static Asset assetCreationBasedOnTheTransaction(RICSC_Transaction__c tr){
    Asset updatedAsset = new Asset();
    updatedAsset.RICSC_GoldenRecord__c = tr.RICSC_GoldenRecord__c;
    updatedAsset.AccountId = tr.RICSC_Account__c;
    updatedAsset.RICSC_CountryOfOrigin__c = tr.RICSC_CountryOfOrigin__c;
    updatedAsset.RICSC_Maison__c = tr.RICSC_Maison__c;
    updatedAsset.Name = 'PP-'+tr.RICSC_SerialNumber__c;
    updatedAsset.RICSC_SalesAssociate__c = tr.RICSC_SalesAssociate__c;
    updatedAsset.Product2Id = tr.RICSC_ProductName__c;
    updatedAsset.PurchaseDate = tr.RICSC_TransactionDate__c;
    updatedAsset.SerialNumber = tr.RICSC_SerialNumber__c;
    updatedAsset.RICSC_DistributionChannel__c = tr.RICSC_Channel__c;
    updatedAsset.RICSC_Boutique__c = tr.RICSC_Boutique__c;
    updatedAsset.RICSC_ExtCreationDate__c = tr.RICSC_ExtCreationDate__c;
    updatedAsset.RICSC_TransactionID__c = tr.Id;
    updatedAsset.RICSC_TransactionNumber__c = tr.RICSC_TransactionNumber__c;
    updatedAsset.RICSC_AmountWithTax__c = tr.RICSC_AmountWithTax__c;
    if(tr.RICSC_AmountWithTax__c < 0){
      updatedAsset.RICSC_ProductsReturned__c = true;
    }else{
      updatedAsset.RICSC_ProductsReturned__c = false;
    }
    return updatedAsset;
  }

  public static void duplicateCheckOverSerialNumber(Map<String,Asset> serialNumberAssetMap){
    List<Asset> alreadyImportedAssets = [SELECT SerialNumber,AccountId FROM Asset WHERE SerialNumber IN :serialNumberAssetMap.keySet()];
    Map<String,Asset> alreadyImportedAssetsMap = new Map<String,Asset>();
    List<Asset> assetsToBeDeleted = new List<Asset>();
    for(Asset ast : alreadyImportedAssets){
      alreadyImportedAssetsMap.put(ast.SerialNumber,ast);
    }
    List<Asset> assetsToBeImported = new List<Asset>();
    for(Asset currentAsset : serialNumberAssetMap.values()){
      if(alreadyImportedAssetsMap.keySet().contains(currentAsset.SerialNumber)){
        if(currentAsset.AccountId != null){
          currentAsset.AccountId = alreadyImportedAssetsMap.get(currentAsset.SerialNumber).AccountId;
        }
        assetsToBeDeleted.add(alreadyImportedAssetsMap.get(currentAsset.SerialNumber));
      }
    }
    // deleted the previously imported record with the same SerialNumber as the newly imported and importing the new instaid
    delete assetsToBeDeleted;
  }
}