unpackaged/main/default/objects/Account/fields/RICSC_CountryOfOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryOfOrigin__c</fullName>
        <description>Country where the record has been created. Used for the sharing rules (e.g. records created outside of China shouldn't be visible for the Chineese users) - Release 1 SC</description>
        <label>Account Country Of Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_ResidentNonResident__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ResidentNonResident__c</fullName>
        <description>Calculated segmentation based on the travel habits of a client</description>
        <label>Resident/Non Resident</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Non-Resident</fullName>
                </value>
                <value>
                    <fullName>Resident</fullName>
                </value>
                <value>
                    <fullName>Traveller</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Address__c/RICSC_Address__c.object-meta.xml
<CustomObject>
    <description>This object is used to collect  the Addresses of the related Local records.</description>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Address__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to Account (Contact)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>RICSC_AddressesAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Address__c/fields/RICSC_Address__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Address__c</fullName>
        <description>Field to capture the full address</description>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Address__c/fields/RICSC_AddressType__c.field-meta.xml
<CustomField>
        <fullName>RICSC_AddressType__c</fullName>
        <description>Picklist to capture the type of address</description>
        <label>Address Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Boutique</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Home Address</fullName>
                </value>
                <value>
                    <fullName>Office Address</fullName>
                </value>
                <value>
                    <fullName>Old Address</fullName>
                </value>
                <value>
                    <fullName>Past</fullName>
                </value>
                <value>
                    <fullName>Residency</fullName>
                </value>
                <value>
                    <fullName>Secondary Residence</fullName>
                </value>
                <value>
                    <fullName>Shipping Address</fullName>
                </value>
                <value>
                    <fullName>Summer Home</fullName>
                </value>
                <value>
                    <fullName>Temporary / Hotel</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>Web</fullName>
                </value>
                <value>
                    <fullName>Web Unknown</fullName>
                </value>
                <value>
                    <fullName>Winter Home</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Address__c/fields/RICSC_Country__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Country__c</fullName>
        <description>Picklist to capture the country of the address</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/RICSC_Transaction__c.object-meta.xml
<CustomObject>
    <description>capture transaction information.</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{000000000}</displayFormat>
        <label>Transaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to an Account - Release 1 SC</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>RICSC_TransactionsAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_CountryOfOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryOfOrigin__c</fullName>
        <description>Country where the record has been created. Used for the sharing rules (e.g. records created outside of China shouldn't be visible for the Chineese users) - Release 1 SC</description>
        <label>Country Of Transaction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/globalValueSets/RICSC_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Amer.Virgin Is.</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua/Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia-Herz.</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Uganda</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/BatchResidenceNonResidence_Test.cls
@isTest
private class BatchResidenceNonResidence_Test {

  @testSetup
  static void setup() {
    UtilityTests.testSetup();
    List<Account> accounts = UtilityTests.getAccounts(3);
    insert accounts;

    List<RICSC_Address__c> addressList = new List<RICSC_Address__c>();
    List<RICSC_Transaction__c> transactionsList = new List<RICSC_Transaction__c>();
    Account acc = accounts.get(0);
    RICSC_Address__c address = UtilityTests.getAddress();
    address.RICSC_AddressType__c = 'Residency';
    address.RICSC_Country__c = 'Italy';
    address.RICSC_Account__c = acc.Id;
    addressList.add(address);

    RICSC_Transaction__c t = UtilityTests.getTransaction();
    t.RICSC_Account__c = acc.Id;
    t.RICSC_CountryOfOrigin__c = 'Italy';
    transactionsList.add(t);

    acc = accounts.get(1);
    address = UtilityTests.getAddress();
    address.RICSC_AddressType__c = 'Residency';
    address.RICSC_Country__c = 'Italy';
    address.RICSC_Account__c = acc.Id;
    addressList.add(address);

    t = UtilityTests.getTransaction();
    t.RICSC_Account__c = acc.Id;
    t.RICSC_CountryOfOrigin__c = 'Uganda';
    transactionsList.add(t);

    acc = accounts.get(2);
    address = UtilityTests.getAddress();
    address.RICSC_AddressType__c = 'Residency';
    address.RICSC_Country__c = 'Italy';
    address.RICSC_Account__c = acc.Id;
    addressList.add(address);

    t = UtilityTests.getTransaction();
    t.RICSC_Account__c = acc.Id;
    t.RICSC_CountryOfOrigin__c = 'Uganda';
    transactionsList.add(t);
    t = UtilityTests.getTransaction();
    t.RICSC_Account__c = acc.Id;
    t.RICSC_CountryOfOrigin__c = 'Italy';
    transactionsList.add(t);

    insert addressList;
    insert transactionsList;
}

  static testmethod void calculateResidenceNonResidence() {
    Test.startTest();
    BatchResidenceNonResidence b = new BatchResidenceNonResidence(false,null);
    Id batchId = Database.executeBatch(b);
    List<Account> accounts = [SELECT Id, RICSC_ResidentNonResident__c FROM Account];
    Test.stopTest();
    List<Account> residentAccounts = new List<Account>();
    List<Account> nonResidentAccounts = new List<Account>();
    List<Account> travellerAccounts = new List<Account>();
    for(Account acc : accounts){
      if(acc.RICSC_ResidentNonResident__c.equals('Resident')){
        residentAccounts.add(acc);
      }
      else if (acc.RICSC_ResidentNonResident__c.equals('Non-Resident')){
        nonResidentAccounts.add(acc);
      }
      else if (acc.RICSC_ResidentNonResident__c.equals('Traveller')){
        travellerAccounts.add(acc);
      }
    }
    System.assert(residentAccounts.size()==1, 'Assertion failed on resident accounts');
    System.assert(nonResidentAccounts.size()==1, 'Assertion failed on non-resident accounts');
    System.assert(travellerAccounts.size()==1, 'Assertion failed on traveller accounts');
  }
}