unpackaged/main/default/objects/Account/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Golden Record</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RICSC_IsGoldenRecord__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.RICSC_NotToBeGrouped__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Accounts (Local Records)</relationshipLabel>
        <relationshipName>RICSC_AccountGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_Maison__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Maison__c</fullName>
        <description>List of Maisons</description>
        <label>Account Maison</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Maison</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_MRScoreFrequency__c.field-meta.xml
<CustomField>
        <fullName>RICSC_MRScoreFrequency__c</fullName>
        <description>Technical field to calculate the score - Not visible at Layout</description>
        <label>MR Score: Frequency</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_MRScoreTurnover__c.field-meta.xml
<CustomField>
        <fullName>RICSC_MRScoreTurnover__c</fullName>
        <description>Field used for calculation of a custom Turnover Score for Master Record selection Score. It counts all historical transaction</description>
        <label>MR Score: Turnover</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/RICSC_Transaction__c.object-meta.xml
<CustomObject>
    <description>capture transaction information.</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{000000000}</displayFormat>
        <label>Transaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to an Account - Release 1 SC</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>RICSC_TransactionsAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_AmountWithTaxEUR__c.field-meta.xml
<CustomField>
        <fullName>RICSC_AmountWithTaxEUR__c</fullName>
        <description>Total amount of the transaction coming from the source system</description>
        <label>Amount With Tax EUR</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to a Golden Record which has been created for the Account - Release 1 SC</description>
        <label>Golden Record</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>RICSC_TransactionsGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_Maison__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Maison__c</fullName>
        <description>List of Maisons</description>
        <label>Maison</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Maison</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_SerialNumber__c.field-meta.xml
<CustomField>
        <fullName>RICSC_SerialNumber__c</fullName>
        <description>Serial Number of the product in the transaction</description>
        <label>Serial Number</label>
        <length>50</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_TransactionCategory__c.field-meta.xml
<CustomField>
        <fullName>RICSC_TransactionCategory__c</fullName>
        <description>Field to categorize a transaction of a certain type as Repair, Return, Sale</description>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Repair</fullName>
                </value>
                <value>
                    <fullName>Return</fullName>
                </value>
                <value>
                    <fullName>Sale</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_TransactionDate__c.field-meta.xml
<CustomField>
        <fullName>RICSC_TransactionDate__c</fullName>
        <description>Transaction Date in external system</description>
        <label>Transaction Date</label>
        <type>Date</type>
    </CustomField>

unpackaged/main/default/globalValueSets/RICSC_Maison.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cartier</fullName>
    </customValue>
    <customValue>
        <fullName>Jaeger Le Coultre</fullName>
    </customValue>
    <customValue>
        <fullName>Van Cleef &amp; Arpels</fullName>
    </customValue>
    <masterLabel>Maison</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/BatchMRScoreCalculation.cls
/************************************************************************************
* @author       Dimitris Rakantas
* @date         15/11/2019
* @description  Calculation of MR Turnover and Frequency on Accounts

***************************************************************************************/

public class BatchMRScoreCalculation implements
  Database.Batchable<sObject>, Schedulable {
  private Boolean skipTriggersOnAccount;
  public static final Integer MAX_SCOPE = 100;
  private String query = 'SELECT id,RICSC_MRScoreTurnover__c,RICSC_MRScoreFrequency__c FROM Account where isPersonAccount = true';

  public BatchMRScoreCalculation(Boolean skipParam, String queryStr) {
    skipTriggersOnAccount = skipParam;
    this.query = queryStr == null ? this.query : queryStr;
  }

  public void execute(SchedulableContext sc) {
    BatchMRScoreCalculation b = new BatchMRScoreCalculation(false, null);
    Database.executeBatch(b, MAX_SCOPE);
  }

  public Database.QueryLocator start(Database.BatchableContext bc) {
      return Database.getQueryLocator(this.query);
  }
  public void execute(Database.BatchableContext bc, List<Account> scope)  {
    try {

      Date before5years = System.now().addYears(-5).date();

      List<Id> accountIds = new List<Id>();
      for (Account a : scope){
      	accountIds.add(a.Id);
      }

      Map<id,Account> accountTransactions= new Map<id, Account>([SELECT Id, (SELECT id,RICSC_GoldenRecord__c,RICSC_AmountWithTaxEUR__c,RICSC_TransactionDate__c,RICSC_SerialNumber__c,
                                              RICSC_Maison__c,RICSC_TransactionCategory__c from RICSC_TransactionsAccount__r),
                                              (SELECT id,RICSC_Account__c,RICSC_AmountWithTaxEUR__c,RICSC_TransactionDate__c,RICSC_SerialNumber__c,
                                              RICSC_Maison__c,RICSC_TransactionCategory__c from RICSC_TransactionsGoldenRecord__r)
                                              FROM Account where Id in :accountIds]);


      Map<id,Set<Date>> transactionsDatesMap = new Map<id,Set<Date>>();

      for (Account a : scope){
        a.RICSC_MRScoreTurnover__c=0;
        a.RICSC_MRScoreFrequency__c=0;
        transactionsDatesMap.put(a.id,new Set<Date>());
        Set<RICSC_Transaction__c> traccs = new Set<RICSC_Transaction__c>();
        if (accountTransactions.get(a.Id).RICSC_TransactionsAccount__r.size()>0){
          traccs.addAll(accountTransactions.get(a.Id).RICSC_TransactionsAccount__r);
        }
        if (accountTransactions.get(a.Id).RICSC_TransactionsGoldenRecord__r.size()>0){
          traccs.addAll(accountTransactions.get(a.Id).RICSC_TransactionsGoldenRecord__r);
        }
        for (RICSC_Transaction__c t : traccs){
          if(t.RICSC_TransactionCategory__c==UtilityConstants.TRANSACTION_TYPE_REPAIR || (t.RICSC_TransactionCategory__c==UtilityConstants.TRANSACTION_TYPE_SALES && (t.RICSC_AmountWithTaxEUR__c == 0 || t.RICSC_AmountWithTaxEUR__c == null))){
            continue;
          }
          if (t.RICSC_TransactionCategory__c==UtilityConstants.TRANSACTION_TYPE_SALES){
              if((t.RICSC_Maison__c==UtilityConstants.MAISON_CARTIER || t.RICSC_Maison__c==UtilityConstants.MAISON_VAN_CLEEF_ARPELS) && t.RICSC_TransactionDate__c != null){
                if(t.RICSC_TransactionDate__c>=before5years){
                  if (!transactionsDatesMap.get(a.id).contains(t.RICSC_TransactionDate__c)){
                    a.RICSC_MRScoreFrequency__c++;
                    transactionsDatesMap.get(a.id).add(t.RICSC_TransactionDate__c);
                  }
                  if (t.RICSC_AmountWithTaxEUR__c == null){
                    t.RICSC_AmountWithTaxEUR__c = 0;
                  }
                  a.RICSC_MRScoreTurnover__c+=t.RICSC_AmountWithTaxEUR__c;
                }
              }
              else if (t.RICSC_Maison__c==UtilityConstants.MAISON_JAEGER_LE_COULTRE && t.RICSC_TransactionDate__c != null){
                if (!transactionsDatesMap.get(a.id).contains(t.RICSC_TransactionDate__c)){
                  a.RICSC_MRScoreFrequency__c++;
                  transactionsDatesMap.get(a.id).add(t.RICSC_TransactionDate__c);
                }
                if (t.RICSC_AmountWithTaxEUR__c == null){
                  t.RICSC_AmountWithTaxEUR__c = 0;
                }
                a.RICSC_MRScoreTurnover__c+=t.RICSC_AmountWithTaxEUR__c;
              }
            } else if (t.RICSC_TransactionCategory__c==UtilityConstants.TRANSACTION_TYPE_RETURN && t.RICSC_AmountWithTaxEUR__c != null){
              a.RICSC_MRScoreTurnover__c+=t.RICSC_AmountWithTaxEUR__c;
            }
          }
        }

        if(skipTriggersOnAccount){
          TRG_TriggerDispatcher.skipTriggerMap.put('Account',true);
        }
        Database.SaveResult[] srList = Database.update(scope,false);
        UtilityLogger.logAllErrors(srList, false, 'BatchMRScoreCalculation','execute');
        if(skipTriggersOnAccount){
          TRG_TriggerDispatcher.skipTriggerMap.put('Account',false);
        }

    } catch(Exception e) {
      UtilityLogger.logException(e,e.getMessage(),'BatchMRScoreCalculation','execute');
    }
  }
  public void finish(Database.BatchableContext bc){

  }
}