unpackaged/main/default/objects/Account/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Golden Record</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RICSC_IsGoldenRecord__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.RICSC_NotToBeGrouped__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Accounts (Local Records)</relationshipLabel>
        <relationshipName>RICSC_AccountGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_MasterRecordScore__c.field-meta.xml
<CustomField>
        <fullName>RICSC_MasterRecordScore__c</fullName>
        <description>This field is used to calculate a score for the Genera Rule for the Master Record Definition during the merge process.</description>
        <formula>RICSC_MRScoreTurnover__c  *  RICSC_MRScoreFrequency__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Master Record Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_NotToBeGrouped__c.field-meta.xml
<CustomField>
        <fullName>RICSC_NotToBeGrouped__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to avoid the Account record to be merged with others in any case</description>
        <label>Not To Be Grouped</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/classes/MergeExtension.cls
global class MergeExtension implements dupcheck.dc3Plugin.InterfaceMerge {

  global static void beforeMerge(String objectPrefix, Sobject masterRecord, List < sobject > mergedRecordList) {
    System.debug('==> beforeMerge');
    if(objectPrefix.equalsIgnoreCase('001P')){
      System.debug('==> object prefix match');
      Set<Id> mergedRecordsIds = new Set<Id>();
      for(SObject mergeRecord : mergedRecordList) {
          mergedRecordsIds.add(mergeRecord.Id);
      }
      Set<Id> mergedIdsAndMaster = new Set<Id>(mergedRecordsIds);
      mergedIdsAndMaster.add(masterRecord.Id);
      if(!UtilityAccount.falseDuplicatesInSet(mergedIdsAndMaster)){
        String query = Utility.getSOQLWithFieldsFilter('account', '(Id IN :mergedIdsAndMaster OR RICSC_GoldenRecord__c IN :mergedRecordsIds) AND RICSC_NotToBeGrouped__c = false', null, UtilityConstants.SOQLFieldsFilter.ALL);
        Map<Id, Account> mergedAccounts = new Map<Id,Account>((List<Account>)Database.query(query));
        if(mergedAccounts.size() > 1){
          Map<Id, List<SObject>> relatedObjectsMap = UtilityAccount.getAccountsRelatedObjects(mergedAccounts.keySet());
          if(mergedAccounts.get(masterRecord.Id) == null){
            Decimal higherMasterRecordScore;
            for(Account acc: mergedAccounts.values()){
              if(higherMasterRecordScore == null || acc.RICSC_MasterRecordScore__c > higherMasterRecordScore){
                masterRecord = acc;
                higherMasterRecordScore = acc.RICSC_MasterRecordScore__c;
              }
            }
          }
          UtilityAccount.goldenRecordManagement((Account)masterRecord, mergedAccounts, null, relatedObjectsMap);
        }
      }
      throw new dupcheck.dc3Exception.NoProcessException('NO_MERGE');
    }
  }

  global void mergeFailed(String objectPrefix, Sobject masterRecord, Set < id > mergedRecordsIds, dupcheck.dc3Exception.MergeException exceptionData) {
    System.debug('==> merge Failed');
    return;
  }

  global void afterMerge(String objectPrefix, Sobject masterRecord, Set < id > mergedRecordIds) {
    System.debug('==> After merge');
  }

}