unpackaged/main/default/objects/Account/fields/RICSC_CountryOfOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryOfOrigin__c</fullName>
        <description>Country where the record has been created. Used for the sharing rules (e.g. records created outside of China shouldn't be visible for the Chineese users) - Release 1 SC</description>
        <label>Account Country Of Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_FirstSalesDate__c.field-meta.xml
<CustomField>
        <fullName>RICSC_FirstSalesDate__c</fullName>
        <description>Date that client made first purchase</description>
        <label>First Sales Date</label>
        <type>Date</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Golden Record</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RICSC_IsGoldenRecord__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.RICSC_NotToBeGrouped__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Accounts (Local Records)</relationshipLabel>
        <relationshipName>RICSC_AccountGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_Localisation__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Localisation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to the localisation object</description>
        <label>Localisation</label>
        <referenceTo>RICSC_Localisation__c</referenceTo>
        <relationshipLabel>Boutiques</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_Maison__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Maison__c</fullName>
        <description>List of Maisons</description>
        <label>Account Maison</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Maison</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_ReferenceBoutique__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ReferenceBoutique__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is populated with the SF ID correspondent to the respective SAP boutique coming from SAP as a consequence of a calculation</description>
        <label>Reference Boutique</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Reference Boutique)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_ReferenceSA__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ReferenceSA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is populated with the SF ID correspondent to the respective SAP SA coming from SAP as a consequence of a calculation</description>
        <label>Reference SA</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (Reference SA)</relationshipLabel>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_Top1Boutique__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Top1Boutique__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field retrieves the Top 1 Boutique based on rules defined in Salesforce</description>
        <label>Top 1 Boutique</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Top 1 Boutique)</relationshipLabel>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_Top1SA__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Top1SA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field retrieves the top sales assistant based on turnover and frequency</description>
        <label>Top 1 SA</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_TotalNumberOfRepairs__c.field-meta.xml
<CustomField>
        <fullName>RICSC_TotalNumberOfRepairs__c</fullName>
        <description>Calculated number field of all the repairs (of all products)</description>
        <label>Total Number Of Repairs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_VIP__c.field-meta.xml
<CustomField>
        <fullName>RICSC_VIP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Client categorization based on perceived value</description>
        <label>VIP</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Contact/fields/RICSC_Boutique__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Boutique__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the Boutique</description>
        <label>Boutique</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Boutique</relationshipLabel>
        <relationshipName>RICSC_ContactsBoutique</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Contact/fields/RICSC_CountryOfOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryOfOrigin__c</fullName>
        <description>Country where the record has been created. Used for the sharing rules (e.g. records created outside of China shouldn't be visible for the Chineese users) - Release 1 SC</description>
        <label>Sales Associate Country Of Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Contact/fields/RICSC_Maison__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Maison__c</fullName>
        <description>List of Maisons</description>
        <label>Sales Associate Maison</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Maison</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </RecordType>

unpackaged/main/default/objects/RICSC_Localisation__c/RICSC_Localisation__c.object-meta.xml
<CustomObject>
    <description>Object to represent localisation structure of each Maison on the country, market and region level</description>
    <label>Localisation</label>
    <nameField>
        <label>Localisation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Localisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RICSC_Localisation__c/fields/RICSC_LocalisationLevel__c.field-meta.xml
<CustomField>
        <fullName>RICSC_LocalisationLevel__c</fullName>
        <label>Localisation Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Country</fullName>
                </value>
                <value>
                    <fullName>Region</fullName>
                </value>
                <value>
                    <fullName>Market</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Localisation__c/fields/RICSC_Maison__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Maison__c</fullName>
        <description>Maison of the Localisation record</description>
        <label>Maison</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Maison</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Localisation__c/fields/RICSC_ParentLocalisation__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ParentLocalisation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relation to the higher level of Localisation</description>
        <label>Parent Localisation</label>
        <referenceTo>RICSC_Localisation__c</referenceTo>
        <relationshipLabel>Localisations</relationshipLabel>
        <relationshipName>RICSC_ParentLocalisation</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/RICSC_Transaction__c.object-meta.xml
<CustomObject>
    <description>capture transaction information.</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{000000000}</displayFormat>
        <label>Transaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to an Account - Release 1 SC</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>RICSC_TransactionsAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_AmountWithTaxEUR__c.field-meta.xml
<CustomField>
        <fullName>RICSC_AmountWithTaxEUR__c</fullName>
        <description>Total amount of the transaction coming from the source system</description>
        <label>Amount With Tax EUR</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_Boutique__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Boutique__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the Boutique</description>
        <label>Boutique</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transactions (Boutique)</relationshipLabel>
        <relationshipName>RICSC_TransactionsBoutique</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_CountryOfOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryOfOrigin__c</fullName>
        <description>Country where the record has been created. Used for the sharing rules (e.g. records created outside of China shouldn't be visible for the Chineese users) - Release 1 SC</description>
        <label>Country Of Transaction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_CurrencyKey__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CurrencyKey__c</fullName>
        <description>Currency keycoming from the source system</description>
        <label>Currency Key</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Currency</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to a Golden Record which has been created for the Account - Release 1 SC</description>
        <label>Golden Record</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>RICSC_TransactionsGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_Maison__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Maison__c</fullName>
        <description>List of Maisons</description>
        <label>Maison</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Maison</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_SalesAssociate__c.field-meta.xml
<CustomField>
        <fullName>RICSC_SalesAssociate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the Sales Associate</description>
        <label>Sales Associate</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>RICSC_TransactionsSalesAssociate</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_TransactionCategory__c.field-meta.xml
<CustomField>
        <fullName>RICSC_TransactionCategory__c</fullName>
        <description>Field to categorize a transaction of a certain type as Repair, Return, Sale</description>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Repair</fullName>
                </value>
                <value>
                    <fullName>Return</fullName>
                </value>
                <value>
                    <fullName>Sale</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_TransactionDate__c.field-meta.xml
<CustomField>
        <fullName>RICSC_TransactionDate__c</fullName>
        <description>Transaction Date in external system</description>
        <label>Transaction Date</label>
        <type>Date</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_VIP__c.field-meta.xml
<CustomField>
        <fullName>RICSC_VIP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It identifies if the Record is VIP or not . It is recalculated at the GR record level based on Maisons' rules</description>
        <label>VIP</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/globalValueSets/RICSC_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Amer.Virgin Is.</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua/Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia-Herz.</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Islands</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Monaco</fullName>
    </customValue>
    <customValue>
        <fullName>USA</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/RICSC_Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AWG</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BOV</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BTN</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYR</fullName>
    </customValue>
    <customValue>
        <fullName>BZD</fullName>
    </customValue>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <customValue>
        <fullName>CDF</fullName>
    </customValue>
    <customValue>
        <fullName>CHE</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <description>Unit of measurecoming</description>
    <masterLabel>Currency</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/RICSC_Maison.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cartier</fullName>
    </customValue>
    <customValue>
        <fullName>Jaeger Le Coultre</fullName>
    </customValue>
    <customValue>
        <fullName>Van Cleef &amp; Arpels</fullName>
    </customValue>
    <masterLabel>Maison</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/CalculatingFieldsHandler_Test.cls
@isTest
private class CalculatingFieldsHandler_Test {

  @testSetup
  static void setup() {

    RICSC_Localisation__c franceLocalisationRegion = new RICSC_Localisation__c();
    FranceLocalisationRegion.RICSC_LocalisationLevel__c = 'Region';
		FranceLocalisationRegion.Name = 'Europe';
	  FranceLocalisationRegion.RICSC_Maison__c = 'Cartier';
    insert FranceLocalisationRegion;

    RICSC_Localisation__c franceLocalisationMarket = new RICSC_Localisation__c();
    FranceLocalisationMarket.RICSC_LocalisationLevel__c = 'Market';
		FranceLocalisationMarket.Name = 'France';
		FranceLocalisationMarket.RICSC_ParentLocalisation__c = FranceLocalisationRegion.Id;
	  FranceLocalisationMarket.RICSC_Maison__c = 'Cartier';
    insert FranceLocalisationMarket;

    RICSC_Localisation__c franceLocalisation = new RICSC_Localisation__c();
    FranceLocalisation.RICSC_LocalisationLevel__c = 'Country';
		FranceLocalisation.Name = 'France';
		FranceLocalisation.RICSC_ParentLocalisation__c = FranceLocalisationMarket.Id;
	  FranceLocalisation.RICSC_Maison__c = 'Cartier';
    insert franceLocalisation;

    Contact newFrenchSalesAssociate = UtilityTests.getContact();
    newFrenchSalesAssociate.RICSC_CountryOfOrigin__c = 'France';
    insert newFrenchSalesAssociate;

    Account transactionBoutique = UtilityTests.getBoutique();
    transactionBoutique.Name = 'TransactionBoutique';
    transactionBoutique.RICSC_CountryOfOrigin__c = 'France';
    transactionBoutique.RICSC_Maison__c = 'Cartier';
    insert transactionBoutique;

    Account referenceSABoutique = UtilityTests.getBoutique();
    referenceSABoutique.Name = 'ReferenceSABoutique';
    referenceSABoutique.RICSC_CountryOfOrigin__c = 'France';
    referenceSABoutique.RICSC_Maison__c = 'Cartier';
    insert referenceSABoutique;

    Contact newUSASalesAssociate = UtilityTests.getContact();
    newUSASalesAssociate.RICSC_CountryOfOrigin__c = 'USA';
    newUSASalesAssociate.AccountId = referenceSABoutique.Id;
    insert newUSASalesAssociate;

    Account newVanCleefAndArpelsGoldenRecord = UtilityTests.getPersonAccount();
    newVanCleefAndArpelsGoldenRecord.LastName = 'VanCleefAndArpelsGoldenRecordAccount';
    newVanCleefAndArpelsGoldenRecord.RICSC_VIP__c = true;
    newVanCleefAndArpelsGoldenRecord.RICSC_TotalNumberOfRepairs__c = 2;
    newVanCleefAndArpelsGoldenRecord.RICSC_TotalNumberOfRepairs__c = 0;
    newVanCleefAndArpelsGoldenRecord.RICSC_ReferenceSA__c = newFrenchSalesAssociate.Id;
    insert newVanCleefAndArpelsGoldenRecord;

    Account newVanCleefAndArpelsAccount = UtilityTests.getPersonAccount();
    newVanCleefAndArpelsAccount.LastName = 'VanCleefAndArpelsLocalReordAccount';
    newVanCleefAndArpelsAccount.RICSC_VIP__c = true;
    newVanCleefAndArpelsAccount.RICSC_ReferenceSA__c = newFrenchSalesAssociate.Id;
    insert newVanCleefAndArpelsAccount;

    newVanCleefAndArpelsAccount.RICSC_GoldenRecord__c = newVanCleefAndArpelsGoldenRecord.id;
    update newVanCleefAndArpelsAccount;

    RICSC_Transaction__c testTransaction = new RICSC_Transaction__c(RICSC_SalesAssociate__c = newUSASalesAssociate.Id,RICSC_Boutique__c = transactionBoutique.Id,RICSC_Account__c = newVanCleefAndArpelsAccount.Id,RICSC_Maison__c = 'Cartier',RICSC_TransactionCategory__c = 'Sale',RICSC_AmountWithTaxEUR__c = 260000,RICSC_CurrencyKey__c = 'EUR',RICSC_TransactionDate__c = Date.newInstance(2016, 12, 9),RICSC_CountryOfOrigin__c = 'Monaco');
    insert testTransaction;

  }

  static testmethod void vCAGoldenRecord() {

    //Before the insertion of the transaction the golden record reference SA is from France
    //After the transaction insert The Reference SA is going to be from USA , because
    //we entered a transaction and this automaticaly makes it as top 1 SA and top 1 Boutique

    Account goldenRecordAcc = [SELECT id,RICSC_Top1SA__c,RICSC_Top1Boutique__c,RICSC_ReferenceBoutique__c,RICSC_FirstSalesDate__c,
                                RICSC_ReferenceSA__r.RICSC_CountryOfOrigin__c,RICSC_ReferenceSA__r.AccountId,RICSC_LastSalesDate__c,
                                RICSC_ReferenceSA__r.Account.RICSC_Localisation__r.RICSC_ParentLocalisation__r.Name,RICSC_HighJeweleryPieces__c,
                                RICSC_ReferenceSA__r.Account.RICSC_Localisation__r.RICSC_ParentLocalisation__r.RICSC_ParentLocalisation__r.Name,
                                RICSC_ReferenceMarket__c,RICSC_ReferenceRegion__c,RICSC_LastTransactionDate__c,RICSC_LastPurchaseBoutique__c,RICSC_TotalNumberOfRepairs__c
                                FROM Account WHERE RICSC_IsGoldenRecord__c = true AND RICSC_HasLocalRecords__c = true];

    //-------------------------THE FOLLOWING ARE FOR GOLDEN RECORD------------------------------//

    //after the transaction insertion the reference sa changed based on the top 1 obutique
    System.assertEquals('USA', goldenRecordAcc.RICSC_ReferenceSA__r.RICSC_CountryOfOrigin__c);

    //reference SA in golden record equals to the top 1 SA
    System.assertEquals(goldenRecordAcc.RICSC_ReferenceSA__c,goldenRecordAcc.RICSC_Top1SA__c);

    //Top 1 boutique equals to the highest turnover boutique of the transactions (it was empty before the transaction insert)
    System.assertNotEquals(null,goldenRecordAcc.RICSC_Top1Boutique__c);

    //reference Boutique in VCA is Equal to the boutique of the reference SA
    System.assertEquals(goldenRecordAcc.RICSC_ReferenceBoutique__c,goldenRecordAcc.RICSC_ReferenceSA__r.AccountId);

    //reference market is the market from the reference SA
    System.assertEquals(goldenRecordAcc.RICSC_ReferenceSA__r.Account.RICSC_Localisation__r.RICSC_ParentLocalisation__r.Name,goldenRecordAcc.RICSC_ReferenceMarket__c);

    //reference region is the region from the reference SA
    System.assertEquals(goldenRecordAcc.RICSC_ReferenceSA__r.Account.RICSC_Localisation__r.RICSC_ParentLocalisation__r.RICSC_ParentLocalisation__r.Name,goldenRecordAcc.RICSC_ReferenceRegion__c);

    //First Sales Date
    System.assertEquals(goldenRecordAcc.RICSC_FirstSalesDate__c,Date.newInstance(2016, 12, 9));

    //Last Sales Date
    System.assertEquals(goldenRecordAcc.RICSC_LastSalesDate__c,Date.newInstance(2016, 12, 9));

    //Last Transaction Date
    System.assertEquals(goldenRecordAcc.RICSC_LastTransactionDate__c,Date.newInstance(2016, 12, 9));

    //Last Purchase Boutique
    System.assertEquals([SELECT Id FROM Account WHERE Name = 'TransactionBoutique'].Id,goldenRecordAcc.RICSC_LastPurchaseBoutique__c);

    //Total Number Of Repairs
    System.assertEquals(0,goldenRecordAcc.RICSC_TotalNumberOfRepairs__c);

    //High Jewelery Pieces
    System.assertEquals(0,goldenRecordAcc.RICSC_HighJeweleryPieces__c);

  }

  static testmethod void vCALocalRecord() {

    //Before the insertion of the transaction the golden record reference SA is from France
    //After the transaction insert The Reference SA is going to be from USA , because
    //we entered a transaction and this automaticaly makes it as top 1 SA and top 1 Boutique

    Account localRecordAcc = [SELECT id,RICSC_Top1SA__c,RICSC_Top1Boutique__c,RICSC_ReferenceBoutique__c,RICSC_LastPurchaseBoutique__c,RICSC_LastSalesDate__c,
                              RICSC_ReferenceSA__r.RICSC_CountryOfOrigin__c,RICSC_ReferenceSA__r.AccountId,RICSC_LastTransactionDate__c,
                              RICSC_ReferenceSA__r.Account.RICSC_Localisation__r.RICSC_ParentLocalisation__r.Name,RICSC_FirstSalesDate__c,
                              RICSC_ReferenceSA__r.Account.RICSC_Localisation__r.RICSC_ParentLocalisation__r.RICSC_ParentLocalisation__r.Name,
                              RICSC_ReferenceMarket__c,RICSC_ReferenceRegion__c,RICSC_HighJeweleryPieces__c,RICSC_TotalNumberOfRepairs__c
                              FROM Account WHERE Name = 'VanCleefAndArpelsLocalReordAccount'];

    //-------------------------THE FOLLOWING ARE FOR LOCAL RECORD------------------------------//

    //after the transaction insertion the reference sa shouldnt changed based on the top 1 obutique
    System.assertNotEquals('USA', localRecordAcc.RICSC_ReferenceSA__r.RICSC_CountryOfOrigin__c);

    //reference SA in local record is not equal to the top 1 SA
    System.assertNotEquals(localRecordAcc.RICSC_ReferenceSA__c,localRecordAcc.RICSC_Top1SA__c);

    //Top 1 boutique doesnt get calculated on the local level
    System.assertEquals(null,localRecordAcc.RICSC_Top1Boutique__c);

    //reference Boutique isnt calculated on the local record
    System.assertEquals(null,localRecordAcc.RICSC_ReferenceBoutique__c);

    //reference market isnt calculated on the local record
    System.assertEquals(null,localRecordAcc.RICSC_ReferenceMarket__c);

    //reference region isnt calculated on the local record
    System.assertEquals(null,localRecordAcc.RICSC_ReferenceRegion__c);

    //First Sales Date - not calculated on local record
    System.assertEquals(null,localRecordAcc.RICSC_FirstSalesDate__c);

    //Last Sales Date
    System.assert(localRecordAcc.RICSC_LastSalesDate__c==null);

    //Last Transaction Date
    System.assertEquals(Date.newInstance(2016, 12, 9),localRecordAcc.RICSC_LastTransactionDate__c);

    //Last Purchase Boutique
    System.assertEquals([SELECT Id FROM Account WHERE Name = 'TransactionBoutique'].Id,localRecordAcc.RICSC_LastPurchaseBoutique__c);

    //Total Number Of Repairs - not calculated on local record
    System.assertEquals(null,localRecordAcc.RICSC_TotalNumberOfRepairs__c);

    //High Jewelery Pieces
    System.assertEquals(0,localRecordAcc.RICSC_HighJeweleryPieces__c);

  }

}