unpackaged/main/default/objects/Account/fields/RICSC_Email__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Email__c</fullName>
        <description>email field to capture the email of the Boutique</description>
        <label>Email</label>
        <type>Email</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_HasLocalRecords__c.field-meta.xml
<CustomField>
        <fullName>RICSC_HasLocalRecords__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Local Records</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_IsGoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_IsGoldenRecord__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Golden Record</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Address__c/RICSC_Address__c.object-meta.xml
<CustomObject>
    <description>This object is used to collect  the Addresses of the related Local records.</description>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Address__c/fields/RICSC_Address__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Address__c</fullName>
        <description>Field to capture the full address</description>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Address__c/fields/RICSC_GR__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to the golden record</description>
        <label>GR</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>RICSC_AddressesGR</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Address__c/fields/RICSC_GRMainAddress__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GRMainAddress__c</fullName>
        <defaultValue>false</defaultValue>
        <description>a flag indicating the main email address for the Golden record (based on the GR Lookup - not Account)</description>
        <label>GR Main Address</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Address__c/fields/RICSC_LRMainAddress__c.field-meta.xml
<CustomField>
        <fullName>RICSC_LRMainAddress__c</fullName>
        <defaultValue>false</defaultValue>
        <description>a flag indicating the main email address for the Local record (based on the Account Lookup - not GR)</description>
        <label>LR Main Address</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Email__c/RICSC_Email__c.object-meta.xml
<CustomObject>
    <description>This object is used to collect  the Emails of the related Local records.</description>
    <label>Email</label>
    <nameField>
        <displayFormat>E-{000000000}</displayFormat>
        <label>Email</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_DefaultEmail__c.field-meta.xml
<CustomField>
        <fullName>RICSC_DefaultEmail__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to identify which is the primary email. For the LR comes from the Source System in the GR is populated  based on rules</description>
        <label>Default Email</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_DefaultGREmail__c.field-meta.xml
<CustomField>
        <fullName>RICSC_DefaultGREmail__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default GR Email</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_Email__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Email__c</fullName>
        <description>Standard email type field</description>
        <label>Email</label>
        <length>80</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_GR__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This lookup field links the email to the golden record</description>
        <label>GR</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Emails</relationshipLabel>
        <relationshipName>RICSC_EmailsGR</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Phone__c/RICSC_Phone__c.object-meta.xml
<CustomObject>
    <description>This object is used to collect  the Phones of the related Local records.</description>
    <label>Phone</label>
    <nameField>
        <displayFormat>P-{000000000}</displayFormat>
        <label>Phone</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Phones</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Phone__c/fields/RICSC_DefaultGRPhone__c.field-meta.xml
<CustomField>
        <fullName>RICSC_DefaultGRPhone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default GR Phone</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Phone__c/fields/RICSC_DefaultPhone__c.field-meta.xml
<CustomField>
        <fullName>RICSC_DefaultPhone__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to identify which is the primary phone. For the LR comes from the Source System in the GR is populated  based on rules</description>
        <label>Default Phone</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Phone__c/fields/RICSC_GR__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to the golden record</description>
        <label>GR</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Phones</relationshipLabel>
        <relationshipName>RICSC_PhonesGR</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Phone__c/fields/RICSC_Phone__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Phone__c</fullName>
        <description>Standard phone field</description>
        <label>Phone</label>
        <type>Phone</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_SocialMediaID__c/RICSC_SocialMediaID__c.object-meta.xml
<CustomObject>
    <description>This object is used to collect  the Social ID of the related Local records.</description>
    <label>Social Media ID</label>
    <nameField>
        <displayFormat>S-{000000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Social Media IDs</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_SocialMediaID__c/fields/RICSC_DefaultGRSocialMediaID__c.field-meta.xml
<CustomField>
        <fullName>RICSC_DefaultGRSocialMediaID__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default GR Social Media ID</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_SocialMediaID__c/fields/RICSC_DefaultSocialMediaID__c.field-meta.xml
<CustomField>
        <fullName>RICSC_DefaultSocialMediaID__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Default Social Media ID , the last modified social media</description>
        <label>Default Social Media ID</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_SocialMediaID__c/fields/RICSC_GR__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to the golden record</description>
        <label>GR</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Social Media IDs</relationshipLabel>
        <relationshipName>RICSC_SocialMediaIDsGR</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/classes/BatchDefaultRecord.cls
/******************************************************************************
* @author       Silvan Sholla
* @date         12/11/2019
* @description  Checks the default Records based on the last modified one
*               for each account
******************************************************************************/

global class BatchDefaultRecord implements
  Database.Batchable<sObject>, Schedulable {
  private Set<String> recordTypeSet = UtilityConstants.PERSON_ACCOUNT_RT_SET_ID;
  private Boolean skipTriggersOnAccRelObjs;
  private String query = 'SELECT Id,RICSC_HasLocalRecords__c,RICSC_IsGoldenRecord__c FROM Account WHERE RICSC_IsGoldenRecord__c = true AND RecordTypeId IN: recordTypeSet';
  public static final Integer MAX_SCOPE = 100;

  public BatchDefaultRecord(Boolean skipParam, String queryStr) {
    skipTriggersOnAccRelObjs = skipParam;
    this.query = queryStr == null ? this.query : queryStr;
  }

  public void execute(SchedulableContext sc) {
    BatchDefaultRecord b = new BatchDefaultRecord(false, null);
    Database.executeBatch(b, MAX_SCOPE);
  }

  global Database.QueryLocator start(Database.BatchableContext bc) {
    return Database.getQueryLocator(query);
  }
  global void execute(Database.BatchableContext bc, List<Account> scope)  {
    try {
      Set<Id> involvedAccs = new Set<Id>();
      List<SObject> objectsToUpdate = new List<SObject>();
      for (Account acc : (List<Account>)scope){
        involvedAccs.add(acc.Id);
      }

      if(involvedAccs.size()>0){
        CalculatingFieldsHandler.setDefaultRecordForObject('RICSC_Email__c','RICSC_EmailsGR__r',involvedAccs,'RICSC_DefaultEmail__c','RICSC_DefaultGREmail__c');
        CalculatingFieldsHandler.setDefaultRecordForObject('RICSC_Address__c','RICSC_AddressesGR__r',involvedAccs,'RICSC_LRMainAddress__c','RICSC_GRMainAddress__c');
        CalculatingFieldsHandler.setDefaultRecordForObject('RICSC_Phone__c','RICSC_PhonesGR__r',involvedAccs,'RICSC_DefaultPhone__c','RICSC_DefaultGRPhone__c');
        CalculatingFieldsHandler.setDefaultRecordForObject('RICSC_SocialMediaID__c','RICSC_SocialMediaIDsGR__r',involvedAccs,'RICSC_DefaultSocialMediaID__c','RICSC_DefaultGRSocialMediaID__c');
      }
    } catch(Exception e) {
      UtilityLogger.logException(e,e.getMessage(),'BatchDefaultRecord','execute');
    }
  }
  global void finish(Database.BatchableContext bc){

  }
}