unpackaged/main/default/objects/Account/fields/RICSC_ClientFlag__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ClientFlag__c</fullName>
        <description>Client categorization based on perceived value (what level of VIP)</description>
        <label>Client Flag</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Top VIP</fullName>
                </value>
                <value>
                    <fullName>VIP</fullName>
                </value>
                <value>
                    <fullName>Potential VIP</fullName>
                </value>
                <value>
                    <fullName>GOAL – Top</fullName>
                </value>
                <value>
                    <fullName>GOAL – Local</fullName>
                </value>
                <value>
                    <fullName>GOAL – Potential</fullName>
                </value>
                <value>
                    <fullName>GOAL+ – Existing HE</fullName>
                </value>
                <value>
                    <fullName>GOAL+ – Non-HE client</fullName>
                </value>
                <value>
                    <fullName>GOAL+ – Prospect</fullName>
                </value>
                <value>
                    <fullName>Loyal</fullName>
                </value>
                <value>
                    <fullName>Potential</fullName>
                </value>
                <value>
                    <fullName>SAV</fullName>
                </value>
                <value>
                    <fullName>Richemont Board of Directors</fullName>
                </value>
                <value>
                    <fullName>Family-Richemont Board of Directors</fullName>
                </value>
                <value>
                    <fullName>VIP1</fullName>
                    <isActive>false</isActive>
                    <label>VIP1</label>
                </value>
                <value>
                    <fullName>VIP2</fullName>
                    <isActive>false</isActive>
                    <label>VIP2</label>
                </value>
                <value>
                    <fullName>VIP5</fullName>
                    <isActive>false</isActive>
                    <label>VIP5</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_GlobalSegment__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GlobalSegment__c</fullName>
        <description>Calculated segmentation based on rules taking into account the local transactions</description>
        <label>Global Segment</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Golden Record</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RICSC_IsGoldenRecord__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.RICSC_NotToBeGrouped__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Accounts (Local Records)</relationshipLabel>
        <relationshipName>RICSC_AccountGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_Turnover__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Turnover__c</fullName>
        <description>Calculated field with sum of all customer purchases</description>
        <label>Turnover</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_VIP__c.field-meta.xml
<CustomField>
        <fullName>RICSC_VIP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Client categorization based on perceived value</description>
        <label>VIP</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Asset/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to a Golden Record which has been created for the Account - Release 1 SC</description>
        <label>Golden Record</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Product Portfolios</relationshipLabel>
        <relationshipName>RICSC_AssetsGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Asset/fields/RICSC_VIP__c.field-meta.xml
<CustomField>
        <fullName>RICSC_VIP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It identifies if the Record is VIP or not . It is recalculated at the GR record level based on Maisons' rules</description>
        <label>VIP</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Case/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to a Golden Record which has been created for the Account</description>
        <label>Golden Record</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>RICSC_TicketsGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Case/fields/RICSC_VIP__c.field-meta.xml
<CustomField>
        <fullName>RICSC_VIP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It identifies if the Record is VIP or not . It is recalculated at the GR record level based on Maisons' rules</description>
        <label>VIP</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Activity__c/RICSC_Activity__c.object-meta.xml
<CustomObject>
    <description>Activity object is used to collect the interaction between Sales assistant and the customers.</description>
    <label>Activity</label>
    <nameField>
        <label>Activity Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RICSC_Activity__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Direct lookup to an account  from  which the activity originated - Release 1 SC</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>RICSC_ActivitiesAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Activity__c/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to a Golden Record which has been created for the Account - Release 1 SC</description>
        <label>Golden Record</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>RICSC_ActivitiesGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Address__c/RICSC_Address__c.object-meta.xml
<CustomObject>
    <description>This object is used to collect  the Addresses of the related Local records.</description>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Address__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to Account (Contact)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>RICSC_AddressesAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Email__c/RICSC_Email__c.object-meta.xml
<CustomObject>
    <description>This object is used to collect  the Emails of the related Local records.</description>
    <label>Email</label>
    <nameField>
        <displayFormat>E-{000000000}</displayFormat>
        <label>Email</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to the Account (contact)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Emails</relationshipLabel>
        <relationshipName>RICSC_EmailsAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_VIP__c.field-meta.xml
<CustomField>
        <fullName>RICSC_VIP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It identifies if the Record is VIP or not . It is recalculated at the GR record level based on Maisons' rules</description>
        <label>VIP</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Phone__c/RICSC_Phone__c.object-meta.xml
<CustomObject>
    <description>This object is used to collect  the Phones of the related Local records.</description>
    <label>Phone</label>
    <nameField>
        <displayFormat>P-{000000000}</displayFormat>
        <label>Phone</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Phones</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Phone__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to Account (Contact)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Phones</relationshipLabel>
        <relationshipName>RICSC_PhonesAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Relation__c/RICSC_Relation__c.object-meta.xml
<CustomObject>
    <description>Relation object is used to track the relations between 2 Customers (e.g. father, husband etc)</description>
    <label>Relationship</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Relationship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RICSC_Relation__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to to link the related Person account (the one that has the role in the relation type)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationship</relationshipLabel>
        <relationshipName>RICSC_RelationsAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Relation__c/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to to link the related Golden Record (the one that has the role in the relation type)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationship</relationshipLabel>
        <relationshipName>RICSC_RelationsGR</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/RICSC_Transaction__c.object-meta.xml
<CustomObject>
    <description>capture transaction information.</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{000000000}</displayFormat>
        <label>Transaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to a Golden Record which has been created for the Account - Release 1 SC</description>
        <label>Golden Record</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>RICSC_TransactionsGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_VIP__c.field-meta.xml
<CustomField>
        <fullName>RICSC_VIP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It identifies if the Record is VIP or not . It is recalculated at the GR record level based on Maisons' rules</description>
        <label>VIP</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Wishlist__c/RICSC_Wishlist__c.object-meta.xml
<CustomObject>
    <label>Wishlist</label>
    <nameField>
        <displayFormat>Wishlist-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wishlists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RICSC_Wishlist__c/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to a Golden Record which has been created for the Account - Release 1 SC</description>
        <label>Golden Record</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Wishlists</relationshipLabel>
        <relationshipName>RICSC_WishlistsGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/classes/BatchPopulateGoldenRecordLookup.cls
public class BatchPopulateGoldenRecordLookup implements Database.Batchable<SObject>, Schedulable {

    public Integer MAXSCOPE = 100;
    private Set<String> recordTypeSet = UtilityConstants.PERSON_ACCOUNT_RT_SET_ID;
    public String query = 'SELECT Id, RecordTypeId, RICSC_GoldenRecord__c, RICSC_Turnover__c, RICSC_ClientFlag__c, RICSC_GlobalSegment__c, RICSC_Vip__c FROM Account';
    public Boolean skipTriggers = false;

    public Iterable<SObject> start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    public BatchPopulateGoldenRecordLookup(Boolean skipParam, String queryStr) {
        this.query = queryStr == null ? this.query : queryStr;
        skipTriggers = skipParam;
    }

    public void execute(SchedulableContext sc) {
        BatchPopulateGoldenRecordLookup b = new BatchPopulateGoldenRecordLookup(false,null);
        Database.executeBatch(b, MAXSCOPE);
    }

    public void execute(Database.BatchableContext bc, List<Account> scope) {
      try{
        Map<Id,Account> scopeMap = new Map<Id,Account>(scope);
        List<Account> accountWithObjects= [SELECT Id, (SELECT id,RICSC_GoldenRecord__c,RICSC_Account__c FROM RICSC_ActivitiesAccount__r),
                                              (SELECT RICSC_GR__c, RICSC_Account__c FROM RICSC_EmailsAccount__r),
                                              (SELECT RICSC_GR__c, RICSC_Account__c FROM RICSC_SocialMediaIDsAccount__r),
                                              (SELECT RICSC_GR__c, RICSC_Account__c FROM RICSC_AddressesAccount__r),
                                              (SELECT RICSC_GR__c, RICSC_Account__c FROM RICSC_PhonesAccount__r),
                                              (SELECT RICSC_GoldenRecord__c, RICSC_Account__c FROM RICSC_TransactionsAccount__r),
                                              (SELECT RICSC_GoldenRecord__c, AccountId FROM Assets),
                                              (SELECT RICSC_GoldenRecord__c, RICSC_Account__c FROM RICSC_WishlistsAccount__r),
                                              (SELECT RICSC_GoldenRecord__c, RICSC_Account__c FROM RICSC_RelationsAccount__r),
                                              (SELECT RICSC_GoldenRecord__c, AccountId FROM Cases)
                                              FROM Account where Id in :scopeMap.keySet()];
        List<RICSC_Activity__c> activities = new List<RICSC_Activity__c>();
        List<RICSC_Address__c> addresses = new List<RICSC_Address__c>();
        List<RICSC_Email__c> emails = new List<RICSC_Email__c>();
        List<RICSC_Phone__c> phones = new List<RICSC_Phone__c>();
        List<Asset> assets = new List<Asset>();
        List<RICSC_Relation__c> relations = new List<RICSC_Relation__c>();
        List<RICSC_SocialMediaID__c> socialMediaIDs = new List<RICSC_SocialMediaID__c>();
        List<RICSC_Transaction__c> transactions = new List<RICSC_Transaction__c>();
        List<RICSC_Wishlist__c> wishlists = new List<RICSC_Wishlist__c>();
        List<Case> cases = new List<Case>();
        for(Account acc : accountWithObjects){
          activities.addAll(acc.RICSC_ActivitiesAccount__r);
          addresses.addall(acc.RICSC_AddressesAccount__r);
          emails.addall(acc.RICSC_EmailsAccount__r);
          phones.addall(acc.RICSC_PhonesAccount__r);
          assets.addall(acc.Assets);
          relations.addall(acc.RICSC_RelationsAccount__r);
          socialMediaIDs.addall(acc.RICSC_SocialMediaIDsAccount__r);
          transactions.addall(acc.RICSC_TransactionsAccount__r);
          wishlists.addall(acc.RICSC_WishlistsAccount__r);
          cases.addAll(acc.Cases);
        }
        UtilityAccount.goldenRecordLookUpPopulate('RICSC_ActivitiesAccount__r','RICSC_Account__c','RICSC_GoldenRecord__c','ActivityTriggerHandler',activities);
        UtilityAccount.goldenRecordLookUpPopulate('RICSC_AddressesAccount__r','RICSC_Account__c','RICSC_GR__c','AddressTriggerHandler',addresses);
        UtilityAccount.goldenRecordLookUpPopulate('RICSC_EmailsAccount__r','RICSC_Account__c','RICSC_GR__c','EmailTriggerHandler',emails);
        UtilityAccount.goldenRecordLookUpPopulate('RICSC_PhonesAccount__r','RICSC_Account__c','RICSC_GR__c','PhoneTriggerHandler',phones);
        UtilityAccount.goldenRecordLookUpPopulate('Assets','AccountId','RICSC_GoldenRecord__c','ProductPortfolioTriggerHandler',assets);
        UtilityAccount.goldenRecordLookUpPopulate('RICSC_RelationsAccount__r','RICSC_Account__c','RICSC_GoldenRecord__c','RelationTriggerHandler',relations);
        UtilityAccount.goldenRecordLookUpPopulate('RICSC_SocialMediaIDsAccount__r','RICSC_Account__c','RICSC_GR__c','SocialMediaIDTriggerHandler',socialMediaIDs);
        UtilityAccount.goldenRecordLookUpPopulate('Cases','AccountId','RICSC_GoldenRecord__c','TicketTriggerHandler', cases);
        UtilityAccount.goldenRecordLookUpPopulate('RICSC_TransactionsAccount__r','RICSC_Account__c','RICSC_GoldenRecord__c','TransactionTriggerHandler',transactions);
        UtilityAccount.goldenRecordLookUpPopulate('RICSC_WishlistsAccount__r','RICSC_Account__c','RICSC_GoldenRecord__c','WishlistTriggerHandler',wishlists);
        List<SObject> objects = new List<SObject>();
        objects.addAll(activities);
        objects.addAll(addresses);
        objects.addAll(emails);
        objects.addAll(phones);
        objects.addAll(assets);
        objects.addAll(relations);
        objects.addAll(socialMediaIDs);
        objects.addAll(cases);
        objects.addAll(transactions);
        objects.addAll(wishlists);
        if(skipTriggers){
          TRG_TriggerDispatcher.skipTriggerMap.put('RICSC_Activity__c',true);
          TRG_TriggerDispatcher.skipTriggerMap.put('RICSC_Address__c',true);
          TRG_TriggerDispatcher.skipTriggerMap.put('RICSC_Email__c',true);
          TRG_TriggerDispatcher.skipTriggerMap.put('RICSC_Phone__c',true);
          TRG_TriggerDispatcher.skipTriggerMap.put('Asset',true);
          TRG_TriggerDispatcher.skipTriggerMap.put('RICSC_Relation__c',true);
          TRG_TriggerDispatcher.skipTriggerMap.put('RICSC_SocialMediaID__c',true);
          TRG_TriggerDispatcher.skipTriggerMap.put('RICSC_Transaction__c',true);
          TRG_TriggerDispatcher.skipTriggerMap.put('RICSC_Wishlist__c',true);
          TRG_TriggerDispatcher.skipTriggerMap.put('Case',true);
        }
        Database.SaveResult[] srList = Database.update(objects);
        UtilityLogger.logAllErrors(srList, false, 'BatchPopulateGoldenRecordLookup','execute');
        if(skipTriggers){
          TRG_TriggerDispatcher.skipTriggerMap.put('RICSC_Activity__c',false);
          TRG_TriggerDispatcher.skipTriggerMap.put('RICSC_Address__c',false);
          TRG_TriggerDispatcher.skipTriggerMap.put('RICSC_Email__c',false);
          TRG_TriggerDispatcher.skipTriggerMap.put('RICSC_Phone__c',false);
          TRG_TriggerDispatcher.skipTriggerMap.put('Asset',false);
          TRG_TriggerDispatcher.skipTriggerMap.put('RICSC_Relation__c',false);
          TRG_TriggerDispatcher.skipTriggerMap.put('RICSC_SocialMediaID__c',false);
          TRG_TriggerDispatcher.skipTriggerMap.put('RICSC_Transaction__c',false);
          TRG_TriggerDispatcher.skipTriggerMap.put('RICSC_Wishlist__c',false);
          TRG_TriggerDispatcher.skipTriggerMap.put('Case',false);
        }

      } catch(Exception e) {
        UtilityLogger.logException(e,e.getMessage(),'BatchPopulateGoldenRecordLookup','execute');
      }
    }

    public void finish(Database.BatchableContext bc) {
    }
}