unpackaged/main/default/objects/Account/fields/RICSC_GR__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GR__c</fullName>
        <description>Formula field showing golden record icon if a the record is a golden one</description>
        <formula>if( RICSC_IsGoldenRecord__c , IMAGE('/resource/GRIcon?','Image not found', 25,25),'' )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GR</label>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_ResidentNonResident__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ResidentNonResident__c</fullName>
        <description>Calculated segmentation based on the travel habits of a client</description>
        <label>Resident/Non Resident</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Non-Resident</fullName>
                </value>
                <value>
                    <fullName>Resident</fullName>
                </value>
                <value>
                    <fullName>Traveller</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Address__c/RICSC_Address__c.object-meta.xml
<CustomObject>
    <description>This object is used to collect  the Addresses of the related Local records.</description>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Address__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to Account (Contact)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>RICSC_AddressesAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Address__c/fields/RICSC_Address__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Address__c</fullName>
        <description>Field to capture the full address</description>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Address__c/fields/RICSC_AddressType__c.field-meta.xml
<CustomField>
        <fullName>RICSC_AddressType__c</fullName>
        <description>Picklist to capture the type of address</description>
        <label>Address Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Boutique</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Home Address</fullName>
                </value>
                <value>
                    <fullName>Office Address</fullName>
                </value>
                <value>
                    <fullName>Old Address</fullName>
                </value>
                <value>
                    <fullName>Past</fullName>
                </value>
                <value>
                    <fullName>Residency</fullName>
                </value>
                <value>
                    <fullName>Secondary Residence</fullName>
                </value>
                <value>
                    <fullName>Shipping Address</fullName>
                </value>
                <value>
                    <fullName>Summer Home</fullName>
                </value>
                <value>
                    <fullName>Temporary / Hotel</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>Web</fullName>
                </value>
                <value>
                    <fullName>Web Unknown</fullName>
                </value>
                <value>
                    <fullName>Winter Home</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Address__c/fields/RICSC_Country__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Country__c</fullName>
        <description>Picklist to capture the country of the address</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Address__c/fields/RICSC_GR__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to the golden record</description>
        <label>GR</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>RICSC_AddressesGR</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Address__c/fields/RICSC_GRMainAddress__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GRMainAddress__c</fullName>
        <defaultValue>false</defaultValue>
        <description>a flag indicating the main email address for the Golden record (based on the GR Lookup - not Account)</description>
        <label>GR Main Address</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Address__c/fields/RICSC_LRMainAddress__c.field-meta.xml
<CustomField>
        <fullName>RICSC_LRMainAddress__c</fullName>
        <defaultValue>false</defaultValue>
        <description>a flag indicating the main email address for the Local record (based on the Account Lookup - not GR)</description>
        <label>LR Main Address</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/globalValueSets/RICSC_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Amer.Virgin Is.</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua/Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia-Herz.</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Islands</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/AddressTriggerHandler.cls
/******************************************************************************
@author Silvan Sholla
@date 25/Nov/2019
@description This is a container of all trigger classes on Address object used within the trigger framework.
******************************************************************************/

public with sharing class AddressTriggerHandler {

  public without sharing class VCARecordSharing implements TRG_TriggerHandlerInterface {
      public void runTriggerHandler(TRG_TriggerDispatcher.TriggerData td) {

        Set<Id> accountIds = new Set<Id>();
        for(RICSC_Address__c email : (List<RICSC_Address__c>) td.newList){
          if(email.RICSC_Account__c != null){
            accountIds.add(email.RICSC_Account__c);
          }
          if(email.RICSC_GR__c != null){
            accountIds.add(email.RICSC_GR__c);
          }
        }

        if(td.isInsert){
          SharingRuleTriggerHelper.AfterInsert(td.newList,accountIds,'RICSC_Address__share');
        }
        if(td.isUpdate){
          SharingRuleTriggerHelper.AfterUpdate(td.newList,td.oldMap,accountIds,'RICSC_Address__share');
        }
      }
  }

  /******************************************************************************
  * @author       Silvan Sholla/Piergiorgio Lisanti
  * @date         15/Oct/2019
  * @description  This class contains trigger logic fired after addresses are inserted/modified/deleted.
  *               It computes RICSC_ResidentNonResident__c calculated field on Account records based on related transactions and addresses records.
  *               - Resident --> all transactions in the residency address
  *               - Non-Resident --> no transactions in the residency address
  *               - Traveller --> only part of transactions in the residency address
  ******************************************************************************/
  public without sharing class ResidencyFieldsOnAccount implements TRG_TriggerHandlerInterface {
    public void runTriggerHandler(TRG_TriggerDispatcher.TriggerData td) {

      Set<Id> accIds = new Set<Id>();
      Set<Id> accIdsGR = new Set<Id>();
      List<RICSC_Address__c> involvedAddresses = new List<RICSC_Address__c>();
      involvedAddresses = td.isDelete ? (List<RICSC_Address__c>) td.oldList : (List<RICSC_Address__c>) td.newList;
      for(RICSC_Address__c addr : involvedAddresses){
        if(td.isInsert){
          if(addr.RICSC_Country__c != null && addr.RICSC_AddressType__c == 'Residency'){
            if(addr.RICSC_Account__c != null){
              accIds.add(addr.RICSC_Account__c);
            }
            if(addr.RICSC_GR__c != null){
              accIdsGR.add(addr.RICSC_GR__c);
            }
          }
        } else if(td.isUpdate){
          if((addr.RICSC_Country__c != td.oldMap.get(addr.Id).get('RICSC_Country__c') ||
            addr.RICSC_Account__c != td.oldMap.get(addr.Id).get('RICSC_Account__c') ||
            addr.RICSC_AddressType__c != td.oldMap.get(addr.Id).get('RICSC_AddressType__c')) && addr.RICSC_Account__c != null){
              accIds.add(addr.RICSC_Account__c);
              if(addr.RICSC_Account__c != td.oldMap.get(addr.Id).get('RICSC_Account__c') && td.oldMap.get(addr.Id).get('RICSC_Account__c')!=null){
                accIds.add((Id)td.oldMap.get(addr.Id).get('RICSC_Account__c'));
              }
          }
          if((addr.RICSC_Country__c != td.oldMap.get(addr.Id).get('RICSC_Country__c') ||
            addr.RICSC_GR__c != td.oldMap.get(addr.Id).get('RICSC_GR__c') ||
            addr.RICSC_AddressType__c != td.oldMap.get(addr.Id).get('RICSC_AddressType__c')) && addr.RICSC_GR__c != null){

              accIdsGR.add(addr.RICSC_GR__c);
              if(addr.RICSC_GR__c != td.oldMap.get(addr.Id).get('RICSC_GR__c') && td.oldMap.get(addr.Id).get('RICSC_GR__c')!=null){
                accIds.add((Id) td.oldMap.get(addr.Id).get('RICSC_GR__c'));
              }
          }
        }else if(td.isDelete){
            if(addr.RICSC_Account__c != null && addr.RICSC_Country__c != null && addr.RICSC_AddressType__c == 'Residency'){
              accIds.add(addr.RICSC_Account__c);
            }
            if(addr.RICSC_GR__c != null && addr.RICSC_Country__c != null && addr.RICSC_AddressType__c == 'Residency'){
              accIdsGR.add(addr.RICSC_GR__c);
            }
        }
      }

      if(accIds.size()>0){
        TRG_TriggerDispatcher.skipTriggerMap.put('Account',true);
        update CalculatingFieldsHandler.computeResidenceNonResidence(accIds,'RICSC_Account__c',true);
        TRG_TriggerDispatcher.skipTriggerMap.put('Account',false);
      }
      if(accIdsGR.size()>0){
        TRG_TriggerDispatcher.skipTriggerMap.put('Account',true);
        update CalculatingFieldsHandler.computeResidenceNonResidence(accIdsGR,'RICSC_GR__c',true);
        TRG_TriggerDispatcher.skipTriggerMap.put('Account',false);
      }
    }
  }

  public without sharing class DefaultAddressCheck implements TRG_TriggerHandlerInterface {
    public void runTriggerHandler(TRG_TriggerDispatcher.TriggerData td) {
      Set<Id> involvedAccs = new Set<Id>();

      if(td.isInsert){
        for(SObject currentRecord : (List<SObject>) td.newList){
          if(currentRecord.get('RICSC_GR__c') != null){
            involvedAccs.add(currentRecord.get('RICSC_GR__c').toString());
          }
        }
      }else if(td.isUpdate){
        for(SObject currentRecord : (List<SObject>) td.newList){
          if(currentRecord.get('RICSC_GR__c') != null){
            involvedAccs.add(currentRecord.get('RICSC_GR__c').toString());
          }
        }
      }
      if(involvedAccs.size()>0){
        if(!Utility.isAsync()){
          System.enqueueJob(new QueueableClasses.DefaultRecordCalculationForRelatedObjects('RICSC_Address__c','RICSC_AddressesGR__r',involvedAccs,'RICSC_LRMainAddress__c','RICSC_GRMainAddress__c'));
        }else{
          CalculatingFieldsHandler.setDefaultRecordForObject('RICSC_Address__c','RICSC_AddressesGR__r',involvedAccs,'RICSC_LRMainAddress__c','RICSC_GRMainAddress__c');
        }
      }
    }
  }

  /******************************************************************************
  @author Silvan Sholla
  @date 25/Nov/2019
  @description propagate golden record lookup of address based the accounts
               golden record : in case its populated on the account , then
               the golden record is filled with accounts golden record otherwise
               its getting filled with the local account id
  ******************************************************************************/
  public without sharing class GoldenRecordLookUpPopulate implements TRG_TriggerHandlerInterface {
    public void runTriggerHandler(TRG_TriggerDispatcher.TriggerData td) {
      UtilityAccount.goldenRecordLookUpPopulate('RICSC_AddressesAccount__r','RICSC_Account__c','RICSC_GR__c','AddressTriggerHandler',td.newList);
    }
  }
}