unpackaged/main/default/objects/Account/fields/RICSC_CountryOfOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryOfOrigin__c</fullName>
        <description>Country where the record has been created. Used for the sharing rules (e.g. records created outside of China shouldn't be visible for the Chineese users) - Release 1 SC</description>
        <label>Account Country Of Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_ExtCreationDate__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ExtCreationDate__c</fullName>
        <description>Date and Time of the record creation in the source system</description>
        <label>Ext Creation Date</label>
        <type>Date</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Golden Record</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RICSC_IsGoldenRecord__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.RICSC_NotToBeGrouped__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Accounts (Local Records)</relationshipLabel>
        <relationshipName>RICSC_AccountGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_Maison__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Maison__c</fullName>
        <description>List of Maisons</description>
        <label>Account Maison</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Maison</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Asset/fields/RICSC_AmountWithTax__c.field-meta.xml
<CustomField>
        <fullName>RICSC_AmountWithTax__c</fullName>
        <description>Total amount of the transaction coming from the source system</description>
        <label>Amount With Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </CustomField>

unpackaged/main/default/objects/Asset/fields/RICSC_CountryOfOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryOfOrigin__c</fullName>
        <description>Country where the record has been created. Used for the sharing rules (e.g. records created outside of China shouldn't be visible for the Chineese users) - Release 1 SC</description>
        <label>Country Of Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Asset/fields/RICSC_ExtCreationDate__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ExtCreationDate__c</fullName>
        <description>Date and Time of the record creation in the source system</description>
        <label>Ext Creation Date</label>
        <type>Date</type>
    </CustomField>

unpackaged/main/default/objects/Asset/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to a Golden Record which has been created for the Account - Release 1 SC</description>
        <label>Golden Record</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Product Portfolios</relationshipLabel>
        <relationshipName>RICSC_AssetsGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Asset/fields/RICSC_Maison__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Maison__c</fullName>
        <description>List of Maisons</description>
        <label>Maison</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Maison</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Asset/fields/RICSC_ProductsReturned__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ProductsReturned__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Technical field to hide returned products</description>
        <label>Products Returned</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Asset/fields/RICSC_TransactionNumber__c.field-meta.xml
<CustomField>
        <fullName>RICSC_TransactionNumber__c</fullName>
        <description>Transaction Number in external system</description>
        <label>Transaction Number</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Product2/fields/RICSC_ExtCreationDate__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ExtCreationDate__c</fullName>
        <description>Date and Time of the record creation in the source system</description>
        <label>External Creation Date</label>
        <type>Date</type>
    </CustomField>

unpackaged/main/default/objects/Product2/fields/RICSC_Maison__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Maison__c</fullName>
        <description>Maison in which the product exist</description>
        <label>Maison</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Maison</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Product2/fields/RICSC_SerialNumber__c.field-meta.xml
<CustomField>
        <fullName>RICSC_SerialNumber__c</fullName>
        <label>Serial Number</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/RICSC_Transaction__c.object-meta.xml
<CustomObject>
    <description>capture transaction information.</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{000000000}</displayFormat>
        <label>Transaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to an Account - Release 1 SC</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>RICSC_TransactionsAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_AmountWithTax__c.field-meta.xml
<CustomField>
        <fullName>RICSC_AmountWithTax__c</fullName>
        <description>Total amount of the transaction coming from the source system</description>
        <label>Amount With Tax</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_Channel__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Channel__c</fullName>
        <description>Field to categorize the channel through which the transaction was handled</description>
        <label>Transaction Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Boutique</fullName>
                </value>
                <value>
                    <fullName>CC</fullName>
                </value>
                <value>
                    <fullName>Charity</fullName>
                </value>
                <value>
                    <fullName>Web</fullName>
                </value>
                <value>
                    <fullName>Wholesaler</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_CountryOfOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryOfOrigin__c</fullName>
        <description>Country where the record has been created. Used for the sharing rules (e.g. records created outside of China shouldn't be visible for the Chineese users) - Release 1 SC</description>
        <label>Country Of Transaction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_CurrencyKey__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CurrencyKey__c</fullName>
        <description>Currency keycoming from the source system</description>
        <label>Currency Key</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Currency</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to a Golden Record which has been created for the Account - Release 1 SC</description>
        <label>Golden Record</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>RICSC_TransactionsGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_Maison__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Maison__c</fullName>
        <description>List of Maisons</description>
        <label>Maison</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Maison</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_ProductName__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ProductName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the Product</description>
        <label>Product Name</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Names</relationshipLabel>
        <relationshipName>RICSC_ProductNames</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_SerialNumber__c.field-meta.xml
<CustomField>
        <fullName>RICSC_SerialNumber__c</fullName>
        <description>Serial Number of the product in the transaction</description>
        <label>Serial Number</label>
        <length>50</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_TransactionCategory__c.field-meta.xml
<CustomField>
        <fullName>RICSC_TransactionCategory__c</fullName>
        <description>Field to categorize a transaction of a certain type as Repair, Return, Sale</description>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Repair</fullName>
                </value>
                <value>
                    <fullName>Return</fullName>
                </value>
                <value>
                    <fullName>Sale</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_TransactionNumber__c.field-meta.xml
<CustomField>
        <fullName>RICSC_TransactionNumber__c</fullName>
        <description>Transaction Number in external system</description>
        <label>Transaction Number</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/globalValueSets/RICSC_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Amer.Virgin Is.</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua/Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia-Herz.</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Islands</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/RICSC_Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AWG</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BOV</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BTN</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYR</fullName>
    </customValue>
    <customValue>
        <fullName>BZD</fullName>
    </customValue>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <customValue>
        <fullName>CDF</fullName>
    </customValue>
    <customValue>
        <fullName>CHE</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <description>Unit of measurecoming</description>
    <masterLabel>Currency</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/RICSC_Maison.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cartier</fullName>
    </customValue>
    <customValue>
        <fullName>Jaeger Le Coultre</fullName>
    </customValue>
    <customValue>
        <fullName>Van Cleef &amp; Arpels</fullName>
    </customValue>
    <masterLabel>Maison</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/BatchProductPortfolioIntegration_Test.cls
@isTest
private class BatchProductPortfolioIntegration_Test {
    @testSetup
    static void setup() {

      TRG_TriggerDispatcher.skipTriggerMap.put('TransactionTriggerHandler.ProductPortfolioIntegrationTRG',true);
      UtilityTests.testSetup();

      List<RICSC_Transaction__c> transactions = new List<RICSC_Transaction__c>();
      List<Asset> assets = new List<Asset>();

      Account transactionOwner = UtilityTests.getPersonAccount();
      transactionOwner.LastName = 'AccountTransactionOwner';
      insert transactionOwner;

      Account transactionOwnerThatDoesntHaveAnyAsset = UtilityTests.getPersonAccount();
      transactionOwnerThatDoesntHaveAnyAsset.LastName = 'transactionOwnerThatDoesntHaveAnyAsset';
      insert transactionOwnerThatDoesntHaveAnyAsset;

      Product2 pr = new Product2(Name = 'testProduct');
      insert pr;

      RICSC_Transaction__c trc = UtilityTests.getTransaction();
      trc.RICSC_CountryOfOrigin__c = 'France';
      trc.RICSc_Account__c = transactionOwner.Id;
      trc.RICSC_Maison__c = 'Cartier';
      trc.RICSC_Channel__c = 'Boutique';
      trc.RICSC_CurrencyKey__c = 'EUR';
      trc.RICSC_SerialNumber__c = '123456';
      trc.RICSC_TransactionNumber__c = 'EXISTINGASSET';
      trc.RICSC_AmountWithTax__c = 250.0;
      trc.RICSC_Channel__c = 'Boutique';
      trc.RICSC_TransactionCategory__c = 'Sale';
      trc.RICSC_ExtCreationDate__c = Date.newInstance(2018, 12, 9);
      transactions.add(trc);

      RICSC_Transaction__c trc2 = UtilityTests.getTransaction();
      trc2.RICSC_CountryOfOrigin__c = 'France';
      trc2.RICSc_Account__c = transactionOwner.Id;
      trc2.RICSC_Maison__c = 'Cartier';
      trc2.RICSC_Channel__c = 'Boutique';
      trc2.RICSC_CurrencyKey__c = 'EUR';
      trc2.RICSC_SerialNumber__c = '123457';
      trc2.RICSC_TransactionCategory__c = 'Sale';
      trc2.RICSC_ProductName__c = pr.id;
      trc2.RICSC_TransactionNumber__c = 'NEGATIVEAMOUNT';
      trc2.RICSC_AmountWithTax__c = -250.0;
      trc2.RICSC_ExtCreationDate__c = Date.newInstance(2018, 12, 9);
      transactions.add(trc2);

      RICSC_Transaction__c trc3 = UtilityTests.getTransaction();
      trc3.RICSC_CountryOfOrigin__c = 'France';
      trc3.RICSc_Account__c = transactionOwner.Id;
      trc3.RICSC_Maison__c = 'Cartier';
      trc3.RICSC_Channel__c = 'Boutique';
      trc3.RICSC_CurrencyKey__c = 'EUR';
      trc3.RICSC_SerialNumber__c = '01010';
      trc3.RICSC_ProductName__c = pr.id;
      trc3.RICSC_TransactionNumber__c = '1111';
      trc3.RICSC_TransactionCategory__c = 'Sale';
      trc3.RICSC_AmountWithTax__c = -250.0;
      trc3.RICSC_ExtCreationDate__c = Date.newInstance(2018, 12, 9);
      transactions.add(trc3);

      RICSC_Transaction__c trc4 = UtilityTests.getTransaction();
      trc4.RICSC_CountryOfOrigin__c = 'France';
      trc4.RICSc_Account__c = transactionOwnerThatDoesntHaveAnyAsset.Id;
      trc4.RICSC_Maison__c = 'Cartier';
      trc4.RICSC_Channel__c = 'Boutique';
      trc4.RICSC_CurrencyKey__c = 'EUR';
      trc4.RICSC_TransactionCategory__c = 'Sale';
      trc4.RICSC_SerialNumber__c = '2222';
      trc4.RICSC_ProductName__c = pr.id;
      trc4.RICSC_TransactionNumber__c = '1111';
      trc4.RICSC_AmountWithTax__c = -250.0;
      trc4.RICSC_ExtCreationDate__c = Date.newInstance(2018, 12, 9);
      transactions.add(trc4);

      insert transactions;

      Asset ast1 = new Asset();
      ast1.Name = 'asset2';
      ast1.SerialNumber = '123456';
      ast1.AccountId = transactionOwner.Id;
      assets.add(ast1);

      Asset ast2 = new Asset();
      ast2.Name = 'asset3';
      ast2.SerialNumber = '1234568';
      ast2.RICSC_GoldenRecord__c = transactionOwner.Id;
      assets.add(ast2);

      Asset ast3 = new Asset();
      ast3.Name = 'asset4';
      ast3.SerialNumber = '01010';
      ast3.RICSC_GoldenRecord__c = transactionOwner.Id;
      assets.add(ast3);

      insert assets;
    }

    static testmethod void creationOfNewAssetBecauseTheIdMissmatch() {
      Test.startTest();
      BatchProductPortfolioIntegration uca = new BatchProductPortfolioIntegration(false,null);
      Id batchId = Database.executeBatch(uca);
      Test.stopTest();
      System.assertEquals([SELECT Name FROM Asset WHERE SerialNumber = '123457'].Name,'PP-123457');
    }

    static testmethod void updateTheAssetBecauseTheIdMatchPossitiveAmount() {
      Test.startTest();
      BatchProductPortfolioIntegration uca = new BatchProductPortfolioIntegration(false,null);
      Id batchId = Database.executeBatch(uca);
      Test.stopTest();
      //it updates the asset that match with the latest tranasction in the list because its possible to have more than one transaction
      //that the serialnumbers and lookup match so the one updates its the last one
      Asset updatedAsset = [SELECT Name,RICSC_ProductsReturned__c FROM Asset WHERE SerialNumber = '123456'];
      System.assertEquals(updatedAsset.Name,'PP-123456');
      System.assertEquals(updatedAsset.RICSC_ProductsReturned__c,false);
    }

    static testmethod void updateTheAssetBecauseTheIdMatchNegativeAmount() {
      Test.startTest();
      BatchProductPortfolioIntegration uca = new BatchProductPortfolioIntegration(false,null);
      Id batchId = Database.executeBatch(uca);
      Test.stopTest();
      //it updates the asset that match with the latest tranasction in the list because its possible to have more than one transaction
      //that the serialnumbers and lookup match so the one updates its the last one
      Asset updatedAsset = [SELECT Name,RICSC_ProductsReturned__c FROM Asset WHERE SerialNumber = '01010'];
      System.assertEquals(updatedAsset.Name,'PP-01010');
      System.assertEquals(updatedAsset.RICSC_ProductsReturned__c,true);
    }

    static testmethod void createAssetBecauseThereIsNotAnyWithSameLookUp() {
      Test.startTest();
      BatchProductPortfolioIntegration uca = new BatchProductPortfolioIntegration(false,null);
      Id batchId = Database.executeBatch(uca);
      Test.stopTest();
      System.assertEquals([SELECT Name FROM Asset WHERE SerialNumber = '2222'].Name,'PP-2222');
    }

    static testmethod void createAssetBecauseThereIsNotAnyWithSameLookUpTriggersSkipped() {
      Test.startTest();
      BatchProductPortfolioIntegration uca = new BatchProductPortfolioIntegration(true,null);
      Id batchId = Database.executeBatch(uca);
      Test.stopTest();
      System.assertEquals([SELECT Name FROM Asset WHERE SerialNumber = '2222'].Name,'PP-2222');
    }

}