unpackaged/main/default/objects/Account/fields/RICSC_Externalid__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Externalid__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>ID of the record in the externa, source system</description>
        <externalId>true</externalId>
        <label>Externalid</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Golden Record</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RICSC_IsGoldenRecord__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.RICSC_NotToBeGrouped__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Accounts (Local Records)</relationshipLabel>
        <relationshipName>RICSC_AccountGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_SourceCRM__c.field-meta.xml
<CustomField>
        <fullName>RICSC_SourceCRM__c</fullName>
        <description>Technical Field -  to indicate which CRM is the owner of the customer</description>
        <label>Source CRM</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Legacy_0050010</fullName>
                </value>
                <value>
                    <fullName>Legacy_0050050</fullName>
                </value>
                <value>
                    <fullName>Legacy_0050090</fullName>
                </value>
                <value>
                    <fullName>Legacy_0143090</fullName>
                </value>
                <value>
                    <fullName>Legacy_0153080</fullName>
                </value>
                <value>
                    <fullName>Legacy_0155000</fullName>
                </value>
                <value>
                    <fullName>Legacy_0163070</fullName>
                </value>
                <value>
                    <fullName>Legacy_0163170</fullName>
                </value>
                <value>
                    <fullName>Legacy_0163270</fullName>
                </value>
                <value>
                    <fullName>Legacy_0163370</fullName>
                </value>
                <value>
                    <fullName>Legacy_0174000</fullName>
                </value>
                <value>
                    <fullName>Legacy_0174010</fullName>
                </value>
                <value>
                    <fullName>Legacy_0174020</fullName>
                </value>
                <value>
                    <fullName>Legacy_0174030</fullName>
                </value>
                <value>
                    <fullName>Legacy_0186000</fullName>
                </value>
                <value>
                    <fullName>SAP_CRM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Case/fields/RICSC_ExternalID__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ExternalID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>ID of the record in the external source system</description>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </CustomField>

unpackaged/main/default/objects/Case/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to a Golden Record which has been created for the Account</description>
        <label>Golden Record</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>RICSC_TicketsGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Relation__c/RICSC_Relation__c.object-meta.xml
<CustomObject>
    <description>Relation object is used to track the relations between 2 Customers (e.g. father, husband etc)</description>
    <label>Relationship</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Relationship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RICSC_Relation__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to to link the related Person account (the one that has the role in the relation type)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationship</relationshipLabel>
        <relationshipName>RICSC_RelationsAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Relation__c/fields/RICSC_EndDate__c.field-meta.xml
<CustomField>
        <fullName>RICSC_EndDate__c</fullName>
        <description>It specifies when the relation has been closed</description>
        <label>End Date</label>
        <type>Date</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Relation__c/fields/RICSC_ExternalID__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ExternalID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>ID of the record in the external source system</description>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </CustomField>

unpackaged/main/default/objects/RICSC_Relation__c/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to to link the related Golden Record (the one that has the role in the relation type)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationship</relationshipLabel>
        <relationshipName>RICSC_RelationsGR</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Relation__c/fields/RICSC_InverseRelationship__c.field-meta.xml
<CustomField>
        <fullName>RICSC_InverseRelationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>System Field - to relate the respective inverse relation</description>
        <label>Inverse Relationship</label>
        <referenceTo>RICSC_Relation__c</referenceTo>
        <relationshipLabel>Relationships</relationshipLabel>
        <relationshipName>RICSC_RelationsInverseRelationship</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Relation__c/fields/RICSC_RelatedAccount__c.field-meta.xml
<CustomField>
        <fullName>RICSC_RelatedAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to to link the secondary Person account (the one to which the primary [Account] is related to)</description>
        <label>Related Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relations (Related Account)</relationshipLabel>
        <relationshipName>RICSC_RelationsRelatedAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Relation__c/fields/RICSC_RelationType__c.field-meta.xml
<CustomField>
        <fullName>RICSC_RelationType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It specifies the Relation type from the list of already availalvle relations stored in a the Relation type dedicated object</description>
        <label>Relation Type</label>
        <referenceTo>RICSC_RelationType__c</referenceTo>
        <relationshipLabel>Relationships</relationshipLabel>
        <relationshipName>RICSC_RelationsRelationType</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_RelationType__c/RICSC_RelationType__c.object-meta.xml
<CustomObject>
    <description>Relation Type object is used to store all the possible relations type that will be selected in the Relation Object</description>
    <label>Relation Type</label>
    <nameField>
        <label>Relationship Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relation Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RICSC_RelationType__c/fields/RICSC_ExternalID__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ExternalID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>ID of the record in the external source system</description>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </CustomField>

unpackaged/main/default/objects/RICSC_RelationType__c/fields/RICSC_InverseRelationshipRole__c.field-meta.xml
<CustomField>
        <fullName>RICSC_InverseRelationshipRole__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to link to the inverse role</description>
        <label>Inverse Relationship Role</label>
        <referenceTo>RICSC_RelationType__c</referenceTo>
        <relationshipLabel>Relation Types</relationshipLabel>
        <relationshipName>RICSC_RelationTypesInvRelationshipRole</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/classes/RelationTriggerHandler.cls
/******************************************************************************
@author Silvan Sholla
@date 25/Nov/2019
@description This is a container of all trigger classes on RICSC_Relation__c object used within the trigger framework.
******************************************************************************/

public with sharing class RelationTriggerHandler {

 /******************************************************************************
  * @author       Maurizio D'Antonio
  * @date         01/Oct/2019
  * @description  This class contains creation rules for RICSC_Relation__c object update
  ******************************************************************************/

  public without sharing class RelationUpdate implements TRG_TriggerHandlerInterface {
    public void runTriggerHandler(TRG_TriggerDispatcher.TriggerData td) {

      List<RICSC_Relation__c> relationsToUpdate = new List<RICSC_Relation__c>();

      Set<Id> inverseRelationshipsIds = new Set<Id>();
      Set<Id> relatedAccountIds = new Set<Id>();
      for(RICSC_Relation__c rel : (List<RICSC_Relation__c>) td.newList){
        if(rel.RICSC_InverseRelationship__c != null && rel.RICSC_Account__c != null){
          inverseRelationshipsIds.add(rel.RICSC_InverseRelationship__c);
          relatedAccountIds.add(rel.RICSC_Account__c);
        }
      }
      if(inverseRelationshipsIds.size() > 0){
        Map<Id, Account> accountsMap = new Map<Id, Account>([SELECT Id, RICSC_SourceCRM__c FROM Account WHERE Id IN :relatedAccountIds]);
        Map<Id, RICSC_Relation__c> inverseRelationships = new Map<Id, RICSC_Relation__c>([SELECT Id, RICSC_EndDate__c FROM RICSC_Relation__c WHERE Id IN :inverseRelationshipsIds]);
        for(RICSC_Relation__c rel : (List<RICSC_Relation__c>) td.newList){
          if(rel.RICSC_InverseRelationship__c != null && rel.RICSC_Account__c != null){
            String sourceCRM = accountsMap.get(rel.RICSC_Account__c).RICSC_SourceCRM__c;
            if(rel.RICSC_RelatedAccount__c != null && sourceCRM != null && sourceCRM.equals('SAP_CRM')){
              if(rel.RICSC_EndDate__c != td.oldMap.get(rel.Id).get('RICSC_EndDate__c')){
                RICSC_Relation__c inverseRelationship = inverseRelationships.get(rel.RICSC_InverseRelationship__c);
                inverseRelationship.RICSC_EndDate__c = rel.RICSC_EndDate__c;
                relationsToUpdate.add(inverseRelationship);
              }
            }
          }
        }
        if(relationsToUpdate.size() > 0){
          Database.update(relationsToUpdate);
        }
      }
    }
  }


  /******************************************************************************
  * @author       Maurizio D'Antonio
  * @date         01/Oct/2019
  * @description  This class contains creation rules for RICSC_Relation__c object creation
  ******************************************************************************/

  public without sharing class RelationCreation implements TRG_TriggerHandlerInterface {
    public void runTriggerHandler(TRG_TriggerDispatcher.TriggerData td) {
      Map<Id, RICSC_Relation__c> relIdToInverseRelationship = new Map<Id, RICSC_Relation__c>();
      Map<Id, RICSC_Relation__c> inverseRelationshipsMap = new Map<Id, RICSC_Relation__c>();
      Set<Id> relatedAccountIds = new Set<Id>();
      Set<Id> relationsIds = new Set<Id>();
      Set<Id> inverseRelationshipsIds = new Set<Id>();
      List<RICSC_Relation__c> relationsToUpdate = new List<RICSC_Relation__c>();
      for(RICSC_Relation__c rel : (List<RICSC_Relation__c>) td.newList){
        if(rel.RICSC_Account__c != null && rel.RICSC_RelatedAccount__c != null){
          relatedAccountIds.add(rel.RICSC_Account__c);
          if(rel.RICSC_InverseRelationship__c != null){
            inverseRelationshipsIds.add(rel.RICSC_InverseRelationship__c);
          }
          relationsIds.add(rel.Id);
        }
      }

      if(relationsIds.size()>0 && Schema.sObjectType.RICSC_Relation__c.isUpdateable()){
        if(inverseRelationshipsIds.size() > 0){
          inverseRelationshipsMap = new Map<Id,RICSC_Relation__c>([SELECT Id, RICSC_InverseRelationship__c FROM RICSC_Relation__c WHERE Id IN :inverseRelationshipsIds]);
        }
        List<String> selectFields = new List<String>(Schema.getGlobalDescribe().get('RICSC_Relation__c').getDescribe().fields.getMap().keySet());
        String query = 'SELECT RICSC_RelationType__r.RICSC_InverseRelationshipRole__c,' + String.join(selectFields, ',') + ' FROM RICSC_Relation__c WHERE Id IN :relationsIds';
        List<RICSC_Relation__c> relations = Database.query(query);
        Map<Id, Account> accountsMap = new Map<Id, Account>([SELECT Id, RICSC_SourceCRM__c FROM Account WHERE Id IN :relatedAccountIds]);
        for(RICSC_Relation__c rel : relations){
          if(rel.RICSC_InverseRelationship__c == null){
            String sourceCRM = accountsMap.get(rel.RICSC_Account__c).RICSC_SourceCRM__c;
            if(rel.RICSC_RelatedAccount__c != null && sourceCRM != null && sourceCRM.equals('SAP_CRM')){
              RICSC_Relation__c inverseRelationship = rel.clone(false, true, false, false);
              inverseRelationship.RICSC_Account__c = rel.RICSC_RelatedAccount__c;
              inverseRelationship.RICSC_RelatedAccount__c = rel.RICSC_Account__c;
              inverseRelationship.RICSC_ExternalID__c = null;
              inverseRelationship.RICSC_InverseRelationship__c = rel.Id;
              inverseRelationship.RICSC_RelationType__c = rel.RICSC_RelationType__r.RICSC_InverseRelationshipRole__c;
              relIdToInverseRelationship.put(rel.Id, inverseRelationship);
            }
          }
          else{
            RICSC_Relation__c inverseRelationship = inverseRelationshipsMap.get(rel.RICSC_InverseRelationship__c);
            if(inverseRelationship.RICSC_InverseRelationship__c == null){
              inverseRelationship.RICSC_InverseRelationship__c = rel.Id;
              relationsToUpdate.add(inverseRelationship);
            }
          }
        }
        if(relIdToInverseRelationship.size() > 0){
          Database.insert(relIdToInverseRelationship.values());
        }
        if(relationsToUpdate.size()>0){
          Database.update(relationsToUpdate);
        }
      }
    }
  }

  /******************************************************************************
  @author Silvan Sholla
  @date 25/Nov/2019
  @description propagate golden record lookup of relation based the accounts
               golden record : in case its populated on the account , then
               the golden record is filled with accounts golden record otherwise
               its getting filled with the local account id
  ******************************************************************************/
  public without sharing class GoldenRecordLookUpPopulate implements TRG_TriggerHandlerInterface {
    public void runTriggerHandler(TRG_TriggerDispatcher.TriggerData td) {
      UtilityAccount.goldenRecordLookUpPopulate('RICSC_RelationsAccount__r','RICSC_Account__c','RICSC_GoldenRecord__c','RelationTriggerHandler',td.newList);
    }
  }
}