unpackaged/main/default/objects/Account/fields/RICSC_ClientFlag__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ClientFlag__c</fullName>
        <description>Client categorization based on perceived value (what level of VIP)</description>
        <label>Client Flag</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Top VIP</fullName>
                </value>
                <value>
                    <fullName>VIP</fullName>
                </value>
                <value>
                    <fullName>Potential VIP</fullName>
                </value>
                <value>
                    <fullName>GOAL – Top</fullName>
                </value>
                <value>
                    <fullName>GOAL – Local</fullName>
                </value>
                <value>
                    <fullName>GOAL – Potential</fullName>
                </value>
                <value>
                    <fullName>GOAL+ – Existing HE</fullName>
                </value>
                <value>
                    <fullName>GOAL+ – Non-HE client</fullName>
                </value>
                <value>
                    <fullName>GOAL+ – Prospect</fullName>
                </value>
                <value>
                    <fullName>Loyal</fullName>
                </value>
                <value>
                    <fullName>Potential</fullName>
                </value>
                <value>
                    <fullName>SAV</fullName>
                </value>
                <value>
                    <fullName>Richemont Board of Directors</fullName>
                </value>
                <value>
                    <fullName>Family-Richemont Board of Directors</fullName>
                </value>
                <value>
                    <fullName>VIP1</fullName>
                    <isActive>false</isActive>
                    <label>VIP1</label>
                </value>
                <value>
                    <fullName>VIP2</fullName>
                    <isActive>false</isActive>
                    <label>VIP2</label>
                </value>
                <value>
                    <fullName>VIP5</fullName>
                    <isActive>false</isActive>
                    <label>VIP5</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Golden Record</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RICSC_IsGoldenRecord__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.RICSC_NotToBeGrouped__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Accounts (Local Records)</relationshipLabel>
        <relationshipName>RICSC_AccountGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_Turnover__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Turnover__c</fullName>
        <description>Calculated field with sum of all customer purchases</description>
        <label>Turnover</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_VIP__c.field-meta.xml
<CustomField>
        <fullName>RICSC_VIP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Client categorization based on perceived value</description>
        <label>VIP</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/classes/QueueableClasses.cls
/******************************************************************************
 * @author       Silvan Sholla
 * @date         17/Dec/2019
 * @description  This class contains all the queueable classes
 ******************************************************************************/

public class QueueableClasses {

  public class VIPFlagPropagationOverGoldenRecordVCA implements Queueable
  {
    public final Set<Id> goldenRecordAccountIds;

    public VIPFlagPropagationOverGoldenRecordVCA(Set<Id> goldenRecordAccountIds)
    {
        this.goldenRecordAccountIds = goldenRecordAccountIds;
    }
    public void execute(QueueableContext context)
    {
      List<Account> goldenWithRelatedRecords = [SELECT Id,RICSC_Turnover__c,RICSC_ClientFlag__c,(SELECT RICSC_VIP__c FROM RICSC_AccountGoldenRecord__r) FROM Account WHERE Id IN : goldenRecordAccountIds];
      List<sObject> listOfUpdatedRecords = new List < sObject > ();

      for(Account goldenRecord : goldenWithRelatedRecords){
        Boolean hasVipChilds = false;
        for(Account relatedLocal : goldenRecord.RICSC_AccountGoldenRecord__r){
          if(relatedLocal.RICSC_VIP__c == true){
            hasVipChilds = true;
            break;
          }
        }

        if(hasVipChilds == true){
          goldenRecord.RICSC_VIP__c = true;
        }
        else if((goldenRecord.RICSC_Turnover__c < 200000 && !UtilityConstants.CLIENT_FLAG_VIP_SET.contains(goldenRecord.RICSC_ClientFlag__c))){
          goldenRecord.RICSC_VIP__c = false;
        }
        listOfUpdatedRecords.add(goldenRecord);
      }

      // In this dml i do only golden record VIP population which doesnt have to propagate the VIP over the related objects
      // thats the reason i am dissabling it
      TRG_TriggerDispatcher.skipTriggerMap.put('AccountTriggerHandler.VIPFlagPropagation',true);
      Database.update(listOfUpdatedRecords);
      TRG_TriggerDispatcher.skipTriggerMap.put('AccountTriggerHandler.VIPFlagPropagation',false);
    }
  }


  public class FlagPropagationOverRelatedObjects implements Queueable
  {
    public final List<SObject> relatedRecords;
    public final Map<Id,Account> accountsThatChanged;
    public final String flagName;

    public FlagPropagationOverRelatedObjects(Map<Id,Account> accountsThatChanged,List<SObject> relatedRecords,String flagName)
    {
        this.relatedRecords = relatedRecords;
        this.accountsThatChanged = accountsThatChanged;
        this.flagName = flagName;
    }
    public void execute(QueueableContext context)
    {
      List<sObject> listOfUpdatedRecords = new List < sObject > ();

      for (SObject obj: relatedRecords) {
        Account acc = null;
        if(obj.getSobjectType().getDescribe().fields.getMap().keySet().contains('ricsc_account__c')){
          acc = accountsThatChanged.get((Id)obj.get('ricsc_account__c'));
        }
        else if(obj.getSobjectType().getDescribe().fields.getMap().keySet().contains('accountid')){
          acc = accountsThatChanged.get((Id)obj.get('AccountId'));
        }
        if(acc != null){
          obj.put(flagName, acc.get(flagName));
          listOfUpdatedRecords.add(obj);
        }
      }
      Database.update(listOfUpdatedRecords);
    }
  }

  public class DefaultRecordCalculationForRelatedObjects implements Queueable
  {
    public final String objectName;
    public final String parentChildRelationShip;
    public final Set<Id> goldenRecordIds;
    public final String checkBoxFieldNameLR;
    public final String checkBoxFieldNameGR;

    public DefaultRecordCalculationForRelatedObjects(String objectName,String parentChildRelationShip,Set<Id> goldenRecordIds,String checkBoxFieldNameLR,String checkBoxFieldNameGR)
    {
        this.objectName = objectName;
        this.parentChildRelationShip = parentChildRelationShip;
        this.goldenRecordIds = goldenRecordIds;
        this.checkBoxFieldNameLR = checkBoxFieldNameLR;
        this.checkBoxFieldNameGR = checkBoxFieldNameGR;
    }
    public void execute(QueueableContext context)
    {
      CalculatingFieldsHandler.setDefaultRecordForObject(objectName,parentChildRelationShip,goldenRecordIds,checkBoxFieldNameLR,checkBoxFieldNameGR);
    }
  }
}