unpackaged/main/default/objects/Account/fields/RICSC_Maison__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Maison__c</fullName>
        <description>List of Maisons</description>
        <label>Account Maison</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Maison</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_MasterRecordScore__c.field-meta.xml
<CustomField>
        <fullName>RICSC_MasterRecordScore__c</fullName>
        <description>This field is used to calculate a score for the Genera Rule for the Master Record Definition during the merge process.</description>
        <formula>RICSC_MRScoreTurnover__c  *  RICSC_MRScoreFrequency__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Master Record Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/RICSC_Transaction__c.object-meta.xml
<CustomObject>
    <description>capture transaction information.</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{000000000}</displayFormat>
        <label>Transaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to an Account - Release 1 SC</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>RICSC_TransactionsAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_AmountWithTaxEUR__c.field-meta.xml
<CustomField>
        <fullName>RICSC_AmountWithTaxEUR__c</fullName>
        <description>Total amount of the transaction coming from the source system</description>
        <label>Amount With Tax EUR</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_CurrencyKey__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CurrencyKey__c</fullName>
        <description>Currency keycoming from the source system</description>
        <label>Currency Key</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Currency</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_Maison__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Maison__c</fullName>
        <description>List of Maisons</description>
        <label>Maison</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Maison</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_SerialNumber__c.field-meta.xml
<CustomField>
        <fullName>RICSC_SerialNumber__c</fullName>
        <description>Serial Number of the product in the transaction</description>
        <label>Serial Number</label>
        <length>50</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_TransactionCategory__c.field-meta.xml
<CustomField>
        <fullName>RICSC_TransactionCategory__c</fullName>
        <description>Field to categorize a transaction of a certain type as Repair, Return, Sale</description>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Repair</fullName>
                </value>
                <value>
                    <fullName>Return</fullName>
                </value>
                <value>
                    <fullName>Sale</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_TransactionDate__c.field-meta.xml
<CustomField>
        <fullName>RICSC_TransactionDate__c</fullName>
        <description>Transaction Date in external system</description>
        <label>Transaction Date</label>
        <type>Date</type>
    </CustomField>

unpackaged/main/default/globalValueSets/RICSC_Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AWG</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BOV</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BTN</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYR</fullName>
    </customValue>
    <customValue>
        <fullName>BZD</fullName>
    </customValue>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <customValue>
        <fullName>CDF</fullName>
    </customValue>
    <customValue>
        <fullName>CHE</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <description>Unit of measurecoming</description>
    <masterLabel>Currency</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/RICSC_Maison.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cartier</fullName>
    </customValue>
    <customValue>
        <fullName>Jaeger Le Coultre</fullName>
    </customValue>
    <customValue>
        <fullName>Van Cleef &amp; Arpels</fullName>
    </customValue>
    <masterLabel>Maison</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/BatchMRScoreCalculation_Test.cls
@isTest
private class BatchMRScoreCalculation_Test {
    @testSetup
    static void setup() {
      UtilityTests.testSetup();
      TRG_TriggerDispatcher.skipTriggerMap.put('TransactionTriggerHandler.MRScoreCalculation',true);
      List<Account> accs = new List<Account>();
      Account mrScore1 = UtilityTests.getPersonAccount();
      mrScore1.LastName = 'MRScore1';
      Account mrScore2 = UtilityTests.getPersonAccount();
      mrScore2.LastName = 'MRScore2';
      Account mrScore3 = UtilityTests.getPersonAccount();
      mrScore3.LastName = 'MRScore3';
      insert mrScore1;
      insert mrScore2;
      insert mrScore3;
      List<RICSC_Transaction__c> instrans = new List<RICSC_Transaction__c>();
      RICSC_Transaction__c trCARNor = new RICSC_Transaction__c(RICSC_Account__c=mrScore1.id,RICSC_Maison__c='Cartier',RICSC_AmountWithTaxEUR__c=1000,RICSC_TransactionCategory__c=UtilityConstants.TRANSACTION_TYPE_SALES,RICSC_TransactionDate__c=System.now().date(),RICSC_SerialNumber__c='1000',RICSC_CurrencyKey__c='EUR');
      RICSC_Transaction__c trCARRep = new RICSC_Transaction__c(RICSC_Account__c=mrScore1.id,RICSC_Maison__c='Cartier',RICSC_AmountWithTaxEUR__c=1000,RICSC_TransactionCategory__c=UtilityConstants.TRANSACTION_TYPE_RETURN,RICSC_TransactionDate__c=System.now().date(),RICSC_SerialNumber__c='1000',RICSC_CurrencyKey__c='EUR');
      RICSC_Transaction__c trCARNor2 = new RICSC_Transaction__c(RICSC_Account__c=mrScore1.id,RICSC_Maison__c='Cartier',RICSC_AmountWithTaxEUR__c=1000,RICSC_TransactionCategory__c=UtilityConstants.TRANSACTION_TYPE_SALES,RICSC_TransactionDate__c=System.now().date(),RICSC_SerialNumber__c='1001',RICSC_CurrencyKey__c='EUR');
      RICSC_Transaction__c trCARNor2nullAm = new RICSC_Transaction__c(RICSC_Account__c=mrScore1.id,RICSC_Maison__c='Cartier',RICSC_TransactionCategory__c=UtilityConstants.TRANSACTION_TYPE_SALES,RICSC_TransactionDate__c=System.now().adddays(-5).date(),RICSC_SerialNumber__c='1002',RICSC_CurrencyKey__c='EUR');
      RICSC_Transaction__c trCARNorbef = new RICSC_Transaction__c(RICSC_Account__c=mrScore1.id,RICSC_Maison__c='Cartier',RICSC_AmountWithTaxEUR__c=1000,RICSC_TransactionCategory__c=UtilityConstants.TRANSACTION_TYPE_SALES,RICSC_TransactionDate__c=System.now().addyears(-6).date(),RICSC_SerialNumber__c='1003',RICSC_CurrencyKey__c='EUR');
      RICSC_Transaction__c trJLCNor = new RICSC_Transaction__c(RICSC_Account__c=mrScore2.id,RICSC_Maison__c='Jaeger Le Coultre',RICSC_AmountWithTaxEUR__c=1000,RICSC_TransactionCategory__c=UtilityConstants.TRANSACTION_TYPE_SALES,RICSC_TransactionDate__c=System.now().date(),RICSC_SerialNumber__c='3000',RICSC_CurrencyKey__c='EUR');
      RICSC_Transaction__c trJLCNorbef = new RICSC_Transaction__c(RICSC_Account__c=mrScore2.id,RICSC_Maison__c='Jaeger Le Coultre',RICSC_AmountWithTaxEUR__c=1000,RICSC_TransactionCategory__c=UtilityConstants.TRANSACTION_TYPE_SALES,RICSC_TransactionDate__c=System.now().addyears(-7).date(),RICSC_SerialNumber__c='3003',RICSC_CurrencyKey__c='EUR');
      RICSC_Transaction__c trJLCNorGR = new RICSC_Transaction__c(RICSC_Account__c=MRScore3.id,RICSC_Maison__c='Jaeger Le Coultre',RICSC_AmountWithTaxEUR__c=1000,RICSC_TransactionCategory__c=UtilityConstants.TRANSACTION_TYPE_SALES,RICSC_TransactionDate__c=System.now().date(),RICSC_SerialNumber__c='3001',RICSC_CurrencyKey__c='EUR');
      RICSC_Transaction__c trJLCNorGRnullAm = new RICSC_Transaction__c(RICSC_Account__c=MRScore3.id,RICSC_Maison__c='Jaeger Le Coultre',RICSC_AmountWithTaxEUR__c=1000,RICSC_TransactionCategory__c=UtilityConstants.TRANSACTION_TYPE_SALES,RICSC_TransactionDate__c=System.now().date(),RICSC_SerialNumber__c='3002',RICSC_CurrencyKey__c='EUR');
      RICSC_Transaction__c trJLCCSGRnullAm = new RICSC_Transaction__c(RICSC_Account__c=mrScore3.id, RICSC_Maison__c='Jaeger Le Coultre',RICSC_AmountWithTaxEUR__c=1000,RICSC_TransactionCategory__c=UtilityConstants.TRANSACTION_TYPE_REPAIR,RICSC_TransactionDate__c=System.now().date(),RICSC_SerialNumber__c='3003',RICSC_CurrencyKey__c='EUR');
      instrans.add(trCARNor);
      instrans.add(trCARNor2);
      instrans.add(trCARNor2nullAm);
      instrans.add(trCARRep);
      instrans.add(trCARNorbef);
      instrans.add(trJLCNorbef);
      instrans.add(trJLCNor);
      instrans.add(trJLCNorGR);
      instrans.add(trJLCNorGRnullAm);
      instrans.add(trJLCCSGRnullAm);
      insert instrans;
    }

    static testmethod void test() {
      Test.startTest();
      BatchMRScoreCalculation uca = new BatchMRScoreCalculation(true,null);
      Id batchId = Database.executeBatch(uca);
      Test.stopTest();
      List<Account> resins = [SELECT Id,RICSC_MasterRecordScore__c FROM Account Where Name = 'MRScore1' OR Name = 'MRScore2' OR Name = 'MRScore3' Order By Name DESC];
      System.assertEquals(2000,resins[0].RICSC_MasterRecordScore__c, 'Wrong MR score');
      System.assertEquals(4000,resins[1].RICSC_MasterRecordScore__c, 'Wrong MR score');
      System.assertEquals(3000,resins[2].RICSC_MasterRecordScore__c, 'Wrong MR score');
    }


}