unpackaged/main/default/objects/Account/fields/RICSC_GR__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GR__c</fullName>
        <description>Formula field showing golden record icon if a the record is a golden one</description>
        <formula>if( RICSC_IsGoldenRecord__c , IMAGE('/resource/GRIcon?','Image not found', 25,25),'' )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GR</label>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_SocialMediaID__c/RICSC_SocialMediaID__c.object-meta.xml
<CustomObject>
    <description>This object is used to collect  the Social ID of the related Local records.</description>
    <label>Social Media ID</label>
    <nameField>
        <displayFormat>S-{000000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Social Media IDs</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_SocialMediaID__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to Account (Contact)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Social Media IDs</relationshipLabel>
        <relationshipName>RICSC_SocialMediaIDsAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_SocialMediaID__c/fields/RICSC_DefaultGRSocialMediaID__c.field-meta.xml
<CustomField>
        <fullName>RICSC_DefaultGRSocialMediaID__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default GR Social Media ID</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_SocialMediaID__c/fields/RICSC_DefaultSocialMediaID__c.field-meta.xml
<CustomField>
        <fullName>RICSC_DefaultSocialMediaID__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Default Social Media ID , the last modified social media</description>
        <label>Default Social Media ID</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_SocialMediaID__c/fields/RICSC_GR__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to the golden record</description>
        <label>GR</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Social Media IDs</relationshipLabel>
        <relationshipName>RICSC_SocialMediaIDsGR</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/classes/SocialMediaIDTriggerHandler.cls
/******************************************************************************
@author Silvan Sholla
@date 25/Nov/2019
@description This is a container of all trigger classes on RICSC_SocialMediaID__c object used within the trigger framework.
******************************************************************************/

public with sharing class SocialMediaIDTriggerHandler {

  public without sharing class VCARecordSharing implements TRG_TriggerHandlerInterface {
    public void runTriggerHandler(TRG_TriggerDispatcher.TriggerData td) {

      Set<Id> accountIds = new Set<Id>();
      for(RICSC_SocialMediaID__c email : (List<RICSC_SocialMediaID__c>) td.newList){
        if(email.RICSC_Account__c != null){
          accountIds.add(email.RICSC_Account__c);
        }
        if(email.RICSC_GR__c != null){
          accountIds.add(email.RICSC_GR__c);
        }
      }

      if(td.isInsert){
        SharingRuleTriggerHelper.AfterInsert(td.newList,accountIds,'RICSC_SocialMediaID__share');
      }
      if(td.isUpdate){
        SharingRuleTriggerHelper.AfterUpdate(td.newList,td.oldMap,accountIds,'RICSC_SocialMediaID__share');
      }
    }
  }

  public without sharing class DefaultSocialMediaIDCheck implements TRG_TriggerHandlerInterface {
    public void runTriggerHandler(TRG_TriggerDispatcher.TriggerData td) {
      Set<Id> involvedAccs = new Set<Id>();

      if(td.isInsert){
        for(SObject currentRecord : (List<SObject>) td.newList){
          if(currentRecord.get('RICSC_GR__c') != null){
            involvedAccs.add(currentRecord.get('RICSC_GR__c').toString());
          }
        }
      }else if(td.isUpdate){
        for(SObject currentRecord : (List<SObject>) td.newList){
          if(currentRecord.get('RICSC_GR__c') != null){
            involvedAccs.add(currentRecord.get('RICSC_GR__c').toString());
          }
        }
      }
      if(involvedAccs.size()>0){
        if(!Utility.isAsync()){
          System.enqueueJob(new QueueableClasses.DefaultRecordCalculationForRelatedObjects('RICSC_SocialMediaID__c','RICSC_SocialMediaIDsGR__r',involvedAccs,'RICSC_DefaultSocialMediaID__c','RICSC_DefaultGRSocialMediaID__c'));
        }else{
          CalculatingFieldsHandler.setDefaultRecordForObject('RICSC_SocialMediaID__c','RICSC_SocialMediaIDsGR__r',involvedAccs,'RICSC_DefaultSocialMediaID__c','RICSC_DefaultGRSocialMediaID__c');
        }
      }
    }
  }

  /******************************************************************************
  @author Silvan Sholla
  @date 25/Nov/2019
  @description propagate golden record lookup of SocialMedia based the accounts
               golden record : in case its populated on the account , then
               the golden record is filled with accounts golden record otherwise
               its getting filled with the local account id
  ******************************************************************************/
  public without sharing class GoldenRecordLookUpPopulate implements TRG_TriggerHandlerInterface {
    public void runTriggerHandler(TRG_TriggerDispatcher.TriggerData td) {
      UtilityAccount.goldenRecordLookUpPopulate('RICSC_SocialMediaIDsAccount__r','RICSC_Account__c','RICSC_GR__c','SocialMediaIDTriggerHandler',td.newList);
    }
  }
}