unpackaged/main/default/objects/Account/fields/RICSC_CountryOfOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryOfOrigin__c</fullName>
        <description>Country where the record has been created. Used for the sharing rules (e.g. records created outside of China shouldn't be visible for the Chineese users) - Release 1 SC</description>
        <label>Account Country Of Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_Email__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Email__c</fullName>
        <description>email field to capture the email of the Boutique</description>
        <label>Email</label>
        <type>Email</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_ReferenceSA__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ReferenceSA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is populated with the SF ID correspondent to the respective SAP SA coming from SAP as a consequence of a calculation</description>
        <label>Reference SA</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (Reference SA)</relationshipLabel>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_VIP__c.field-meta.xml
<CustomField>
        <fullName>RICSC_VIP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Client categorization based on perceived value</description>
        <label>VIP</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Contact/fields/RICSC_CountryOfOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryOfOrigin__c</fullName>
        <description>Country where the record has been created. Used for the sharing rules (e.g. records created outside of China shouldn't be visible for the Chineese users) - Release 1 SC</description>
        <label>Sales Associate Country Of Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </RecordType>

unpackaged/main/default/objects/RICSC_Email__c/RICSC_Email__c.object-meta.xml
<CustomObject>
    <description>This object is used to collect  the Emails of the related Local records.</description>
    <label>Email</label>
    <nameField>
        <displayFormat>E-{000000000}</displayFormat>
        <label>Email</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to the Account (contact)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Emails</relationshipLabel>
        <relationshipName>RICSC_EmailsAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_CountryofOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryofOrigin__c</fullName>
        <description>Picklist to capture the client's country of origin</description>
        <label>Country of Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_Email__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Email__c</fullName>
        <description>Standard email type field</description>
        <label>Email</label>
        <length>80</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_VIP__c.field-meta.xml
<CustomField>
        <fullName>RICSC_VIP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It identifies if the Record is VIP or not . It is recalculated at the GR record level based on Maisons' rules</description>
        <label>VIP</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/globalValueSets/RICSC_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Amer.Virgin Is.</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua/Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia-Herz.</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Islands</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Monaco</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/EmailTriggerHandler_Test.cls
@isTest
public with sharing class EmailTriggerHandler_Test {

@testSetup
  static void setup() {

    Contact newFrenchSalesAssociate = UtilityTests.getContact();
    newFrenchSalesAssociate.RICSC_CountryOfOrigin__c = 'France';
    insert newFrenchSalesAssociate;
    Contact newMonacoSalesAssociate = UtilityTests.getContact();
    newMonacoSalesAssociate.RICSC_CountryOfOrigin__c = 'Monaco';
    insert newMonacoSalesAssociate;

    Account newVanCleefAndArpelsAccount = UtilityTests.getPersonAccount();
    newVanCleefAndArpelsAccount.LastName = 'VanCleefAndArpelsFranceAccount';
    newVanCleefAndArpelsAccount.RICSC_VIP__c = true;
    newVanCleefAndArpelsAccount.RICSC_ReferenceSA__c = newFrenchSalesAssociate.Id;
    insert newVanCleefAndArpelsAccount;

    Account newVanCleefAndArpelsAccountGoldenRecord = UtilityTests.getPersonAccount();
    newVanCleefAndArpelsAccountGoldenRecord.LastName = 'newVanCleefAndArpelsAccountGoldenRecord';
    newVanCleefAndArpelsAccountGoldenRecord.RICSC_VIP__c = true;
    newVanCleefAndArpelsAccountGoldenRecord.RICSC_ReferenceSA__c = newMonacoSalesAssociate.Id;
    insert newVanCleefAndArpelsAccountGoldenRecord;

    RICSC_Email__c afterUpdateTestingEmail = UtilityTests.getEmail();
    afterUpdateTestingEmail.RICSC_Account__c = newVanCleefAndArpelsAccount.Id;
    insert afterUpdateTestingEmail;

    Account newVanCleefAndArpelsMonacoAccount = UtilityTests.getPersonAccount();
    newVanCleefAndArpelsMonacoAccount.LastName = 'VanCleefAndArpelsMonacoAccount';
    newVanCleefAndArpelsMonacoAccount.RICSC_VIP__c = true;
    newVanCleefAndArpelsMonacoAccount.RICSC_ReferenceSA__c = newMonacoSalesAssociate.Id;
    insert newVanCleefAndArpelsMonacoAccount;

  }

  static testmethod void afterInsertSharingRulesCreateOnEmailObjectLRANDGRFieldPopulated() {
    Contact frenchAccount = [SELECT Id FROM Contact WHERE RICSC_CountryOfOrigin__c = 'France' LIMIT 1];
    Account vanCleefAndArpelsAccount = [SELECT Id, RICSC_VIP__c, RICSC_ReferenceSA__c FROM Account WHERE Name = 'VanCleefAndArpelsFranceAccount'];
    Account newVanCleefAndArpelsAccountGoldenRecord = [SELECT Id, RICSC_VIP__c, RICSC_ReferenceSA__c FROM Account WHERE Name = 'newVanCleefAndArpelsAccountGoldenRecord'];
    RICSC_Email__c testEmail = UtilityTests.getEmail();
    testEmail.RICSC_Account__c = vanCleefAndArpelsAccount.Id;
    insert testEmail;
    List<Group> gp = [SELECT DeveloperName FROM Group WHERE DeveloperName = 'RICSC_VCACRMFrance' AND Id IN (SELECT UserOrGroupId FROM RICSC_Email__share)];
    System.assertEquals(false,gp.isEmpty());
    gp = [SELECT DeveloperName FROM Group WHERE DeveloperName = 'RICSC_VCACRMMonaco' AND Id IN (SELECT UserOrGroupId FROM RICSC_Email__share)];
    System.assertEquals(true,gp.isEmpty());
  }


  static testmethod void afterInsertSharingRulesCreateOnEmailObjectLRFieldPopulated() {
    Contact frenchAccount = [SELECT Id FROM Contact WHERE RICSC_CountryOfOrigin__c = 'France' LIMIT 1];
    Account vanCleefAndArpelsAccount = [SELECT Id, RICSC_VIP__c, RICSC_ReferenceSA__c FROM Account WHERE Name = 'VanCleefAndArpelsFranceAccount'];
    RICSC_Email__c testEmail = UtilityTests.getEmail();
    testEmail.RICSC_Account__c = vanCleefAndArpelsAccount.Id;
    insert testEmail;

    List<Group> gp = [SELECT DeveloperName FROM Group WHERE DeveloperName = 'RICSC_VCACRMFrance' AND Id IN (SELECT UserOrGroupId FROM RICSC_Email__share)];
    System.assertEquals(gp.isEmpty(),false);
  }


  static testmethod void afterUpdateSharingRulesCreateOnEmailObject() {

    //BeforeUpdate
    List<Group> gp = [SELECT DeveloperName FROM Group WHERE DeveloperName = 'RICSC_VCACRMMonaco' AND Id IN (SELECT UserOrGroupId FROM RICSC_Email__share)];
    System.assertEquals(gp.isEmpty(),true);

    Account acc = [SELECT Id FROM Account WHERE Name = 'VanCleefAndArpelsMonacoAccount'];
    RICSC_Email__c updateEmail = [SELECT Id,RICSC_Account__c FROM RICSC_Email__c];
    updateEmail.RICSC_Account__c = acc.Id;
    update updateEmail;

    //AfterUpdate
    gp = [SELECT DeveloperName FROM Group WHERE DeveloperName = 'RICSC_VCACRMMonaco' AND Id IN (SELECT UserOrGroupId FROM RICSC_Email__share)];
    System.assertEquals(gp.isEmpty(),false);
  }

}