unpackaged/main/default/objects/Account/fields/RICSC_Email__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Email__c</fullName>
        <description>email field to capture the email of the Boutique</description>
        <label>Email</label>
        <type>Email</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_GR__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GR__c</fullName>
        <description>Formula field showing golden record icon if a the record is a golden one</description>
        <formula>if( RICSC_IsGoldenRecord__c , IMAGE('/resource/GRIcon?','Image not found', 25,25),'' )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GR</label>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Email__c/RICSC_Email__c.object-meta.xml
<CustomObject>
    <description>This object is used to collect  the Emails of the related Local records.</description>
    <label>Email</label>
    <nameField>
        <displayFormat>E-{000000000}</displayFormat>
        <label>Email</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to the Account (contact)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Emails</relationshipLabel>
        <relationshipName>RICSC_EmailsAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_DefaultEmail__c.field-meta.xml
<CustomField>
        <fullName>RICSC_DefaultEmail__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to identify which is the primary email. For the LR comes from the Source System in the GR is populated  based on rules</description>
        <label>Default Email</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_DefaultGREmail__c.field-meta.xml
<CustomField>
        <fullName>RICSC_DefaultGREmail__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default GR Email</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_Email__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Email__c</fullName>
        <description>Standard email type field</description>
        <label>Email</label>
        <length>80</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_GR__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This lookup field links the email to the golden record</description>
        <label>GR</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Emails</relationshipLabel>
        <relationshipName>RICSC_EmailsGR</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/classes/EmailTriggerHandler.cls
/******************************************************************************
@author Silvan Sholla
@date 25/Nov/2019
@description This is a container of all trigger classes on RICSC_Email__c object used within the trigger framework.
******************************************************************************/

public with sharing class EmailTriggerHandler {

  public without sharing class VCARecordSharing implements TRG_TriggerHandlerInterface {
    public void runTriggerHandler(TRG_TriggerDispatcher.TriggerData td) {

      Set<Id> accountIds = new Set<Id>();
      for(RICSC_Email__c email : (List<RICSC_Email__c>) td.newList){
        if(email.RICSC_Account__c != null){
          accountIds.add(email.RICSC_Account__c);
        }
        if(email.RICSC_GR__c != null){
          accountIds.add(email.RICSC_GR__c);
        }
      }

      if(td.isInsert){
        SharingRuleTriggerHelper.AfterInsert(td.newList,accountIds,'RICSC_Email__share');
      }
      if(td.isUpdate){
        SharingRuleTriggerHelper.AfterUpdate(td.newList,td.oldMap,accountIds,'RICSC_Email__share');
      }
    }
  }

  public without sharing class DefaultEmailCheck implements TRG_TriggerHandlerInterface {

    public void runTriggerHandler(TRG_TriggerDispatcher.TriggerData td) {

      Set<Id> involvedAccs = new Set<Id>();

      if(td.isInsert){
        for(SObject currentRecord : (List<SObject>) td.newList){
          if(currentRecord.get('RICSC_GR__c') != null){
            involvedAccs.add(currentRecord.get('RICSC_GR__c').toString());
          }
        }
      }else if(td.isUpdate){
        for(SObject currentRecord : (List<SObject>) td.newList){
          if(currentRecord.get('RICSC_GR__c') != null){
            involvedAccs.add(currentRecord.get('RICSC_GR__c').toString());
          }
        }
      }

      if(involvedAccs.size()>0){
        if(!Utility.isAsync()){
          System.enqueueJob(new QueueableClasses.DefaultRecordCalculationForRelatedObjects('RICSC_Email__c','RICSC_EmailsGR__r',involvedAccs,'RICSC_DefaultEmail__c','RICSC_DefaultGREmail__c'));
        }else{
          CalculatingFieldsHandler.setDefaultRecordForObject('RICSC_Email__c','RICSC_EmailsGR__r',involvedAccs,'RICSC_DefaultEmail__c','RICSC_DefaultGREmail__c');
        }
      }
    }
  }

  /******************************************************************************
  @author Silvan Sholla
  @date 25/Nov/2019
  @description propagate golden record lookup of email based the accounts
               golden record : in case its populated on the account , then
               the golden record is filled with accounts golden record otherwise
               its getting filled with the local account id
  ******************************************************************************/
  public without sharing class GoldenRecordLookUpPopulate implements TRG_TriggerHandlerInterface {
    public void runTriggerHandler(TRG_TriggerDispatcher.TriggerData td) {
      UtilityAccount.goldenRecordLookUpPopulate('RICSC_EmailsAccount__r','RICSC_Account__c','RICSC_GR__c','EmailTriggerHandler',td.newList);
    }
  }
}