unpackaged/main/default/objects/Account/fields/RICSC_ClassCode__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ClassCode__c</fullName>
        <description>Client segment based on rules in SAP</description>
        <label>Class Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Boutique Client</fullName>
                </value>
                <value>
                    <fullName>Boutique Service client</fullName>
                </value>
                <value>
                    <fullName>Cartier Call Center Prospect</fullName>
                </value>
                <value>
                    <fullName>Cartier Customer Service</fullName>
                </value>
                <value>
                    <fullName>Cartier Prospect</fullName>
                </value>
                <value>
                    <fullName>Cartier Prospect Multichannel</fullName>
                </value>
                <value>
                    <fullName>Cartier Retail</fullName>
                </value>
                <value>
                    <fullName>Cartier Retail Mutlichannel Customer</fullName>
                </value>
                <value>
                    <fullName>Cartier Retail Web Customer</fullName>
                </value>
                <value>
                    <fullName>Charity</fullName>
                </value>
                <value>
                    <fullName>Charity Client</fullName>
                </value>
                <value>
                    <fullName>Contact Center Client</fullName>
                </value>
                <value>
                    <fullName>Contact Center Retail Client</fullName>
                </value>
                <value>
                    <fullName>Contact Center Service Client</fullName>
                </value>
                <value>
                    <fullName>Customer Service Client</fullName>
                </value>
                <value>
                    <fullName>E-Commerce Client</fullName>
                </value>
                <value>
                    <fullName>Multi-Channel Client</fullName>
                </value>
                <value>
                    <fullName>Multi-channel Retail Client</fullName>
                </value>
                <value>
                    <fullName>Multi-channel Service Client</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Prospect Boutique</fullName>
                </value>
                <value>
                    <fullName>Prospect contact center</fullName>
                </value>
                <value>
                    <fullName>Prospect Partnership</fullName>
                </value>
                <value>
                    <fullName>Prospect Web</fullName>
                </value>
                <value>
                    <fullName>Prospect Web Cartier</fullName>
                </value>
                <value>
                    <fullName>Staff</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>Web Client</fullName>
                </value>
                <value>
                    <fullName>Web Retail Client</fullName>
                </value>
                <value>
                    <fullName>Wholesaler</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Golden Record</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RICSC_IsGoldenRecord__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.RICSC_NotToBeGrouped__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Accounts (Local Records)</relationshipLabel>
        <relationshipName>RICSC_AccountGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_HasLocalRecords__c.field-meta.xml
<CustomField>
        <fullName>RICSC_HasLocalRecords__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Local Records</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_IsGoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_IsGoldenRecord__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Golden Record</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Asset/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to a Golden Record which has been created for the Account - Release 1 SC</description>
        <label>Golden Record</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Product Portfolios</relationshipLabel>
        <relationshipName>RICSC_AssetsGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/RICSC_Transaction__c.object-meta.xml
<CustomObject>
    <description>capture transaction information.</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{000000000}</displayFormat>
        <label>Transaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to an Account - Release 1 SC</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>RICSC_TransactionsAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to a Golden Record which has been created for the Account - Release 1 SC</description>
        <label>Golden Record</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>RICSC_TransactionsGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_TransactionCategory__c.field-meta.xml
<CustomField>
        <fullName>RICSC_TransactionCategory__c</fullName>
        <description>Field to categorize a transaction of a certain type as Repair, Return, Sale</description>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Repair</fullName>
                </value>
                <value>
                    <fullName>Return</fullName>
                </value>
                <value>
                    <fullName>Sale</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/classes/ProductPortfolioTriggerHandler_Test.cls
@isTest
public with sharing class ProductPortfolioTriggerHandler_Test {

  @testSetup
  static void setup() {
    Account involvedAccount = UtilityTests.getPersonAccount();
    involvedAccount.RICSC_IsGoldenRecord__c = true;
    involvedAccount.RICSC_HasLocalRecords__c = true;
    insert involvedAccount;
  }

  static testmethod void classCodeWholesaler() {
    //Class code is wholesaler if all assets are without transaction id
    Test.startTest();
    Account acc = [SELECT Id FROM Account LIMIT 1];
    Asset involvedAsset = UtilityTests.getAsset();
    involvedAsset.Name = 'Involved Asset';
    involvedAsset.RICSC_GoldenRecord__c = acc.Id;
    insert involvedAsset;
    Asset involvedAsset2 = UtilityTests.getAsset();
    involvedAsset2.Name = 'Involved Asset 2';
    involvedAsset2.RICSC_GoldenRecord__c = acc.Id;
    insert involvedAsset2;
    Test.stopTest();

    System.assertEquals(UtilityConstants.CLASS_CODE_WHLSL, [SELECT RICSC_ClassCode__c FROM Account LIMIT 1].RICSC_ClassCode__c,0);
  }

   static testmethod void classCodeProspect() {
    Account acc = [SELECT Id, RICSC_ClassCode__c FROM Account LIMIT 1];
    //if no transaction related and class code not already wholesaler then CLASS CODE is Prospect
    System.assertEquals(UtilityConstants.CLASS_CODE_PROSP, acc.RICSC_ClassCode__c);
    Test.startTest();
    RICSC_Transaction__c tr = new RICSC_Transaction__c(RICSC_GoldenRecord__c = acc.Id,RICSC_Account__c = acc.Id,RICSC_TransactionCategory__c = UtilityConstants.TRANSACTION_TYPE_REPAIR);
    insert tr;
    acc = [SELECT Id, RICSC_ClassCode__c FROM Account LIMIT 1];
    //if no transaction related and class code not already wholesaler then CLASS CODE is Prospect
    System.assertEquals(UtilityConstants.CLASS_CODE_SCLNT, acc.RICSC_ClassCode__c);
    acc = [SELECT Id FROM Account LIMIT 1];
    Test.stopTest();
  }

   static testmethod void assertCreationAndPreviousDeletion() {

     Account acc = [SELECT Id FROM Account LIMIT 1];
	
     Test.startTest();  
     Asset ast1 = UtilityTests.getAsset();
     ast1.Name = 'Asset That is Going To Be Deleted';
     ast1.AccountId = acc.Id;
     ast1.SerialNumber = '1234';
     ast1.Price	= 20;
     insert ast1;

     Asset ast2 = UtilityTests.getAsset();
     ast2.Name = 'Asset That is Going To Be Inserted';
     ast2.AccountId = acc.Id;
     ast2.SerialNumber = '1234';
     ast2.Price = 30;
     insert ast2;
	 Test.stopTest();
       
     //Since the two assets got same serial number, the excisting asset is going to be deleted
     System.assertEquals(1,[SELECT count() FROM Asset WHERE isDeleted = false]);

     //The Second Asset that is being imported is going actually to take place of the first one
     System.assertEquals(30, [SELECT Price FROM Asset WHERE isDeleted = false].Price);

   }


}