unpackaged/main/default/objects/Account/fields/RICSC_SourceCRM__c.field-meta.xml
<CustomField>
        <fullName>RICSC_SourceCRM__c</fullName>
        <description>Technical Field -  to indicate which CRM is the owner of the customer</description>
        <label>Source CRM</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Legacy_0050010</fullName>
                </value>
                <value>
                    <fullName>Legacy_0050050</fullName>
                </value>
                <value>
                    <fullName>Legacy_0050090</fullName>
                </value>
                <value>
                    <fullName>Legacy_0143090</fullName>
                </value>
                <value>
                    <fullName>Legacy_0153080</fullName>
                </value>
                <value>
                    <fullName>Legacy_0155000</fullName>
                </value>
                <value>
                    <fullName>Legacy_0163070</fullName>
                </value>
                <value>
                    <fullName>Legacy_0163170</fullName>
                </value>
                <value>
                    <fullName>Legacy_0163270</fullName>
                </value>
                <value>
                    <fullName>Legacy_0163370</fullName>
                </value>
                <value>
                    <fullName>Legacy_0174000</fullName>
                </value>
                <value>
                    <fullName>Legacy_0174010</fullName>
                </value>
                <value>
                    <fullName>Legacy_0174020</fullName>
                </value>
                <value>
                    <fullName>Legacy_0174030</fullName>
                </value>
                <value>
                    <fullName>Legacy_0186000</fullName>
                </value>
                <value>
                    <fullName>SAP_CRM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Relation__c/RICSC_Relation__c.object-meta.xml
<CustomObject>
    <description>Relation object is used to track the relations between 2 Customers (e.g. father, husband etc)</description>
    <label>Relationship</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Relationship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RICSC_Relation__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to to link the related Person account (the one that has the role in the relation type)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationship</relationshipLabel>
        <relationshipName>RICSC_RelationsAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Relation__c/fields/RICSC_EndDate__c.field-meta.xml
<CustomField>
        <fullName>RICSC_EndDate__c</fullName>
        <description>It specifies when the relation has been closed</description>
        <label>End Date</label>
        <type>Date</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Relation__c/fields/RICSC_InverseRelationship__c.field-meta.xml
<CustomField>
        <fullName>RICSC_InverseRelationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>System Field - to relate the respective inverse relation</description>
        <label>Inverse Relationship</label>
        <referenceTo>RICSC_Relation__c</referenceTo>
        <relationshipLabel>Relationships</relationshipLabel>
        <relationshipName>RICSC_RelationsInverseRelationship</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Relation__c/fields/RICSC_RelatedAccount__c.field-meta.xml
<CustomField>
        <fullName>RICSC_RelatedAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to to link the secondary Person account (the one to which the primary [Account] is related to)</description>
        <label>Related Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relations (Related Account)</relationshipLabel>
        <relationshipName>RICSC_RelationsRelatedAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Relation__c/fields/RICSC_RelationType__c.field-meta.xml
<CustomField>
        <fullName>RICSC_RelationType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It specifies the Relation type from the list of already availalvle relations stored in a the Relation type dedicated object</description>
        <label>Relation Type</label>
        <referenceTo>RICSC_RelationType__c</referenceTo>
        <relationshipLabel>Relationships</relationshipLabel>
        <relationshipName>RICSC_RelationsRelationType</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_RelationType__c/RICSC_RelationType__c.object-meta.xml
<CustomObject>
    <description>Relation Type object is used to store all the possible relations type that will be selected in the Relation Object</description>
    <label>Relation Type</label>
    <nameField>
        <label>Relationship Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relation Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RICSC_RelationType__c/fields/RICSC_InverseRelationshipRole__c.field-meta.xml
<CustomField>
        <fullName>RICSC_InverseRelationshipRole__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to link to the inverse role</description>
        <label>Inverse Relationship Role</label>
        <referenceTo>RICSC_RelationType__c</referenceTo>
        <relationshipLabel>Relation Types</relationshipLabel>
        <relationshipName>RICSC_RelationTypesInvRelationshipRole</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_RelationType__c/fields/RICSC_InverseRoleName__c.field-meta.xml
<CustomField>
        <fullName>RICSC_InverseRoleName__c</fullName>
        <description>This is the inverse role name (e.g. Son)</description>
        <label>Inverse Role Name</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/classes/RelationTriggerHandler_Test.cls
@isTest
public with sharing class RelationTriggerHandler_Test {
    public RelationTriggerHandler_Test() {
      makeData();
    }

    @TestSetup
    static void makeData(){
      RICSC_RelationType__c type1 = new RICSC_RelationType__c(Name = 'Wife', RICSC_InverseRoleName__c = 'Husband');
      insert type1;
      RICSC_RelationType__c type2 = new RICSC_RelationType__c(Name = 'Husband', RICSC_InverseRoleName__c = 'Wife');
      insert type2;
      type1.RICSC_InverseRelationshipRole__c = type2.Id;
      type2.RICSC_InverseRelationshipRole__c = type1.Id;
      update type1;
      update type2;
    }

    @IsTest
    static void relationManagementTest(){
      Test.startTest();
      RICSC_RelationType__c wifeRelationType = [SELECT Id FROM RICSC_RelationType__c WHERE Name = 'Wife' LIMIT 1];
      RICSC_RelationType__c husbandRelationType = [SELECT Id FROM RICSC_RelationType__c WHERE Name = 'Husband' LIMIT 1];
      Account wife = new Account(FirstName = 'Wife', LastName = 'Account', RICSC_SourceCRM__c = 'SAP_CRM');
      insert wife;
      Account husband = new Account(FirstName = 'Husband', LastName = 'Account', RICSC_SourceCRM__c = 'SAP_CRM');
      insert husband;
      RICSC_Relation__c rel = new RICSC_Relation__c(RICSC_RelationType__c = wifeRelationType.Id, RICSC_Account__c = wife.Id, RICSC_RelatedAccount__c = husband.Id);
      insert rel;

      List<RICSC_Relation__c> inverseRelationship = [SELECT Id FROM RICSC_Relation__c WHERE RICSC_InverseRelationship__c = :rel.Id];
      System.assert(inverseRelationship.size() > 0);

      rel.RICSC_EndDate__c = Date.today();
      update rel;

      inverseRelationship = [SELECT Id,RICSC_EndDate__c FROM RICSC_Relation__c WHERE RICSC_InverseRelationship__c = :rel.Id];
      System.assert(inverseRelationship.size() > 0 && inverseRelationship.get(0).RICSC_EndDate__c != null);

      Test.stopTest();
    }
}