unpackaged/main/default/objects/Account/fields/RICSC_CanBeContacted__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CanBeContacted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>LR: value retrieved from SAP regarding customer permission to be contacted by Richemont.
GR: Populated based on rules.</description>
        <label>Can Be Contacted</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_ConsentTimestamp__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ConsentTimestamp__c</fullName>
        <description>Technical Field -  to indicate the timestamp of the last consent update</description>
        <label>Consent Timestamp</label>
        <type>DateTime</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_ElectronicContact__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ElectronicContact__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to indicate whether this contact can be reached via electronic correspondance</description>
        <label>Electronic Contact</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Golden Record</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RICSC_IsGoldenRecord__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.RICSC_NotToBeGrouped__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Accounts (Local Records)</relationshipLabel>
        <relationshipName>RICSC_AccountGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_HasLocalRecords__c.field-meta.xml
<CustomField>
        <fullName>RICSC_HasLocalRecords__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Local Records</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_PostalContact__c.field-meta.xml
<CustomField>
        <fullName>RICSC_PostalContact__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to indicate whether this contact can be used for mail &amp; deliveries</description>
        <label>Postal Contact</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_VIP__c.field-meta.xml
<CustomField>
        <fullName>RICSC_VIP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Client categorization based on perceived value</description>
        <label>VIP</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_VoiceContact__c.field-meta.xml
<CustomField>
        <fullName>RICSC_VoiceContact__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to indicate whether this contact can be reached via voice correspondance (telephone calls)</description>
        <label>Voice Contact</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/classes/BatchConsentsOnRecords_Test.cls
@isTest
private class BatchConsentsOnRecords_Test {
    @testSetup
    static void setup() {
        Account newVanCleefAndArpelsAccount = new Account();
        newVanCleefAndArpelsAccount.LastName = 'VanCleefAndArpelsAccount';
        newVanCleefAndArpelsAccount.RecordTypeId = RecordTypeHelper.getRTId('Account', 'RICSC_VanCleefAndArpels');
        newVanCleefAndArpelsAccount.RICSC_VIP__c = true;
        newVanCleefAndArpelsAccount.RICSC_ConsentTimestamp__c = Datetime.now().addDays(-5);
        newVanCleefAndArpelsAccount.RICSC_HasLocalRecords__c = true;
        insert newVanCleefAndArpelsAccount;

        Account newVanCleefAndArpelsAccount2 = new Account();
        newVanCleefAndArpelsAccount2.LastName = 'VanCleefAndArpelsAccount2';
        newVanCleefAndArpelsAccount2.RecordTypeId = RecordTypeHelper.getRTId('Account', 'RICSC_VanCleefAndArpels');
        newVanCleefAndArpelsAccount2.RICSC_VIP__c = false;
        newVanCleefAndArpelsAccount2.RICSC_ConsentTimestamp__c = Datetime.now().addMonths(-1);
        newVanCleefAndArpelsAccount2.RICSC_GoldenRecord__c = newVanCleefAndArpelsAccount.id;
        insert newVanCleefAndArpelsAccount2;

    }

    static testmethod void goldenCanBeContacted() {
      Test.startTest();
      TRG_TriggerDispatcher.skipTriggerMap.put('Account',true);
      Account goldenAccount = [SELECT Id, RICSC_GoldenRecord__c, RICSC_ConsentTimestamp__c, RICSC_CanBeContacted__c, RICSC_PostalContact__c, RICSC_ElectronicContact__c, RICSC_VoiceContact__c
                                                FROM Account
                                                WHERE LastName = 'VanCleefAndArpelsAccount'];
      goldenAccount.RICSC_CanBeContacted__c = true;
      goldenAccount.RICSC_ConsentTimestamp__c = Datetime.now();
      update goldenAccount;
      BatchConsentsOnRecords uca = new BatchConsentsOnRecords(true, null);
      Id batchid = Database.executeBatch(uca);
      Test.stopTest();
      List<Account> localRecords = [SELECT Id, RICSC_GoldenRecord__c, RICSC_ConsentTimestamp__c, RICSC_CanBeContacted__c, RICSC_PostalContact__c, RICSC_ElectronicContact__c, RICSC_VoiceContact__c
                                    FROM Account
                                    WHERE LastName = 'VanCleefAndArpelsAccount2'];
      List<Account> accountsWithFalseFlag = new List<Account>();
      for(Account acc : localRecords){
        if(!acc.RICSC_CanBeContacted__c){
          accountsWithFalseFlag.add(acc);
        }
      }
      System.assert(accountsWithFalseFlag.isEmpty(), 'Accounts with false flag');
    }

    static testmethod void localPostalContact() {
      Test.startTest();
      TRG_TriggerDispatcher.skipTriggerMap.put('Account',true);
      Account goldenAccount = [SELECT Id, RICSC_GoldenRecord__c, RICSC_ConsentTimestamp__c, RICSC_CanBeContacted__c, RICSC_PostalContact__c, RICSC_ElectronicContact__c, RICSC_VoiceContact__c
                                                FROM Account
                                                WHERE LastName = 'VanCleefAndArpelsAccount'];
      goldenAccount.RICSC_PostalContact__c = true;
      goldenAccount.RICSC_ConsentTimestamp__c = Datetime.now().addMonths(-10);
      update goldenAccount;
      BatchConsentsOnRecords uca = new BatchConsentsOnRecords(true, null);
      Id batchid = Database.executeBatch(uca);
      Test.stopTest();
      List<Account> localRecords = [SELECT Id, RICSC_GoldenRecord__c, RICSC_ConsentTimestamp__c, RICSC_CanBeContacted__c, RICSC_PostalContact__c, RICSC_ElectronicContact__c, RICSC_VoiceContact__c
                      FROM Account
                      WHERE LastName = 'VanCleefAndArpelsAccount2'];
      List<Account> accountsWithFalseFlag = new List<Account>();
      for(Account acc : localRecords){
        if(!acc.RICSC_PostalContact__c){
          accountsWithFalseFlag.add(acc);
        }
      }
      System.assert(accountsWithFalseFlag.size()>0, 'Accounts with false flag');
    }

   static testmethod void goldenElectronicContact() {
      Test.startTest();
      TRG_TriggerDispatcher.skipTriggerMap.put('Account',true);
      List<Account> localRecords = [SELECT Id, RICSC_GoldenRecord__c, RICSC_ConsentTimestamp__c, RICSC_CanBeContacted__c, RICSC_PostalContact__c, RICSC_ElectronicContact__c, RICSC_VoiceContact__c
                FROM Account
                WHERE LastName = 'VanCleefAndArpelsAccount2'];
      Account localRecord = localRecords.get(0);
      localRecord.RICSC_ElectronicContact__c = true;
      localRecord.RICSC_ConsentTimestamp__c = Datetime.now().addMonths(1);
      update localRecord;
      BatchConsentsOnRecords uca = new BatchConsentsOnRecords(true, null);
      Id batchid = Database.executeBatch(uca);
      Test.stopTest();
      List<Account> relatedRecords = [SELECT Id, RICSC_GoldenRecord__c, RICSC_ConsentTimestamp__c, RICSC_CanBeContacted__c, RICSC_PostalContact__c, RICSC_ElectronicContact__c, RICSC_VoiceContact__c
                      FROM Account
                      WHERE LastName = 'VanCleefAndArpelsAccount2' OR LastName = 'VanCleefAndArpelsAccount'];
      System.debug('==> relatedRecords: ' + relatedRecords);
      List<Account> accountsWithFalseFlag = new List<Account>();
      for(Account acc : relatedRecords){
        if(!acc.RICSC_ElectronicContact__c){
          accountsWithFalseFlag.add(acc);
        }
      }
      System.debug('==> accountsWithFalseFlag: ' + accountsWithFalseFlag);
      System.assert(accountsWithFalseFlag.isEmpty(), 'Accounts with false flag');
   }

   static testmethod void goldenVoiceContact() {
      Test.startTest();
      TRG_TriggerDispatcher.skipTriggerMap.put('Account',true);
      Account localRecord= [SELECT Id, RICSC_GoldenRecord__c, RICSC_ConsentTimestamp__c, RICSC_CanBeContacted__c, RICSC_PostalContact__c, RICSC_ElectronicContact__c, RICSC_VoiceContact__c
                FROM Account
                WHERE LastName = 'VanCleefAndArpelsAccount2'];
      localRecord.RICSC_VoiceContact__c = true;
      localRecord.RICSC_ConsentTimestamp__c = Datetime.now().addMonths(-1);
      update localRecord;
      BatchConsentsOnRecords uca = new BatchConsentsOnRecords(true, null);
      Id batchid = Database.executeBatch(uca);
      Test.stopTest();
      List<Account> relatedRecords = [SELECT Id, RICSC_GoldenRecord__c, RICSC_ConsentTimestamp__c, RICSC_CanBeContacted__c, RICSC_PostalContact__c, RICSC_ElectronicContact__c, RICSC_VoiceContact__c
                      FROM Account
                      WHERE LastName = 'VanCleefAndArpelsAccount2' OR LastName = 'VanCleefAndArpelsAccount'];
      List<Account> accountsWithFalseFlag = new List<Account>();
      for(Account acc : relatedRecords){
        if(!acc.RICSC_VoiceContact__c){
          accountsWithFalseFlag.add(acc);
        }
      }
      System.assert(accountsWithFalseFlag.size()>0, 'Accounts with false flag');

    }

}