unpackaged/main/default/objects/Account/fields/RICSC_Email__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Email__c</fullName>
        <description>email field to capture the email of the Boutique</description>
        <label>Email</label>
        <type>Email</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Address__c/RICSC_Address__c.object-meta.xml
<CustomObject>
    <description>This object is used to collect  the Addresses of the related Local records.</description>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Address__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to Account (Contact)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>RICSC_AddressesAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Address__c/fields/RICSC_Address__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Address__c</fullName>
        <description>Field to capture the full address</description>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Address__c/fields/RICSC_GRMainAddress__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GRMainAddress__c</fullName>
        <defaultValue>false</defaultValue>
        <description>a flag indicating the main email address for the Golden record (based on the GR Lookup - not Account)</description>
        <label>GR Main Address</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Address__c/fields/RICSC_LRMainAddress__c.field-meta.xml
<CustomField>
        <fullName>RICSC_LRMainAddress__c</fullName>
        <defaultValue>false</defaultValue>
        <description>a flag indicating the main email address for the Local record (based on the Account Lookup - not GR)</description>
        <label>LR Main Address</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Email__c/RICSC_Email__c.object-meta.xml
<CustomObject>
    <description>This object is used to collect  the Emails of the related Local records.</description>
    <label>Email</label>
    <nameField>
        <displayFormat>E-{000000000}</displayFormat>
        <label>Email</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to the Account (contact)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Emails</relationshipLabel>
        <relationshipName>RICSC_EmailsAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_DefaultEmail__c.field-meta.xml
<CustomField>
        <fullName>RICSC_DefaultEmail__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to identify which is the primary email. For the LR comes from the Source System in the GR is populated  based on rules</description>
        <label>Default Email</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_DefaultGREmail__c.field-meta.xml
<CustomField>
        <fullName>RICSC_DefaultGREmail__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default GR Email</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_Email__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Email__c</fullName>
        <description>Standard email type field</description>
        <label>Email</label>
        <length>80</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Phone__c/RICSC_Phone__c.object-meta.xml
<CustomObject>
    <description>This object is used to collect  the Phones of the related Local records.</description>
    <label>Phone</label>
    <nameField>
        <displayFormat>P-{000000000}</displayFormat>
        <label>Phone</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Phones</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Phone__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to Account (Contact)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Phones</relationshipLabel>
        <relationshipName>RICSC_PhonesAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Phone__c/fields/RICSC_DefaultGRPhone__c.field-meta.xml
<CustomField>
        <fullName>RICSC_DefaultGRPhone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default GR Phone</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Phone__c/fields/RICSC_DefaultPhone__c.field-meta.xml
<CustomField>
        <fullName>RICSC_DefaultPhone__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to identify which is the primary phone. For the LR comes from the Source System in the GR is populated  based on rules</description>
        <label>Default Phone</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Phone__c/fields/RICSC_Phone__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Phone__c</fullName>
        <description>Standard phone field</description>
        <label>Phone</label>
        <type>Phone</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_SocialMediaID__c/RICSC_SocialMediaID__c.object-meta.xml
<CustomObject>
    <description>This object is used to collect  the Social ID of the related Local records.</description>
    <label>Social Media ID</label>
    <nameField>
        <displayFormat>S-{000000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Social Media IDs</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_SocialMediaID__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to Account (Contact)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Social Media IDs</relationshipLabel>
        <relationshipName>RICSC_SocialMediaIDsAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_SocialMediaID__c/fields/RICSC_DefaultGRSocialMediaID__c.field-meta.xml
<CustomField>
        <fullName>RICSC_DefaultGRSocialMediaID__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default GR Social Media ID</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_SocialMediaID__c/fields/RICSC_DefaultSocialMediaID__c.field-meta.xml
<CustomField>
        <fullName>RICSC_DefaultSocialMediaID__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Default Social Media ID , the last modified social media</description>
        <label>Default Social Media ID</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/classes/BatchDefaultRecord_Test.cls
@isTest
private class BatchDefaultRecord_Test {

  @testSetup
  static void setup() {

    TRG_TriggerDispatcher.skipTriggerMap.put('EmailTriggerHandler.DefaultEmailCheck',true);
    TRG_TriggerDispatcher.skipTriggerMap.put('AddressTriggerHandler.DefaultAddressCheck',true);
    TRG_TriggerDispatcher.skipTriggerMap.put('PhoneTriggerHandler.DefaultPhoneCheck',true);
    TRG_TriggerDispatcher.skipTriggerMap.put('SocialMediaIDTriggerHandler.DefaultSocialMediaIDCheck',true);
    TRG_TriggerDispatcher.skipTriggerMap.put('AccountTriggerHandler.defaultRecordsBasedOnMasterRecordScore',true);

    Account newPersonAccountLR = UtilityTests.getPersonAccount();
    newPersonAccountLR.FirstName = 'FirstName';
    newPersonAccountLR.LastName = 'LastName';

    insert newPersonAccountLR;

    List<RICSC_Email__c> emails = new List<RICSC_Email__c>();

    RICSC_Email__c newEmail = UtilityTests.getEmail();
    newEmail.RICSC_Account__c = newPersonAccountLR.Id;
    emails.add(newEmail);

    RICSC_Email__c newEmail1 = UtilityTests.getEmail();
    newEmail1.RICSC_Account__c = newPersonAccountLR.Id;
    newEmail1.RICSC_DefaultEmail__c = true;
    emails.add(newEmail1);

    RICSC_Email__c newEmail2 = UtilityTests.getEmail();
    newEmail2.RICSC_Account__c = newPersonAccountLR.Id;
    emails.add(newEmail2);

    insert emails;

    List<RICSC_Phone__c> phones = new List<RICSC_Phone__c>();
    RICSC_Phone__c newPhone = UtilityTests.getPhone();
    newPhone.RICSC_Account__c = newPersonAccountLR.Id;
    phones.add(newPhone);

    insert phones;

    List<RICSC_socialMediaId__c> socialMediaIds = new List<RICSC_socialMediaId__c>();
    RICSC_socialMediaId__c newsocialMediaId = UtilityTests.getsocialMediaId();
    newsocialMediaId.RICSC_Account__c = newPersonAccountLR.Id;
    socialMediaIds.add(newsocialMediaId);

    insert socialMediaIds;

    List<RICSC_address__c> addresss = new List<RICSC_address__c>();
    RICSC_address__c newaddress = UtilityTests.getaddress();
    newaddress.RICSC_Account__c = newPersonAccountLR.Id;
    addresss.add(newaddress);

    insert addresss;
  }

  static testmethod void defaultEmailCheck() {
    Test.startTest();
    BatchDefaultRecord bas = new BatchDefaultRecord(false, null);
    Id batchId = Database.executeBatch(bas);
    Test.stopTest();
    System.assertEquals(1,[SELECT Id FROM RICSC_Email__c WHERE RICSC_DefaultGREmail__c = true].size(), 'Email not set as default');
    System.assertEquals(1,[SELECT Id FROM RICSC_Email__c WHERE RICSC_DefaultEmail__c = true].size(), 'Email not set as default');
  }

  static testmethod void defaultAddressCheck() {
    Test.startTest();
    BatchDefaultRecord bas = new BatchDefaultRecord(false, null);
    Id batchId = Database.executeBatch(bas);
    Test.stopTest();
    System.assertEquals(1,[SELECT Id FROM RICSC_Address__c WHERE RICSC_GRMainAddress__c = true].size(), 'Address not set as default');
    System.assertEquals(1,[SELECT Id FROM RICSC_Address__c WHERE RICSC_LRMainAddress__c = true].size(), 'Address not set as default');
  }

  static testmethod void defaultSocialMediaIDCheck() {
    Test.startTest();
    BatchDefaultRecord bas = new BatchDefaultRecord(false, null);
    Id batchId = Database.executeBatch(bas);
    Test.stopTest();
    System.assertEquals(1,[SELECT Id FROM RICSC_SocialMediaID__c WHERE RICSC_DefaultGRSocialMediaID__c = true].size(), 'Social ID not set as default');
    System.assertEquals(1,[SELECT Id FROM RICSC_SocialMediaID__c WHERE RICSC_DefaultSocialMediaID__c = true].size(), 'Social ID not set as default');
  }

   static testmethod void defaultPhoneCheck() {
    Test.startTest();
    BatchDefaultRecord bas = new BatchDefaultRecord(false, null);
    Id batchId = Database.executeBatch(bas);
    Test.stopTest();
    System.assertEquals(1,[SELECT Id FROM RICSC_Phone__c WHERE RICSC_DefaultGRPhone__c = true].size(), 'Phone not set as default');
    System.assertEquals(1,[SELECT Id FROM RICSC_Phone__c WHERE RICSC_DefaultPhone__c = true].size(), 'Phone not set as default');
  }

  static testmethod void defaultPhoneCheckSkippTriggers() {
    Test.startTest();
    BatchDefaultRecord bas = new BatchDefaultRecord(true, null);
    Id batchId = Database.executeBatch(bas);
    Test.stopTest();
    System.assertEquals(1,[SELECT Id FROM RICSC_Phone__c WHERE RICSC_DefaultGRPhone__c = true].size(), 'Phone not set as default');
  }

}