unpackaged/main/default/objects/Account/fields/RICSC_ClientFlag__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ClientFlag__c</fullName>
        <description>Client categorization based on perceived value (what level of VIP)</description>
        <label>Client Flag</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Top VIP</fullName>
                </value>
                <value>
                    <fullName>VIP</fullName>
                </value>
                <value>
                    <fullName>Potential VIP</fullName>
                </value>
                <value>
                    <fullName>GOAL – Top</fullName>
                </value>
                <value>
                    <fullName>GOAL – Local</fullName>
                </value>
                <value>
                    <fullName>GOAL – Potential</fullName>
                </value>
                <value>
                    <fullName>GOAL+ – Existing HE</fullName>
                </value>
                <value>
                    <fullName>GOAL+ – Non-HE client</fullName>
                </value>
                <value>
                    <fullName>GOAL+ – Prospect</fullName>
                </value>
                <value>
                    <fullName>Loyal</fullName>
                </value>
                <value>
                    <fullName>Potential</fullName>
                </value>
                <value>
                    <fullName>SAV</fullName>
                </value>
                <value>
                    <fullName>Richemont Board of Directors</fullName>
                </value>
                <value>
                    <fullName>Family-Richemont Board of Directors</fullName>
                </value>
                <value>
                    <fullName>VIP1</fullName>
                    <isActive>false</isActive>
                    <label>VIP1</label>
                </value>
                <value>
                    <fullName>VIP2</fullName>
                    <isActive>false</isActive>
                    <label>VIP2</label>
                </value>
                <value>
                    <fullName>VIP5</fullName>
                    <isActive>false</isActive>
                    <label>VIP5</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_CollectionOfInterests__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CollectionOfInterests__c</fullName>
        <description>Multi-selection of: client interests and Maison (e.g. Watches JLC)</description>
        <label>Collection Of Interests</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Accessories</fullName>
                </value>
                <value>
                    <fullName>Antique Pieces</fullName>
                </value>
                <value>
                    <fullName>Ballet/Opera</fullName>
                </value>
                <value>
                    <fullName>Bridal</fullName>
                </value>
                <value>
                    <fullName>Bridal jewellery</fullName>
                </value>
                <value>
                    <fullName>Classic</fullName>
                </value>
                <value>
                    <fullName>Collector</fullName>
                </value>
                <value>
                    <fullName>Complications</fullName>
                </value>
                <value>
                    <fullName>Design/Architecture</fullName>
                </value>
                <value>
                    <fullName>Drive</fullName>
                </value>
                <value>
                    <fullName>Enameling</fullName>
                </value>
                <value>
                    <fullName>Engraving</fullName>
                </value>
                <value>
                    <fullName>Estate Pieces</fullName>
                </value>
                <value>
                    <fullName>Eyewear</fullName>
                </value>
                <value>
                    <fullName>Fashion/Couture</fullName>
                </value>
                <value>
                    <fullName>Fine Watchmaking</fullName>
                </value>
                <value>
                    <fullName>Fragrance</fullName>
                </value>
                <value>
                    <fullName>Gastronomy/Wine</fullName>
                </value>
                <value>
                    <fullName>Gem-Setting</fullName>
                </value>
                <value>
                    <fullName>Generic function</fullName>
                </value>
                <value>
                    <fullName>Heritage/Craftsmanship</fullName>
                </value>
                <value>
                    <fullName>High Jewellery</fullName>
                </value>
                <value>
                    <fullName>Jewellery</fullName>
                </value>
                <value>
                    <fullName>Lady</fullName>
                </value>
                <value>
                    <fullName>Leather Goods</fullName>
                </value>
                <value>
                    <fullName>Limited series</fullName>
                </value>
                <value>
                    <fullName>Love</fullName>
                </value>
                <value>
                    <fullName>Nature/Gardens</fullName>
                </value>
                <value>
                    <fullName>New creations</fullName>
                </value>
                <value>
                    <fullName>Pens</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_ECard__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ECard__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the customer has been created using the eCard (i.e. no paper card for its consent</description>
        <label>E Card</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_GlobalSegment__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GlobalSegment__c</fullName>
        <description>Calculated segmentation based on rules taking into account the local transactions</description>
        <label>Global Segment</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Golden Record</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RICSC_IsGoldenRecord__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.RICSC_NotToBeGrouped__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Accounts (Local Records)</relationshipLabel>
        <relationshipName>RICSC_AccountGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_Hobbies__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Hobbies__c</fullName>
        <description>Client's hobbies in text format</description>
        <label>Hobbies</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>CRICKET</fullName>
                </value>
                <value>
                    <fullName>F1_MOTOR_RACING</fullName>
                </value>
                <value>
                    <fullName>PEN_COLL</fullName>
                </value>
                <value>
                    <fullName>RUGBY</fullName>
                </value>
                <value>
                    <fullName>SAILING</fullName>
                </value>
                <value>
                    <fullName>SHOPPING</fullName>
                </value>
                <value>
                    <fullName>SKIING</fullName>
                </value>
                <value>
                    <fullName>SPORT</fullName>
                </value>
                <value>
                    <fullName>TENNIS</fullName>
                </value>
                <value>
                    <fullName>THEATRE</fullName>
                </value>
                <value>
                    <fullName>TRAVEL</fullName>
                </value>
                <value>
                    <fullName>WATCH_COLL</fullName>
                </value>
                <value>
                    <fullName>WATER</fullName>
                </value>
                <value>
                    <fullName>WHISKY</fullName>
                </value>
                <value>
                    <fullName>WINE</fullName>
                </value>
                <value>
                    <fullName>WINTER_SPORTS</fullName>
                </value>
                <value>
                    <fullName>YACHTING</fullName>
                </value>
                <value>
                    <fullName>YOGA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_LocalVIP__c.field-meta.xml
<CustomField>
        <fullName>RICSC_LocalVIP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Technical field to indicate if there is at least 1 VIP among the Local Records</description>
        <inlineHelpText>If flagged at least on Local record is VIP</inlineHelpText>
        <label>Local VIP</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_Notes__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Notes__c</fullName>
        <description>Notes coming from SAP CRM. Long notes stored on the customers, same issue than activities to retrieve this information</description>
        <label>Notes</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_ProductOfInterests__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ProductOfInterests__c</fullName>
        <description>Multi-selection of all products (coming from SAP) the client has a known interest in, coming from SAP.</description>
        <label>Product Of Interests</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Accessories Belt</fullName>
                </value>
                <value>
                    <fullName>Accessories Card holder</fullName>
                </value>
                <value>
                    <fullName>Accessories Clock</fullName>
                </value>
                <value>
                    <fullName>Accessories Cufflinks</fullName>
                </value>
                <value>
                    <fullName>Accessories Handbags &amp; Leather</fullName>
                </value>
                <value>
                    <fullName>Accessories Key ring</fullName>
                </value>
                <value>
                    <fullName>Accessories Lighter</fullName>
                </value>
                <value>
                    <fullName>Accessories Money clip</fullName>
                </value>
                <value>
                    <fullName>Accessories Other</fullName>
                </value>
                <value>
                    <fullName>Accessories Pens</fullName>
                </value>
                <value>
                    <fullName>Accessories Prescript Eyewear</fullName>
                </value>
                <value>
                    <fullName>Accessories Scarf</fullName>
                </value>
                <value>
                    <fullName>Accessories Small Leather</fullName>
                </value>
                <value>
                    <fullName>Accessories Sunglasses</fullName>
                </value>
                <value>
                    <fullName>AMVOX</fullName>
                </value>
                <value>
                    <fullName>Atmos</fullName>
                </value>
                <value>
                    <fullName>Bridal Ballerine</fullName>
                </value>
                <value>
                    <fullName>Bridal Cartier D’Amour</fullName>
                </value>
                <value>
                    <fullName>Bridal C De Cartier</fullName>
                </value>
                <value>
                    <fullName>Bridal Classic Wedding Bands</fullName>
                </value>
                <value>
                    <fullName>Bridal Declaration</fullName>
                </value>
                <value>
                    <fullName>Bridal Honeymoon</fullName>
                </value>
                <value>
                    <fullName>Bridal LOVE</fullName>
                </value>
                <value>
                    <fullName>Bridal Other</fullName>
                </value>
                <value>
                    <fullName>Bridal Solitaire 1895</fullName>
                </value>
                <value>
                    <fullName>Bridal Trinity</fullName>
                </value>
                <value>
                    <fullName>Duomètre</fullName>
                </value>
                <value>
                    <fullName>Extraordinary</fullName>
                </value>
                <value>
                    <fullName>Fragrances Baiser Volé</fullName>
                </value>
                <value>
                    <fullName>Fragrances Déclaration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_SpotNotes__c.field-meta.xml
<CustomField>
        <fullName>RICSC_SpotNotes__c</fullName>
        <description>Additional notes coming from SAP CRM. This field stores a short text (50 char) popping up every time we display this customer</description>
        <label>Spot Notes</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_Turnover__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Turnover__c</fullName>
        <description>Calculated field with sum of all customer purchases</description>
        <label>Turnover</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_VIP__c.field-meta.xml
<CustomField>
        <fullName>RICSC_VIP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Client categorization based on perceived value</description>
        <label>VIP</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/classes/BatchCalculatedFields.cls
public class BatchCalculatedFields implements Database.Batchable<SObject>, Schedulable {

    public static final Integer MAX_SCOPE = 100;
    private Set<String> recordTypeSet = UtilityConstants.PERSON_ACCOUNT_RT_SET_ID;
    private String query = 'SELECT Id, RecordTypeId, RICSC_GoldenRecord__c, RICSC_Turnover__c, RICSC_ClientFlag__c, RICSC_GlobalSegment__c, RICSC_Vip__c, RICSC_ECard__c, RICSC_Notes__c, RICSC_SpotNotes__c, RICSC_ProductOfInterests__c, RICSC_CollectionOfInterests__c,RICSC_Hobbies__c,RICSC_LocalVIP__c FROM Account';
    private Boolean skipTriggersOnAccount = false;

    public Iterable<SObject> start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    public BatchCalculatedFields(Boolean skipParam, String queryStr) {
      this.query = queryStr == null ? this.query : queryStr;
      skipTriggersOnAccount = skipParam;
    }

    public void execute(SchedulableContext sc) {
        BatchCalculatedFields b = new BatchCalculatedFields(false, null);
        Database.executeBatch(b, MAX_SCOPE);
    }

    public void execute(Database.BatchableContext bc, List<Account> scope) {
      try{

        Set<Id> allScopeAccIds = new Set<Id>();
        List<Account> accountsAfterCalculatedFields = new List<Account>();
        Set<Account> vipAccs = new Set<Account>();

        for(Account ac : scope){
          allScopeAccIds.add(ac.Id);
        }

        // First of all we do the fields calculation
        if(skipTriggersOnAccount){
          TRG_TriggerDispatcher.skipTriggerMap.put('Account',true);
        }

        accountsAfterCalculatedFields = CalculatingFieldsHandler.computeFieldsFromTransactionRecords(allScopeAccIds);
        update accountsAfterCalculatedFields;

        if(skipTriggersOnAccount){
          TRG_TriggerDispatcher.skipTriggerMap.put('Account',false);
        }

        // We also calculate concatenated fields on GR_G account in scope
        accountsAfterCalculatedFields = [SELECT Id, RecordTypeId, RICSC_GoldenRecord__c, RICSC_Turnover__c, RICSC_ClientFlag__c, RICSC_GlobalSegment__c, RICSC_Vip__c, RICSC_ECard__c, RICSC_Notes__c, RICSC_SpotNotes__c, RICSC_ProductOfInterests__c, RICSC_CollectionOfInterests__c,RICSC_Hobbies__c,RICSC_LocalVIP__c FROM Account WHERE Id IN: allScopeAccIds];
        for(Account ac : accountsAfterCalculatedFields){
          if (ac.RICSC_Turnover__c != null || ac.RICSC_ClientFlag__c != null || ac.RICSC_GlobalSegment__c != null){
            vipAccs.add(ac);
          }
        }

        Map<Id,CalculatingFieldsHandler.CalculatedAccountFieldCont> calculatedValuesXGRgId = new Map <Id,CalculatingFieldsHandler.CalculatedAccountFieldCont>();
        CalculatingFieldsHandler.computeConcatenatedFieldsOnGR(allScopeAccIds,calculatedValuesXGRgId);

        // Based on the previous calculations we also decide if the user is VIP
        CalculatingFieldsHandler.computeVipFlag(vipAccs,calculatedValuesXGRgId);

        if(skipTriggersOnAccount){
          TRG_TriggerDispatcher.skipTriggerMap.put('Account',true);
        }

        update CalculatingFieldsHandler.getComputedAccounts(calculatedValuesXGRgId.values());

        if(skipTriggersOnAccount){
          TRG_TriggerDispatcher.skipTriggerMap.put('Account',false);
        }

      } catch(Exception e) {
        UtilityLogger.logException(e,e.getMessage(),'BatchCalculatedFields','execute');
      }
    }

    public void finish(Database.BatchableContext bc) {
    }
}