unpackaged/main/default/objects/Account/fields/RICSC_CanBeContacted__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CanBeContacted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>LR: value retrieved from SAP regarding customer permission to be contacted by Richemont.
GR: Populated based on rules.</description>
        <label>Can Be Contacted</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_ClientSegment__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ClientSegment__c</fullName>
        <description>Client classification based on rules in SAP</description>
        <label>Client Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Access 0-6 U05</fullName>
                </value>
                <value>
                    <fullName>Access 7-12 U10</fullName>
                </value>
                <value>
                    <fullName>Access Accessories</fullName>
                </value>
                <value>
                    <fullName>Access Bijoux</fullName>
                </value>
                <value>
                    <fullName>Access Frequent E10</fullName>
                </value>
                <value>
                    <fullName>Access Frequent E13</fullName>
                </value>
                <value>
                    <fullName>Access Frequent E2</fullName>
                </value>
                <value>
                    <fullName>Access Frequent E6</fullName>
                </value>
                <value>
                    <fullName>Access New N5</fullName>
                </value>
                <value>
                    <fullName>Access One Shot E4</fullName>
                </value>
                <value>
                    <fullName>Access One Shot E8</fullName>
                </value>
                <value>
                    <fullName>Access One Time Buyer E3</fullName>
                </value>
                <value>
                    <fullName>Access One Time Buyer E6</fullName>
                </value>
                <value>
                    <fullName>Access Regular E11</fullName>
                </value>
                <value>
                    <fullName>Access Regular E14</fullName>
                </value>
                <value>
                    <fullName>Access Regular E3</fullName>
                </value>
                <value>
                    <fullName>Access Regular E7</fullName>
                </value>
                <value>
                    <fullName>Access Repeater E2</fullName>
                </value>
                <value>
                    <fullName>Access Repeater E5</fullName>
                </value>
                <value>
                    <fullName>Access Super frequent E1</fullName>
                </value>
                <value>
                    <fullName>Access Super frequent E12</fullName>
                </value>
                <value>
                    <fullName>Access Super Frequent E4</fullName>
                </value>
                <value>
                    <fullName>Access Super frequent E5</fullName>
                </value>
                <value>
                    <fullName>Access Super frequent E9</fullName>
                </value>
                <value>
                    <fullName>Access Watch</fullName>
                </value>
                <value>
                    <fullName>ACTIVE</fullName>
                </value>
                <value>
                    <fullName>Active Clients 20K</fullName>
                </value>
                <value>
                    <fullName>Active - Elegant</fullName>
                </value>
                <value>
                    <fullName>Active - Frequent</fullName>
                </value>
                <value>
                    <fullName>Active - Occasional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_ConsentTimestamp__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ConsentTimestamp__c</fullName>
        <description>Technical Field -  to indicate the timestamp of the last consent update</description>
        <label>Consent Timestamp</label>
        <type>DateTime</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_Email__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Email__c</fullName>
        <description>email field to capture the email of the Boutique</description>
        <label>Email</label>
        <type>Email</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_FirstSalesDate__c.field-meta.xml
<CustomField>
        <fullName>RICSC_FirstSalesDate__c</fullName>
        <description>Date that client made first purchase</description>
        <label>First Sales Date</label>
        <type>Date</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_Maison__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Maison__c</fullName>
        <description>List of Maisons</description>
        <label>Account Maison</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Maison</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_NotToBeGrouped__c.field-meta.xml
<CustomField>
        <fullName>RICSC_NotToBeGrouped__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to avoid the Account record to be merged with others in any case</description>
        <label>Not To Be Grouped</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Product2/fields/RICSC_Maison__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Maison__c</fullName>
        <description>Maison in which the product exist</description>
        <label>Maison</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Maison</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Product2/fields/RICSC_TechnicalProductType__c.field-meta.xml
<CustomField>
        <fullName>RICSC_TechnicalProductType__c</fullName>
        <label>Technical Product Type</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Activity__c/RICSC_Activity__c.object-meta.xml
<CustomObject>
    <description>Activity object is used to collect the interaction between Sales assistant and the customers.</description>
    <label>Activity</label>
    <nameField>
        <label>Activity Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RICSC_Activity__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Direct lookup to an account  from  which the activity originated - Release 1 SC</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>RICSC_ActivitiesAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Activity__c/fields/RICSC_Maison__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Maison__c</fullName>
        <description>List of Maisons to be able to drive</description>
        <label>Maison</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Maison</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Address__c/RICSC_Address__c.object-meta.xml
<CustomObject>
    <description>This object is used to collect  the Addresses of the related Local records.</description>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Address__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to Account (Contact)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>RICSC_AddressesAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Address__c/fields/RICSC_Address__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Address__c</fullName>
        <description>Field to capture the full address</description>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Email__c/RICSC_Email__c.object-meta.xml
<CustomObject>
    <description>This object is used to collect  the Emails of the related Local records.</description>
    <label>Email</label>
    <nameField>
        <displayFormat>E-{000000000}</displayFormat>
        <label>Email</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to the Account (contact)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Emails</relationshipLabel>
        <relationshipName>RICSC_EmailsAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_Email__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Email__c</fullName>
        <description>Standard email type field</description>
        <label>Email</label>
        <length>80</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Phone__c/RICSC_Phone__c.object-meta.xml
<CustomObject>
    <description>This object is used to collect  the Phones of the related Local records.</description>
    <label>Phone</label>
    <nameField>
        <displayFormat>P-{000000000}</displayFormat>
        <label>Phone</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Phones</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Phone__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to Account (Contact)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Phones</relationshipLabel>
        <relationshipName>RICSC_PhonesAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Phone__c/fields/RICSC_Maison__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Maison__c</fullName>
        <description>List of Maisons to be able to drive</description>
        <label>Maison</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Maison</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Phone__c/fields/RICSC_Phone__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Phone__c</fullName>
        <description>Standard phone field</description>
        <label>Phone</label>
        <type>Phone</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_SocialMediaID__c/RICSC_SocialMediaID__c.object-meta.xml
<CustomObject>
    <description>This object is used to collect  the Social ID of the related Local records.</description>
    <label>Social Media ID</label>
    <nameField>
        <displayFormat>S-{000000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Social Media IDs</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_SocialMediaID__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to Account (Contact)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Social Media IDs</relationshipLabel>
        <relationshipName>RICSC_SocialMediaIDsAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/RICSC_Transaction__c.object-meta.xml
<CustomObject>
    <description>capture transaction information.</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{000000000}</displayFormat>
        <label>Transaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to an Account - Release 1 SC</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>RICSC_TransactionsAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_Maison__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Maison__c</fullName>
        <description>List of Maisons</description>
        <label>Maison</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Maison</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Wishlist__c/RICSC_Wishlist__c.object-meta.xml
<CustomObject>
    <label>Wishlist</label>
    <nameField>
        <displayFormat>Wishlist-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wishlists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RICSC_Wishlist__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to an Account - Release 1 SC</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Wishlists</relationshipLabel>
        <relationshipName>RICSC_WishlistsAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/globalValueSets/RICSC_Maison.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cartier</fullName>
    </customValue>
    <customValue>
        <fullName>Jaeger Le Coultre</fullName>
    </customValue>
    <customValue>
        <fullName>Van Cleef &amp; Arpels</fullName>
    </customValue>
    <masterLabel>Maison</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/MergeExtension_TEST.cls
@isTest
public with sharing class MergeExtension_TEST {
    public MergeExtension_TEST() {
      makeData();
    }

    @TestSetup
    static void makeData(){
      UtilityTests.testSetup();
      Account masterRecord = new Account(FirstName = 'Golden', LastName = 'Account', RICSC_Maison__c = 'Cartier', RICSC_FirstSalesDate__c = Date.today(), RICSC_ConsentTimestamp__c = Datetime.now(), RICSC_CanBeContacted__c = true, RICSC_ClientSegment__c = 'TestClientSegment',RecordTypeId = RecordTypeHelper.getRTId('Account', 'RICSC_Cartier'));
      Database.insert(masterRecord);
      List<Account> mergedRecordList = new List<Account>();
      for(Integer i=0; i<4; i++){
        Account a = new Account(FirstName = 'Test', LastName = '00'+String.valueOf(i), RICSC_Maison__c = 'Cartier', RICSC_FirstSalesDate__c = Date.today(), RICSC_ConsentTimestamp__c = Datetime.now().addMonths(-1), RICSC_CanBeContacted__c = false, RICSC_ClientSegment__c = 'TestClientSegment',RecordTypeId = RecordTypeHelper.getRTId('Account', 'RICSC_Cartier'));
        if(i==3){
          a.RICSC_NotToBeGrouped__c = true;
        }
        mergedRecordList.add(a);
      }
      Database.insert(mergedRecordList);
      List<RICSC_Email__c> emailsList = new List<RICSC_Email__c>();
      List<RICSC_SocialMediaID__c> smIDList = new List<RICSC_SocialMediaID__c>();
      List<RICSC_Phone__c> phonesList = new List<RICSC_Phone__c>();
      List<RICSC_Address__c> addressList = new List<RICSC_Address__c>();
      List<RICSC_Transaction__c> transactionsList = new List<RICSC_Transaction__c>();
      List<RICSC_Activity__c> activitiesList = new List<RICSC_Activity__c>();
      List<RICSC_Wishlist__c> wishlistsList = new List<RICSC_Wishlist__c>();
      RICSC_Email__c email = new RICSC_Email__c(RICSC_Account__c = masterRecord.Id);
      emailsList.add(email);
      RICSC_SocialMediaID__c smID = new RICSC_SocialMediaID__c(RICSC_Account__c = masterRecord.Id);
      smIDList.add(smId);
      RICSC_Phone__c phone = new RICSC_Phone__c(RICSC_Account__c = masterRecord.Id);
      phonesList.add(phone);
      RICSC_Address__c address = new RICSC_Address__c(RICSC_Account__c = masterRecord.Id);
      addressList.add(address);
      Product2 p = new Product2(Name = 'Test Product', RICSC_TechnicalProductType__c = 'Watches',RICSC_Maison__c='Cartier');
      insert p;
      RICSC_Transaction__c tr = new RICSC_Transaction__c(RICSC_Account__c = masterRecord.Id, RICSC_AmountWithTaxEUR__c = 10000, RICSC_ProductName__c = p.Id, RICSC_TransactionDate__c = Date.today(),RICSC_TransactionCategory__c=UtilityConstants.TRANSACTION_TYPE_SALES);
      transactionsList.add(tr);
      RICSC_Activity__c act = new RICSC_Activity__c(RICSC_Account__c = masterRecord.Id, Name = 'Activity test '+masterRecord.Name);
      activitiesList.add(act);
      RICSC_Wishlist__c wsh = new RICSC_Wishlist__c(RICSC_Account__c = masterRecord.Id);
      wishlistsList.add(wsh);
      for(Account a : mergedRecordList){
        email = new RICSC_Email__c(RICSC_Account__c = a.Id);
        emailsList.add(email);
        smID = new RICSC_SocialMediaID__c(RICSC_Account__c = a.Id);
        smIDList.add(smId);
        phone = new RICSC_Phone__c(RICSC_Account__c = a.Id);
        phonesList.add(phone);
        address = new RICSC_Address__c(RICSC_Account__c = a.Id);
        addressList.add(address);
        tr = new RICSC_Transaction__c(RICSC_Account__c = a.Id, RICSC_AmountWithTaxEUR__c = 60000, RICSC_ProductName__c = p.Id, RICSC_TransactionDate__c = Date.today(),RICSC_TransactionCategory__c=UtilityConstants.TRANSACTION_TYPE_SALES);
        transactionsList.add(tr);
        act = new RICSC_Activity__c(RICSC_Account__c = a.Id, Name = 'Activity test '+a.Name);
        activitiesList.add(act);
        wsh = new RICSC_Wishlist__c(RICSC_Account__c = a.Id);
        wishlistsList.add(wsh);
      }
      Database.insert(emailsList);
      Database.insert(smIDList);
      Database.insert(phonesList);
      Database.insert(addressList);
      Database.insert(transactionsList);
      Database.insert(activitiesList);
      Database.insert(wishlistsList);
    }

    @IsTest
    static void mergeTest(){
      Test.startTest();
      String query = Utility.getSOQLWithFieldsFilter('account', 'FirstName = \'Golden\' LIMIT 1', 'RICSC_MasterRecordScore__c', UtilityConstants.SOQLFieldsFilter.CREATABLE);
      SObject masterRecord = Database.query(query);
      query = Utility.getSOQLWithFieldsFilter('account', 'Name LIKE \'%Test%\'', 'RICSC_MasterRecordScore__c', UtilityConstants.SOQLFieldsFilter.CREATABLE);
      //Map<Id, Account> mergedRecordList = new Map<Id,Account>((List<Account>)Database.query(query));
      List<SObject> mergedRecordsList = Database.query(query);
      boolean exceptionThrown = false;
      try{
        MergeExtension.beforeMerge('001P', masterRecord, mergedRecordsList);
      }
      catch (dupcheck.dc3Exception.NoProcessException e){
        exceptionThrown = true;
      }
      System.assert(exceptionThrown, 'Exception not thrown');
      //UtilityAccount.goldenRecordManagement(masterRecord, mergedRecordList, null);
      Test.stopTest();
      masterRecord = [SELECT Id, RICSC_IsGoldenRecord__c, RICSC_HasLocalRecords__c, RICSC_GlobalSegment__c FROM Account WHERE Firstname = 'Golden' AND RICSC_HasLocalRecords__c = true LIMIT 1];
      List<Account> allAccounts = [SELECT Id, RICSC_CanBeContacted__c, RICSC_NotToBeGrouped__c FROM Account];
      System.debug('==> allAccounts: ' + allAccounts);
      Boolean canBeContacted = true;
      for(Account a : allAccounts){
        if(!a.RICSC_NotToBeGrouped__c && !a.RICSC_CanBeContacted__c){
          canBeContacted = false;
        }
      }
      System.assert((Boolean)masterRecord.get('RICSC_HasLocalRecords__c'), 'Master hasn\'t local records');
      System.assert((Boolean)masterRecord.get('RICSC_IsGoldenRecord__c'), 'Master isn\'t golden record');
      System.assert(masterRecord.get('RICSC_GlobalSegment__c') != null, 'GlobalSegment is null');
      Account notGroupedAcc = [SELECT Id, RICSC_IsGoldenRecord__c, RICSC_HasLocalRecords__c FROM Account WHERE RICSC_NotToBeGrouped__c = true];
      System.assert(!notGroupedAcc.RICSC_HasLocalRecords__c, 'Account not to be merged has been merged');
      System.assert(notGroupedAcc.RICSC_IsGoldenRecord__c, 'Account not to be merged has been merged');
      System.assert(canBeContacted, 'Error in consents propagation');
    }
}