unpackaged/main/default/objects/Account/fields/RICSC_CountryOfOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryOfOrigin__c</fullName>
        <description>Country where the record has been created. Used for the sharing rules (e.g. records created outside of China shouldn't be visible for the Chineese users) - Release 1 SC</description>
        <label>Account Country Of Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_Email__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Email__c</fullName>
        <description>email field to capture the email of the Boutique</description>
        <label>Email</label>
        <type>Email</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Golden Record</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RICSC_IsGoldenRecord__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.RICSC_NotToBeGrouped__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Accounts (Local Records)</relationshipLabel>
        <relationshipName>RICSC_AccountGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_GR__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GR__c</fullName>
        <description>Formula field showing golden record icon if a the record is a golden one</description>
        <formula>if( RICSC_IsGoldenRecord__c , IMAGE('/resource/GRIcon?','Image not found', 25,25),'' )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GR</label>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_HasLocalRecords__c.field-meta.xml
<CustomField>
        <fullName>RICSC_HasLocalRecords__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Local Records</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_IsGoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_IsGoldenRecord__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Golden Record</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_ReferenceSA__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ReferenceSA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is populated with the SF ID correspondent to the respective SAP SA coming from SAP as a consequence of a calculation</description>
        <label>Reference SA</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (Reference SA)</relationshipLabel>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_VIP__c.field-meta.xml
<CustomField>
        <fullName>RICSC_VIP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Client categorization based on perceived value</description>
        <label>VIP</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Contact/fields/RICSC_CountryOfOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryOfOrigin__c</fullName>
        <description>Country where the record has been created. Used for the sharing rules (e.g. records created outside of China shouldn't be visible for the Chineese users) - Release 1 SC</description>
        <label>Sales Associate Country Of Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Address__c/RICSC_Address__c.object-meta.xml
<CustomObject>
    <description>This object is used to collect  the Addresses of the related Local records.</description>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Address__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to Account (Contact)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>RICSC_AddressesAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Address__c/fields/RICSC_Address__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Address__c</fullName>
        <description>Field to capture the full address</description>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Address__c/fields/RICSC_GR__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to the golden record</description>
        <label>GR</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>RICSC_AddressesGR</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Email__c/RICSC_Email__c.object-meta.xml
<CustomObject>
    <description>This object is used to collect  the Emails of the related Local records.</description>
    <label>Email</label>
    <nameField>
        <displayFormat>E-{000000000}</displayFormat>
        <label>Email</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to the Account (contact)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Emails</relationshipLabel>
        <relationshipName>RICSC_EmailsAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_CountryofOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryofOrigin__c</fullName>
        <description>Picklist to capture the client's country of origin</description>
        <label>Country of Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_Email__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Email__c</fullName>
        <description>Standard email type field</description>
        <label>Email</label>
        <length>80</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_GR__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This lookup field links the email to the golden record</description>
        <label>GR</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Emails</relationshipLabel>
        <relationshipName>RICSC_EmailsGR</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_VIP__c.field-meta.xml
<CustomField>
        <fullName>RICSC_VIP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It identifies if the Record is VIP or not . It is recalculated at the GR record level based on Maisons' rules</description>
        <label>VIP</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Phone__c/RICSC_Phone__c.object-meta.xml
<CustomObject>
    <description>This object is used to collect  the Phones of the related Local records.</description>
    <label>Phone</label>
    <nameField>
        <displayFormat>P-{000000000}</displayFormat>
        <label>Phone</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Phones</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Phone__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to Account (Contact)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Phones</relationshipLabel>
        <relationshipName>RICSC_PhonesAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Phone__c/fields/RICSC_CountryofOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryofOrigin__c</fullName>
        <description>Country of origin of client</description>
        <label>Country of Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Phone__c/fields/RICSC_GR__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to the golden record</description>
        <label>GR</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Phones</relationshipLabel>
        <relationshipName>RICSC_PhonesGR</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Phone__c/fields/RICSC_Phone__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Phone__c</fullName>
        <description>Standard phone field</description>
        <label>Phone</label>
        <type>Phone</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_SocialMediaID__c/RICSC_SocialMediaID__c.object-meta.xml
<CustomObject>
    <description>This object is used to collect  the Social ID of the related Local records.</description>
    <label>Social Media ID</label>
    <nameField>
        <displayFormat>S-{000000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Social Media IDs</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_SocialMediaID__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to Account (Contact)</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Social Media IDs</relationshipLabel>
        <relationshipName>RICSC_SocialMediaIDsAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_SocialMediaID__c/fields/RICSC_GR__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to the golden record</description>
        <label>GR</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Social Media IDs</relationshipLabel>
        <relationshipName>RICSC_SocialMediaIDsGR</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/RICSC_Transaction__c.object-meta.xml
<CustomObject>
    <description>capture transaction information.</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{000000000}</displayFormat>
        <label>Transaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to an Account - Release 1 SC</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>RICSC_TransactionsAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_CountryOfOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryOfOrigin__c</fullName>
        <description>Country where the record has been created. Used for the sharing rules (e.g. records created outside of China shouldn't be visible for the Chineese users) - Release 1 SC</description>
        <label>Country Of Transaction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to a Golden Record which has been created for the Account - Release 1 SC</description>
        <label>Golden Record</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>RICSC_TransactionsGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_VIP__c.field-meta.xml
<CustomField>
        <fullName>RICSC_VIP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It identifies if the Record is VIP or not . It is recalculated at the GR record level based on Maisons' rules</description>
        <label>VIP</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/globalValueSets/RICSC_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Amer.Virgin Is.</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua/Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia-Herz.</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Islands</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/BatchVCASharing.cls
/******************************************************************************
 * @author       Silvan Sholla
 * @date         11/11/2019
 * @description  Batch apex sharing for the following objects based on the country
 *               Of origin of the reference SA
 *               Address,SocialMediaId,Email,Phone And Transaction
 ******************************************************************************/

public class BatchVCASharing implements
Database.Batchable < sObject >, Schedulable {
  public static final Integer MAX_SCOPE = 100;

  public Database.QueryLocator start(Database.BatchableContext bc) {
      return Database.getQueryLocator('SELECT Id, RICSC_ReferenceSA__r.RICSC_CountryOfOrigin__c,RICSC_VIP__c,RICSC_HasLocalRecords__c,RICSC_IsGoldenRecord__c ' +
          'FROM Account ' +
          'WHERE RecordTypeId = \'' + RecordTypeHelper.getRTId('Account', UtilityConstants.PERSON_ACCOUNT_VCA_RT) + '\' '
      );
  }

  public void execute(SchedulableContext sc) {
    BatchVCASharing b = new BatchVCASharing();
    Database.executeBatch(b, MAX_SCOPE);
  }

  public void execute(Database.BatchableContext bc, List < Account > scope) {
      try {
          vCARecordSharing(scope);
      } catch (Exception e) {
          UtilityLogger.logException(e, e.getMessage(), 'BatchAccountScrambler', 'execute');
      }
  }
  public void finish(Database.BatchableContext bc) {
  }

  private void vCARecordSharing(List < Account > listOfAccounts) {
      //all records per object
    Set < Id > setOfIdsOfAccounts = new Set < Id > ();
    for (Account acc: listOfAccounts) {
        setOfIdsOfAccounts.add(acc.Id);
    }

    String accessLvl = 'read';
    Map < String, Id > getGroupIdByDeveloperName = Utility.getGroupIdByDeveloperName();
    Map < String, String > getRoleByCountryName = Utility.getRoleByCountryName();

    //all records per object
    List < RICSC_Email__c > emailList = [SELECT Id, RICSC_Account__c, RICSC_GR__c FROM RICSC_Email__c WHERE RICSC_Account__c IN: setOfIdsOfAccounts OR RICSC_GR__c IN: setOfIdsOfAccounts];
    List < RICSC_SocialMediaID__c > socialMediaList = [SELECT Id, RICSC_Account__c, RICSC_GR__c FROM RICSC_SocialMediaID__c WHERE RICSC_Account__c IN: setOfIdsOfAccounts OR RICSC_GR__c IN: setOfIdsOfAccounts];
    List < RICSC_Phone__c > phoneList = [SELECT Id, RICSC_Account__c, RICSC_GR__c FROM RICSC_Phone__c WHERE RICSC_Account__c IN: setOfIdsOfAccounts OR RICSC_GR__c IN: setOfIdsOfAccounts];
    List < RICSC_Address__c > addressesList = [SELECT Id, RICSC_Account__c, RICSC_GR__c FROM RICSC_Address__c WHERE RICSC_Account__c IN: setOfIdsOfAccounts OR RICSC_GR__c IN: setOfIdsOfAccounts];
    List < RICSC_Transaction__c > transactionList = [SELECT Id, RICSC_Account__c, RICSC_CountryOfOrigin__c, RICSC_GoldenRecord__c FROM RICSC_Transaction__c WHERE RICSC_Account__c IN: setOfIdsOfAccounts OR RICSC_GoldenRecord__c IN: setOfIdsOfAccounts];

    //lists with the records that has to get sharing rules
    Set < SObject > sharingRecordsToBeAdded = new Set < SObject >();
    List < SObject > sharingRecordsToBeDeleted = new List < SObject >();

    //set of ids of rules that has to get deleted | Local Sharing Records
    Set < Id > emailShareRemoveList = new Set < Id > ();
    Set < Id > socialMediaShareRemoveList = new Set < Id > ();
    Set < Id > phoneShareRemoveList = new Set < Id > ();
    Set < Id > addressShareRemoveList = new Set < Id > ();
    Set < Id > transactionShareRemoveList = new Set < Id > ();

    //set of ids of rules that has to get deleted | Golden Sharing Records
    Set < Id > emailShareRemoveGoldenList = new Set < Id > ();
    Set < Id > socialMediaShareRemoveGoldenList = new Set < Id > ();
    Set < Id > phoneShareRemoveGoldenList = new Set < Id > ();
    Set < Id > addressShareRemoveGoldenList = new Set < Id > ();
    Set < Id > transactionShareRemoveGoldenList = new Set < Id > ();

    for (Account acc: listOfAccounts) {
        if (acc.RICSC_VIP__c == false) {
            if ((acc.RICSC_HasLocalRecords__c == false && acc.RICSC_IsGoldenRecord__c == true) ||
                (acc.RICSC_HasLocalRecords__c == false && acc.RICSC_IsGoldenRecord__c == false)) {
                emailShareRemoveList.addAll(SharingRuleTriggerHelper.sharingRulesRemovalsObject(emailList, acc, 'RICSC_GR__c'));
                socialMediaShareRemoveList.addAll(SharingRuleTriggerHelper.sharingRulesRemovalsObject(socialMediaList, acc, 'RICSC_GR__c'));
                phoneShareRemoveList.addAll(SharingRuleTriggerHelper.sharingRulesRemovalsObject(phoneList, acc, 'RICSC_GR__c'));
                addressShareRemoveList.addAll(SharingRuleTriggerHelper.sharingRulesRemovalsObject(addressesList, acc, 'RICSC_GR__c'));
                transactionShareRemoveList.addAll(SharingRuleTriggerHelper.sharingRulesRemovalsObject(transactionList, acc, 'RICSC_GoldenRecord__c'));
            } else {
                emailShareRemoveGoldenList.addAll(SharingRuleTriggerHelper.sharingRulesRemovalsObject(emailList, acc, 'RICSC_GR__c'));
                socialMediaShareRemoveGoldenList.addAll(SharingRuleTriggerHelper.sharingRulesRemovalsObject(socialMediaList, acc, 'RICSC_GR__c'));
                phoneShareRemoveGoldenList.addAll(SharingRuleTriggerHelper.sharingRulesRemovalsObject(phoneList, acc, 'RICSC_GR__c'));
                addressShareRemoveGoldenList.addAll(SharingRuleTriggerHelper.sharingRulesRemovalsObject(addressesList, acc, 'RICSC_GR__c'));
                transactionShareRemoveGoldenList.addAll(SharingRuleTriggerHelper.sharingRulesRemovalsObject(transactionList, acc, 'RICSC_GoldenRecord__c'));
            }
        } else if (acc.RICSC_VIP__c == true) {
            sharingRecordsToBeAdded.addAll(SharingRuleTriggerHelper.createSharingRulesObject(emailList, acc, accessLvl, acc.RICSC_ReferenceSA__r.RICSC_CountryOfOrigin__c, 'RICSC_Email__share', getGroupIdByDeveloperName, getRoleByCountryName));
            sharingRecordsToBeAdded.addAll(SharingRuleTriggerHelper.createSharingRulesObject(socialMediaList, acc, accessLvl, acc.RICSC_ReferenceSA__r.RICSC_CountryOfOrigin__c, 'RICSC_SocialMediaID__share', getGroupIdByDeveloperName, getRoleByCountryName));
            sharingRecordsToBeAdded.addAll(SharingRuleTriggerHelper.createSharingRulesObject(phoneList, acc, accessLvl, acc.RICSC_ReferenceSA__r.RICSC_CountryOfOrigin__c, 'RICSC_Phone__share', getGroupIdByDeveloperName, getRoleByCountryName));
            sharingRecordsToBeAdded.addAll(SharingRuleTriggerHelper.createSharingRulesObject(addressesList, acc, accessLvl, acc.RICSC_ReferenceSA__r.RICSC_CountryOfOrigin__c, 'RICSC_Address__share', getGroupIdByDeveloperName, getRoleByCountryName));
            sharingRecordsToBeAdded.addAll(SharingRuleTriggerHelper.createSharingRulesObject(transactionList, acc, accessLvl, acc.RICSC_ReferenceSA__r.RICSC_CountryOfOrigin__c, 'RICSC_Transaction__share', getGroupIdByDeveloperName, getRoleByCountryName));
        }
    }


    if (emailShareRemoveList.size() != 0) {
      sharingRecordsToBeDeleted.addAll([SELECT Id FROM RICSC_Email__share WHERE RowCause =: UtilityConstants.VCA_APEX_REASON_LOCAL_RECORD AND ParentId IN: emailShareRemoveList]);
    }
    if (socialMediaShareRemoveList.size() != 0) {
      sharingRecordsToBeDeleted.addAll([SELECT Id FROM RICSC_SocialMediaID__share WHERE RowCause =: UtilityConstants.VCA_APEX_REASON_LOCAL_RECORD AND ParentId IN: socialMediaShareRemoveList]);
    }
    if (phoneShareRemoveList.size() != 0) {
      sharingRecordsToBeDeleted.addAll([SELECT Id FROM RICSC_Phone__share WHERE RowCause =: UtilityConstants.VCA_APEX_REASON_LOCAL_RECORD AND ParentId IN: phoneShareRemoveList]);
    }
    if (addressShareRemoveList.size() != 0) {
      sharingRecordsToBeDeleted.addAll([SELECT Id FROM RICSC_Address__share WHERE RowCause =: UtilityConstants.VCA_APEX_REASON_LOCAL_RECORD AND ParentId IN: addressShareRemoveList]);
    }
    if (transactionShareRemoveList.size() != 0) {
      sharingRecordsToBeDeleted.addAll([SELECT Id FROM RICSC_Transaction__share WHERE RowCause =: UtilityConstants.VCA_APEX_REASON_LOCAL_RECORD AND ParentId IN: transactionShareRemoveList]);
    }
    if (emailShareRemoveGoldenList.size() != 0) {
      sharingRecordsToBeDeleted.addAll([SELECT Id FROM RICSC_Email__share WHERE RowCause =: UtilityConstants.VCA_APEX_REASON_GOLDEN_RECORD AND ParentId IN: emailShareRemoveGoldenList]);
    }
    if (socialMediaShareRemoveGoldenList.size() != 0) {
      sharingRecordsToBeDeleted.addAll([SELECT Id FROM RICSC_SocialMediaID__share WHERE RowCause =: UtilityConstants.VCA_APEX_REASON_GOLDEN_RECORD AND ParentId IN: socialMediaShareRemoveGoldenList]);
    }
    if (phoneShareRemoveGoldenList.size() != 0) {
      sharingRecordsToBeDeleted.addAll([SELECT Id FROM RICSC_Phone__share WHERE RowCause =: UtilityConstants.VCA_APEX_REASON_GOLDEN_RECORD AND ParentId IN: phoneShareRemoveGoldenList]);
    }
    if (addressShareRemoveGoldenList.size() != 0) {
      sharingRecordsToBeDeleted.addAll([SELECT Id FROM RICSC_Address__share WHERE RowCause =: UtilityConstants.VCA_APEX_REASON_GOLDEN_RECORD AND ParentId IN: addressShareRemoveGoldenList]);
    }
    if (transactionShareRemoveGoldenList.size() != 0) {
      sharingRecordsToBeDeleted.addAll([SELECT Id FROM RICSC_Transaction__share WHERE RowCause =: UtilityConstants.VCA_APEX_REASON_GOLDEN_RECORD AND ParentId IN: transactionShareRemoveGoldenList]);
    }

    List<sObject> listToBeUpdated = new List<sObject>(sharingRecordsToBeAdded);
    Database.SaveResult[] srUpdateList = Database.insert(listToBeUpdated,false);
    UtilityLogger.logAllErrors(srUpdateList, false, 'BatchVCASharing','execute');
    Database.DeleteResult[] drList = Database.delete(sharingRecordsToBeDeleted,false);
    UtilityLogger.logAllErrors(drList, true, 'BatchVCASharing','execute');
  }
}