unpackaged/main/default/objects/Account/fields/RICSC_CountryOfOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryOfOrigin__c</fullName>
        <description>Country where the record has been created. Used for the sharing rules (e.g. records created outside of China shouldn't be visible for the Chineese users) - Release 1 SC</description>
        <label>Account Country Of Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_Email__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Email__c</fullName>
        <description>email field to capture the email of the Boutique</description>
        <label>Email</label>
        <type>Email</type>
    </CustomField>

unpackaged/main/default/objects/Asset/fields/RICSC_CountryOfOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryOfOrigin__c</fullName>
        <description>Country where the record has been created. Used for the sharing rules (e.g. records created outside of China shouldn't be visible for the Chineese users) - Release 1 SC</description>
        <label>Country Of Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Contact/fields/RICSC_CountryOfOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryOfOrigin__c</fullName>
        <description>Country where the record has been created. Used for the sharing rules (e.g. records created outside of China shouldn't be visible for the Chineese users) - Release 1 SC</description>
        <label>Sales Associate Country Of Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </RecordType>

unpackaged/main/default/objects/GeneralSettings__c/GeneralSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom Setting used to store general system settings</description>
    <label>General Settings</label>
</CustomObject>

unpackaged/main/default/objects/GeneralSettings__c/fields/GroupId_AllInternalUsers__c.field-meta.xml
<CustomField>
        <fullName>GroupId_AllInternalUsers__c</fullName>
        <description>The Id of public group with developerName AllInternalUsers</description>
        <inlineHelpText>Set the 18 digit version of ID for group with developerName AllInternalUsers</inlineHelpText>
        <label>GroupId AllInternalUsers</label>
        <length>18</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/GeneralSettings__c/fields/Logger_DebugEnabled__c.field-meta.xml
<CustomField>
        <fullName>Logger_DebugEnabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If true enables storing of Debug Application Log records</description>
        <label>Logger Debug Enabled</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/GeneralSettings__c/fields/Logger_ExceptionEnabled__c.field-meta.xml
<CustomField>
        <fullName>Logger_ExceptionEnabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If true enables storing of Exception Application Log records</description>
        <label>Logger Exception Enabled</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/GeneralSettings__c/fields/RICSC_ProductPortfolioIntegrationDate__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ProductPortfolioIntegrationDate__c</fullName>
        <description>its used in a batch to retrieve  transactions that are used in the propagation with the product portfolio object</description>
        <label>Product Portfolio Integration From Date</label>
        <type>Date</type>
    </CustomField>

unpackaged/main/default/objects/GeneralSettings__c/fields/RICSC_RunConsentsAlignmentAfterDCJob__c.field-meta.xml
<CustomField>
        <fullName>RICSC_RunConsentsAlignmentAfterDCJob__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Run consents alignment after DC job</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/GeneralSettings__c/fields/RICSC_RunSegmentationAfterDCJob__c.field-meta.xml
<CustomField>
        <fullName>RICSC_RunSegmentationAfterDCJob__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Run segmentation after DC job</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/GeneralSettings__c/fields/RICSC_VCACRMNonChinaPublicGroupNoMembers__c.field-meta.xml
<CustomField>
        <fullName>RICSC_VCACRMNonChinaPublicGroupNoMembers__c</fullName>
        <description>VCA Roles that doesnt belong on the VCACRMNonChinaRoles Public Group</description>
        <label>VCACRMNonChinaPublicGroupNoMembers</label>
        <type>TextArea</type>
    </CustomField>

unpackaged/main/default/objects/GeneralSettings__c/fields/Scope__c.field-meta.xml
<CustomField>
        <fullName>Scope__c</fullName>
        <description>The scope used by the system to control deviation from global framework. If not necessary just use -All- value</description>
        <label>Scope</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Activity__c/RICSC_Activity__c.object-meta.xml
<CustomObject>
    <description>Activity object is used to collect the interaction between Sales assistant and the customers.</description>
    <label>Activity</label>
    <nameField>
        <label>Activity Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RICSC_Activity__c/fields/RICSC_CountryofOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryofOrigin__c</fullName>
        <description>Country where the record has been created. Used for the sharing rules (e.g. records created outside of China shouldn't be visible for the Chineese users) - Release 1 SC</description>
        <label>Country of Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Email__c/RICSC_Email__c.object-meta.xml
<CustomObject>
    <description>This object is used to collect  the Emails of the related Local records.</description>
    <label>Email</label>
    <nameField>
        <displayFormat>E-{000000000}</displayFormat>
        <label>Email</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_CountryofOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryofOrigin__c</fullName>
        <description>Picklist to capture the client's country of origin</description>
        <label>Country of Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Email__c/fields/RICSC_Email__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Email__c</fullName>
        <description>Standard email type field</description>
        <label>Email</label>
        <length>80</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Phone__c/RICSC_Phone__c.object-meta.xml
<CustomObject>
    <description>This object is used to collect  the Phones of the related Local records.</description>
    <label>Phone</label>
    <nameField>
        <displayFormat>P-{000000000}</displayFormat>
        <label>Phone</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Phones</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Phone__c/fields/RICSC_CountryofOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryofOrigin__c</fullName>
        <description>Country of origin of client</description>
        <label>Country of Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Relation__c/RICSC_Relation__c.object-meta.xml
<CustomObject>
    <description>Relation object is used to track the relations between 2 Customers (e.g. father, husband etc)</description>
    <label>Relationship</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Relationship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RICSC_Relation__c/fields/RICSC_CountryofOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryofOrigin__c</fullName>
        <description>Country where the record has been created. Used for the sharing rules (e.g. records created outside of China shouldn't be visible for the Chineese users) - Release 1 SC</description>
        <label>Country of Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/TRG_TriggerSettings__c/TRG_TriggerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom setting used to enable or disable all triggers/specific triggers for a given user/profile</description>
    <label>Trigger Settings</label>
</CustomObject>

unpackaged/main/default/objects/TRG_TriggerSettings__c/fields/CheckEnabledOnLeanLoad__c.field-meta.xml
<CustomField>
        <fullName>CheckEnabledOnLeanLoad__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CheckEnabledOnLeanLoad</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/TRG_TriggerSettings__c/fields/DisableAllProcessBuilders__c.field-meta.xml
<CustomField>
        <fullName>DisableAllProcessBuilders__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If true, all process builders managed by the Trigger Framework are skipped for all objects</description>
        <inlineHelpText>if true, all process builders managed by the Trigger Framework are skipped for all objects</inlineHelpText>
        <label>DisableAllProcessBuilders</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/TRG_TriggerSettings__c/fields/DisableAllTriggers__c.field-meta.xml
<CustomField>
        <fullName>DisableAllTriggers__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If true, all triggers managed by the Trigger Framework are skipped for all objects</description>
        <inlineHelpText>If true, all triggers managed by the Trigger Framework are skipped for all objects</inlineHelpText>
        <label>DisableAllTriggers</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/TRG_TriggerSettings__c/fields/DisableAllWorkflows__c.field-meta.xml
<CustomField>
        <fullName>DisableAllWorkflows__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If true, all workflows managed by the Trigger Framework are skipped for all objects</description>
        <inlineHelpText>If true, all workflows managed by the Trigger Framework are skipped for all objects</inlineHelpText>
        <label>DisableAllWorkflows</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/TRG_TriggerSettings__c/fields/DisableTriggerMethods__c.field-meta.xml
<CustomField>
        <fullName>DisableTriggerMethods__c</fullName>
        <description>List of newline separated fully specified class names of classes extending TriggerHandlerInterface to skip during execution</description>
        <inlineHelpText>List of newline separated fully specified class names of classes extending TriggerHandlerInterface to skip during execution</inlineHelpText>
        <label>DisableTriggerMethods</label>
        <type>TextArea</type>
    </CustomField>

unpackaged/main/default/objects/TRG_TriggerSettings__c/fields/DisableTriggerObjects__c.field-meta.xml
<CustomField>
        <fullName>DisableTriggerObjects__c</fullName>
        <description>List of newline separated fully specified object names to skip during trigger execution</description>
        <inlineHelpText>List of newline separated fully specified object names to skip during trigger execution</inlineHelpText>
        <label>DisableTriggerObjects</label>
        <type>TextArea</type>
    </CustomField>

unpackaged/main/default/objects/TRG_TriggerSettings__c/fields/PrintLimitsInDebug__c.field-meta.xml
<CustomField>
        <fullName>PrintLimitsInDebug__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If true, print limits in debug</description>
        <inlineHelpText>If true, print limits in debug</inlineHelpText>
        <label>PrintLimitsInDebug</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/globalValueSets/RICSC_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Amer.Virgin Is.</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua/Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia-Herz.</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Islands</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/UtilityTests.cls
/****************************************************************************************************************************
* @author       Piergiorgio Lisanti
* @date         26/Aug/2019
* @description  General Utility class for TESTS
*****************************************************************************************************************************/
@SuppressWarnings('PMD.ApexCRUDViolation')
public without sharing class UtilityTests {

    @TestVisible
    private static void testSetup(){

        setupGeneralSettings();
        setupTriggerSettings();

    }


    private static void setupGeneralSettings(){

        GeneralSettings__c generalSetting = GeneralSettings__c.getOrgDefaults();

        //**Attention: Change scope accroding to the organization**//
        Boolean isProd = ([SELECT Id, IsSandbox FROM Organization LIMIT 1].IsSandbox == false);
        String scopeStr = isProd ? UtilityConstants.FunctionalScopes.PRD.name() : UtilityConstants.FunctionalScopes.SBX.name();
        generalSetting.Scope__c = scopeStr;
        generalSetting.RICSC_ProductPortfolioIntegrationDate__c = Date.newInstance(2014, 9, 9);
        generalSetting.Logger_DebugEnabled__c = true;
        generalSetting.Logger_ExceptionEnabled__c = true;
        generalSetting.RICSC_RunSegmentationAfterDCJob__c = true;
        generalSetting.RICSC_RunConsentsAlignmentAfterDCJob__c = true;
        generalSetting.RICSC_VCACRMNonChinaPublicGroupNoMembers__c = 'RICSC_VCACRMAmericasRegion,RICSC_VCACRMAsiaPacificRegion,RICSC_VCACRMEuropeCIS,RICSC_VCACRMFranceRegion,RICSC_VCACRMHongKongMacao,RICSC_VCACRMHQ,RICSC_VCACRMMiddleEastRegion,RICSC_VCACRMSouthEastAsiaAustralia,RICSC_VCACRMWorld,RICSC_VCACRMChina';

        for(Group g : [Select Id,DeveloperName From Group where DeveloperName = 'AllInternalUsers' limit 1]){

            if(g.developerName == 'AllInternalUsers'){

                generalSetting.GroupId_AllInternalUsers__c  = g.Id;

            }
        }

        upsert generalSetting  GeneralSettings__c.Id;
    }

    private static void setupTriggerSettings(){

        TRG_TriggerSettings__c triggerSetting = TRG_TriggerSettings__c.getOrgDefaults();

        triggerSetting.DisableAllProcessBuilders__c = false;
        triggerSetting.DisableAllTriggers__c = false;
        triggerSetting.DisableAllWorkflows__c = false;
        triggerSetting.CheckEnabledOnLeanLoad__c = false;
        triggerSetting.PrintLimitsInDebug__c = true;
        triggerSetting.DisableTriggerMethods__c = '';
        triggerSetting.DisableTriggerObjects__c = '';

        upsert triggerSetting  TRG_TriggerSettings__c.Id;
    }

    @TestVisible
    private static User getUser(String profileName){

        return new User(
                LastName            = 'PREFIX' + System.now().millisecond(),
                Email               = 'PREFIX'+ System.now().millisecond() +'@test.com',
                Username            = 'PREFIX'+ string.valueOf(Crypto.getRandomInteger()) +'@test.com',
                Alias               = 'alias' + System.now().millisecond(),
                ProfileId           =  profileMap.get(profileName).Id,
                LocaleSidKey        = 'en_TZ',
                EmailEncodingKey    = 'ISO-8859-1',
                TimeZoneSidKey      = 'GMT',
                LanguageLocaleKey   = 'en_US'
                );
    }

    private static Map<String,Profile> profileMap {

        get {

            if(profileMap == null){

                profileMap = new Map<String,Profile>();

                for(Profile p : [SELECT Id, Name FROM Profile]){
                    profileMap.put(p.Name, p);
                }
            }

            return profileMap;

        }
        private set;

    }

    @TestVisible
    private static Account getAccount(){
      return new Account(
        Name = 'Account_' + System.now().millisecond()
      );
    }

    @TestVisible
    private static List<Account> getAccounts(integer size){
        List<Account> accounts = new List<Account>();
        for(Integer i=0; i<size; i++){ accounts.add(getAccount()); }
        return accounts;
    }

    @TestVisible
    private static Account getPersonAccount(){
      return getPersonAccount(UtilityConstants.PERSON_ACCOUNT_VCA_RT);
    }

    @TestVisible
    private static List<Account> getPersonAccounts(integer size){
        List<Account> accounts = new List<Account>();
        for(Integer i=0; i<size; i++){ accounts.add(getAccount()); }
        return accounts;
    }

    @TestVisible
    private static Account getPersonAccount(String rtDevName){
      return new Account(
        LastName = 'Account_' + System.now().millisecond(),
        RecordTypeId = RecordTypeHelper.getRTId('Account', rtDevName)
      );
    }

    @TestVisible
    private static Contact getContact(){
      return new Contact(
        LastName  = 'Contact_' + System.now().millisecond()
      );
    }

    @TestVisible
    private static List<Contact> getContacts(integer size){
        List<Contact> contacts = new List<Contact>();
        for(Integer i=0; i<size; i++){ contacts.add(getContact()); }
        return contacts;
    }

    @TestVisible
    private static RICSC_Email__c getEmail(){
      return new RICSC_Email__c(
      );
    }

    @TestVisible
    private static List<RICSC_Email__c> getEmails(integer size){
        List<RICSC_Email__c> emails = new List<RICSC_Email__c>();
        for(Integer i=0; i<size; i++){ emails.add(getEmail()); }
        return emails;
    }

    @TestVisible
    private static RICSC_Transaction__c getTransaction(){
      return new RICSC_Transaction__c(
        RICSC_CountryOfOrigin__c = 'France'
      );
    }

    @TestVisible
    private static Product2 getProduct(){
      return new Product2();
    }

    @TestVisible
    private static List<Product2> getProducts(integer size){
        List<Product2> products = new List<Product2>();
        for(Integer i=0; i<size; i++){ products.add(getProduct()); }
        return products;
    }

    @TestVisible
    private static RICSC_Wishlist__c getWishlist(){
      return new RICSC_Wishlist__c();
    }

    @TestVisible
    private static RICSC_Relation__c getRelation(){
      return new RICSC_Relation__c();
    }

    @TestVisible
    private static RICSC_Activity__c getActivity(){
      return new RICSC_Activity__c();
    }

    @TestVisible
    private static List<RICSC_Wishlist__c> getWishlists(integer size){
        List<RICSC_Wishlist__c> wishlists = new List<RICSC_Wishlist__c>();
        for(Integer i=0; i<size; i++){ wishlists.add(getWishlist()); }
        return wishlists;
    }


    @TestVisible
    private static Asset getAsset(){
      return new Asset();
    }

    @TestVisible
    private static List<Asset> getAssets(integer size){
        List<Asset> assets = new List<Asset>();
        for(Integer i=0; i<size; i++){ assets.add(getAsset()); }
        return assets;
    }

    @TestVisible
    private static List<RICSC_Transaction__c> getTransactions(integer size){
        List<RICSC_Transaction__c> transactions = new List<RICSC_Transaction__c>();
        for(Integer i=0; i<size; i++){ transactions.add(getTransaction()); }
        return transactions;
    }

    @TestVisible
    private static Account getBoutique(){
      return new Account(
        Name  = 'Boutique_' + System.now().millisecond(),
        RecordTypeId = RecordTypeHelper.getRTID('Account',UtilityConstants.ACCOUNTBOUTIQUE_RT)
      );
    }

    @TestVisible
    private static List<Account> getBoutiques(integer size){
        List<Account> boutiques = new List<Account>();
        for(Integer i=0; i<size; i++){ boutiques.add(getBoutique()); }
        return boutiques;
    }

    @TestVisible
    private static RICSC_SocialMediaID__c getSocialMediaID(){
      return new RICSC_SocialMediaID__c(
      );
    }

    @TestVisible
    private static List<RICSC_SocialMediaID__c> getSocialMediaIDs(integer size){
        List<RICSC_SocialMediaID__c> socialMediaIDs = new List<RICSC_SocialMediaID__c>();
        for(Integer i=0; i<size; i++){ SocialMediaIDs.add(getSocialMediaID()); }
        return SocialMediaIDs;
    }

    @TestVisible
    private static RICSC_Address__c getAddress(){
      return new RICSC_Address__c(
      );
    }

    @TestVisible
    private static List<RICSC_Address__c> getAddresses(integer size){
        List<RICSC_Address__c> addresss = new List<RICSC_Address__c>();
        for(Integer i=0; i<size; i++){ Addresss.add(getAddress()); }
        return Addresss;
    }

    @TestVisible
    private static RICSC_Phone__c getPhone(){
      return new RICSC_Phone__c(
      );
    }

    @TestVisible
    private static List<RICSC_Phone__c> getPhones(integer size){
        List<RICSC_Phone__c> phones = new List<RICSC_Phone__c>();
        for(Integer i=0; i<size; i++){ Phones.add(getPhone()); }
        return Phones;
    }

    @TestVisible
    private static PermissionSet getPermSet(String permSetName){
        return permSetMap.get(permSetName);
    }

    private static Map<String,PermissionSet> permSetMap {
        get {
            if(permSetMap == null){
                permSetMap = new Map<String,PermissionSet>();
                for(PermissionSet ps : [SELECT Id, Name FROM PermissionSet]){
                    permSetMap.put(ps.Name, ps);
                }
            }
            return permSetMap;
        }
        private set;
}

}