unpackaged/main/default/objects/Account/fields/RICSC_ClassCode__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ClassCode__c</fullName>
        <description>Client segment based on rules in SAP</description>
        <label>Class Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Boutique Client</fullName>
                </value>
                <value>
                    <fullName>Boutique Service client</fullName>
                </value>
                <value>
                    <fullName>Cartier Call Center Prospect</fullName>
                </value>
                <value>
                    <fullName>Cartier Customer Service</fullName>
                </value>
                <value>
                    <fullName>Cartier Prospect</fullName>
                </value>
                <value>
                    <fullName>Cartier Prospect Multichannel</fullName>
                </value>
                <value>
                    <fullName>Cartier Retail</fullName>
                </value>
                <value>
                    <fullName>Cartier Retail Mutlichannel Customer</fullName>
                </value>
                <value>
                    <fullName>Cartier Retail Web Customer</fullName>
                </value>
                <value>
                    <fullName>Charity</fullName>
                </value>
                <value>
                    <fullName>Charity Client</fullName>
                </value>
                <value>
                    <fullName>Contact Center Client</fullName>
                </value>
                <value>
                    <fullName>Contact Center Retail Client</fullName>
                </value>
                <value>
                    <fullName>Contact Center Service Client</fullName>
                </value>
                <value>
                    <fullName>Customer Service Client</fullName>
                </value>
                <value>
                    <fullName>E-Commerce Client</fullName>
                </value>
                <value>
                    <fullName>Multi-Channel Client</fullName>
                </value>
                <value>
                    <fullName>Multi-channel Retail Client</fullName>
                </value>
                <value>
                    <fullName>Multi-channel Service Client</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Prospect Boutique</fullName>
                </value>
                <value>
                    <fullName>Prospect contact center</fullName>
                </value>
                <value>
                    <fullName>Prospect Partnership</fullName>
                </value>
                <value>
                    <fullName>Prospect Web</fullName>
                </value>
                <value>
                    <fullName>Prospect Web Cartier</fullName>
                </value>
                <value>
                    <fullName>Staff</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>Web Client</fullName>
                </value>
                <value>
                    <fullName>Web Retail Client</fullName>
                </value>
                <value>
                    <fullName>Wholesaler</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Golden Record</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RICSC_IsGoldenRecord__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.RICSC_NotToBeGrouped__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Accounts (Local Records)</relationshipLabel>
        <relationshipName>RICSC_AccountGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_TotalNumberOfRepairs__c.field-meta.xml
<CustomField>
        <fullName>RICSC_TotalNumberOfRepairs__c</fullName>
        <description>Calculated number field of all the repairs (of all products)</description>
        <label>Total Number Of Repairs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_TotalNumberOfSales__c.field-meta.xml
<CustomField>
        <fullName>RICSC_TotalNumberOfSales__c</fullName>
        <description>Calculated number field of all sales transactions</description>
        <label>Total Number Of Sales</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_TransactionChannelsSelected__c.field-meta.xml
<CustomField>
        <fullName>RICSC_TransactionChannelsSelected__c</fullName>
        <description>channels that were selected from the related transactions</description>
        <label>Transaction Channels Selected</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Boutique</fullName>
                </value>
                <value>
                    <fullName>CC</fullName>
                </value>
                <value>
                    <fullName>Charity</fullName>
                </value>
                <value>
                    <fullName>Web</fullName>
                </value>
                <value>
                    <fullName>WeChat</fullName>
                    <isActive>false</isActive>
                    <label>WeChat</label>
                </value>
                <value>
                    <fullName>Wholesaler</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Asset/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to a Golden Record which has been created for the Account - Release 1 SC</description>
        <label>Golden Record</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Product Portfolios</relationshipLabel>
        <relationshipName>RICSC_AssetsGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Asset/fields/RICSC_TransactionID__c.field-meta.xml
<CustomField>
        <fullName>RICSC_TransactionID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction ID</label>
        <referenceTo>RICSC_Transaction__c</referenceTo>
        <relationshipLabel>Product Portfolios</relationshipLabel>
        <relationshipName>RICSC_AssetsTransaction</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Case/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to a Golden Record which has been created for the Account</description>
        <label>Golden Record</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>RICSC_TicketsGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/classes/ProductPortfolioTriggerHandler.cls
/******************************************************************************
@author Silvan Sholla
@date 25/Nov/2019
@description This is a container of all trigger classes on Asset object used within the trigger framework.
******************************************************************************/

public with sharing class ProductPortfolioTriggerHandler {
    public without sharing class ClassCodeCalculation implements TRG_TriggerHandlerInterface {
    public void runTriggerHandler(TRG_TriggerDispatcher.TriggerData td) {

      Set<Id> involvedAccounts = new Set<Id>();

      if(td.isInsert || td.isUpdate){
        for(Asset ast : (List<Asset>) td.newList){
          if(ast.RICSC_GoldenRecord__c != null){
            involvedAccounts.add(ast.RICSC_GoldenRecord__c);
          }
        }
      }

      if(td.isDelete){
        for(Asset ast : (List<Asset>) td.oldList){
          if(ast.RICSC_GoldenRecord__c != null){
            involvedAccounts.add(ast.RICSC_GoldenRecord__c);
          }
        }
      }

      if(involvedAccounts.size() > 0){
        List<Account> involvedAccountList = [SELECT Id,RICSC_TransactionChannelsSelected__c,RICSC_ClassCode__c,RICSC_TotalNumberOfSales__c,RICSC_TotalNumberOfRepairs__c,(SELECT id,RICSC_TransactionID__c  FROM RICSC_AssetsGoldenRecord__r) FROM Account WHERE Id IN :involvedAccounts];
        List<Account> accountsToBeUpdated = new List<Account>();
        for(Account acc :involvedAccountList){
          Boolean hasAllAssetsWS = true;
          if(acc.getSObjects('RICSC_AssetsGoldenRecord__r') != null){
            for(Asset ast :(List<Asset>)acc.getSObjects('RICSC_AssetsGoldenRecord__r')){
              if(ast.RICSC_TransactionID__c != null){
                hasAllAssetsWS = false;
                break;
              }
            }
            if(hasAllAssetsWS){
              Account updatedAccount = new Account();
              updatedAccount.put('Id', acc.Id);
              updatedAccount.put('RICSC_ClassCode__c', UtilityConstants.CLASS_CODE_WHLSL);
              accountsToBeUpdated.add(updatedAccount);
            }
          }
        }
        update accountsToBeUpdated;
      }
    }
  }

  /******************************************************************************
  @author Silvan Sholla
  @date 25/Nov/2019
  @description propagate golden record lookup of asset based the accounts
               golden record : in case its populated on the account , then
               the golden record is filled with accounts golden record otherwise
               its getting filled with the local account id
  ******************************************************************************/
  public without sharing class GoldenRecordLookUpPopulate implements TRG_TriggerHandlerInterface {
    public void runTriggerHandler(TRG_TriggerDispatcher.TriggerData td) {
      UtilityAccount.goldenRecordLookUpPopulate('Assets','AccountId','RICSC_GoldenRecord__c','ProductPortfolioTriggerHandler',td.newList);
    }
  }


  /******************************************************************************
  @author Silvan Sholla
  @date 13/Jan/2020
  @description duplication of product portfolios check
               the PP being inserted from integration is allowed but then any
               existing with same serial Number is being deleted
  ******************************************************************************/
  public without sharing class DuplicateCheck implements TRG_TriggerHandlerInterface {
    public void runTriggerHandler(TRG_TriggerDispatcher.TriggerData td) {
      Map<String,Asset> serialNumberAssetMap = new Map<String,Asset>();
      for(Asset ast : (List<Asset>) td.newList){
        if(ast.SerialNumber != null){
          serialNumberAssetMap.put(ast.SerialNumber,ast);
        }
      }
      ProductPortfolioIntegration.duplicateCheckOverSerialNumber(serialNumberAssetMap);
    }
  }
}