unpackaged/main/default/objects/Account/fields/RICSC_CountryOfOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryOfOrigin__c</fullName>
        <description>Country where the record has been created. Used for the sharing rules (e.g. records created outside of China shouldn't be visible for the Chineese users) - Release 1 SC</description>
        <label>Account Country Of Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_ExtCreationDate__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ExtCreationDate__c</fullName>
        <description>Date and Time of the record creation in the source system</description>
        <label>Ext Creation Date</label>
        <type>Date</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Golden Record</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RICSC_IsGoldenRecord__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.RICSC_NotToBeGrouped__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Accounts (Local Records)</relationshipLabel>
        <relationshipName>RICSC_AccountGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Account/fields/RICSC_Maison__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Maison__c</fullName>
        <description>List of Maisons</description>
        <label>Account Maison</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Maison</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Asset/fields/RICSC_AmountWithTax__c.field-meta.xml
<CustomField>
        <fullName>RICSC_AmountWithTax__c</fullName>
        <description>Total amount of the transaction coming from the source system</description>
        <label>Amount With Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </CustomField>

unpackaged/main/default/objects/Asset/fields/RICSC_Boutique__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Boutique__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the Boutique</description>
        <label>Boutique</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Product Portfolios (Boutique)</relationshipLabel>
        <relationshipName>RICSC_AssetsBoutique</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Asset/fields/RICSC_CountryOfOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryOfOrigin__c</fullName>
        <description>Country where the record has been created. Used for the sharing rules (e.g. records created outside of China shouldn't be visible for the Chineese users) - Release 1 SC</description>
        <label>Country Of Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Asset/fields/RICSC_ExtCreationDate__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ExtCreationDate__c</fullName>
        <description>Date and Time of the record creation in the source system</description>
        <label>Ext Creation Date</label>
        <type>Date</type>
    </CustomField>

unpackaged/main/default/objects/Asset/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to a Golden Record which has been created for the Account - Release 1 SC</description>
        <label>Golden Record</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Product Portfolios</relationshipLabel>
        <relationshipName>RICSC_AssetsGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Asset/fields/RICSC_Maison__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Maison__c</fullName>
        <description>List of Maisons</description>
        <label>Maison</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Maison</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Asset/fields/RICSC_SalesAssociate__c.field-meta.xml
<CustomField>
        <fullName>RICSC_SalesAssociate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the Sales Associate</description>
        <label>Sales Associate</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Product Portfolios</relationshipLabel>
        <relationshipName>RICSC_ProductPortfoliosSalesAssociate</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Asset/fields/RICSC_TransactionNumber__c.field-meta.xml
<CustomField>
        <fullName>RICSC_TransactionNumber__c</fullName>
        <description>Transaction Number in external system</description>
        <label>Transaction Number</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/GeneralSettings__c/GeneralSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom Setting used to store general system settings</description>
    <label>General Settings</label>
</CustomObject>

unpackaged/main/default/objects/GeneralSettings__c/fields/RICSC_ProductPortfolioIntegrationDate__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ProductPortfolioIntegrationDate__c</fullName>
        <description>its used in a batch to retrieve  transactions that are used in the propagation with the product portfolio object</description>
        <label>Product Portfolio Integration From Date</label>
        <type>Date</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/RICSC_Transaction__c.object-meta.xml
<CustomObject>
    <description>capture transaction information.</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{000000000}</displayFormat>
        <label>Transaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_Account__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to an Account - Release 1 SC</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>RICSC_TransactionsAccount</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_AmountWithTax__c.field-meta.xml
<CustomField>
        <fullName>RICSC_AmountWithTax__c</fullName>
        <description>Total amount of the transaction coming from the source system</description>
        <label>Amount With Tax</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_Boutique__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Boutique__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the Boutique</description>
        <label>Boutique</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transactions (Boutique)</relationshipLabel>
        <relationshipName>RICSC_TransactionsBoutique</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_Channel__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Channel__c</fullName>
        <description>Field to categorize the channel through which the transaction was handled</description>
        <label>Transaction Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Boutique</fullName>
                </value>
                <value>
                    <fullName>CC</fullName>
                </value>
                <value>
                    <fullName>Charity</fullName>
                </value>
                <value>
                    <fullName>Web</fullName>
                </value>
                <value>
                    <fullName>Wholesaler</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_CountryOfOrigin__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CountryOfOrigin__c</fullName>
        <description>Country where the record has been created. Used for the sharing rules (e.g. records created outside of China shouldn't be visible for the Chineese users) - Release 1 SC</description>
        <label>Country Of Transaction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Country</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_GoldenRecord__c.field-meta.xml
<CustomField>
        <fullName>RICSC_GoldenRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to a Golden Record which has been created for the Account - Release 1 SC</description>
        <label>Golden Record</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>RICSC_TransactionsGoldenRecord</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_Maison__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Maison__c</fullName>
        <description>List of Maisons</description>
        <label>Maison</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Maison</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_ProductName__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ProductName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the Product</description>
        <label>Product Name</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Names</relationshipLabel>
        <relationshipName>RICSC_ProductNames</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_SalesAssociate__c.field-meta.xml
<CustomField>
        <fullName>RICSC_SalesAssociate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the Sales Associate</description>
        <label>Sales Associate</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>RICSC_TransactionsSalesAssociate</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_SerialNumber__c.field-meta.xml
<CustomField>
        <fullName>RICSC_SerialNumber__c</fullName>
        <description>Serial Number of the product in the transaction</description>
        <label>Serial Number</label>
        <length>50</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_TransactionCategory__c.field-meta.xml
<CustomField>
        <fullName>RICSC_TransactionCategory__c</fullName>
        <description>Field to categorize a transaction of a certain type as Repair, Return, Sale</description>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Repair</fullName>
                </value>
                <value>
                    <fullName>Return</fullName>
                </value>
                <value>
                    <fullName>Sale</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_TransactionDate__c.field-meta.xml
<CustomField>
        <fullName>RICSC_TransactionDate__c</fullName>
        <description>Transaction Date in external system</description>
        <label>Transaction Date</label>
        <type>Date</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_TransactionNumber__c.field-meta.xml
<CustomField>
        <fullName>RICSC_TransactionNumber__c</fullName>
        <description>Transaction Number in external system</description>
        <label>Transaction Number</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/globalValueSets/RICSC_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Amer.Virgin Is.</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua/Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia-Herz.</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Islands</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/RICSC_Maison.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cartier</fullName>
    </customValue>
    <customValue>
        <fullName>Jaeger Le Coultre</fullName>
    </customValue>
    <customValue>
        <fullName>Van Cleef &amp; Arpels</fullName>
    </customValue>
    <masterLabel>Maison</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/BatchProductPortfolioIntegration.cls
/************************************************************************************
* @author       Silvan Sholla
* @date         9/9/2019
* @description  Population of Product portfolio records related to
*               an account based on linked transaction records.
*               With The Following Criteria :
*
*               1. if there is a match between transaction and asset serial number
*               and the amount with tax is possitive update asset with values
*               from transaction
*               else if there is a match with serial number but the amount with
*               tax is negative mark product refunded as true
*
*               2.If there is not match between transaction and asset serial number
*               create a new asset with the transaction fields link to the same account
***************************************************************************************/


public class BatchProductPortfolioIntegration implements
  Database.Batchable<sObject>, Schedulable {
  private Boolean skipTriggersOnAsset;
  public static final Integer MAX_SCOPE = 100;
  public String salesType = UtilityConstants.TRANSACTION_TYPE_SALES;
  private String query = 'SELECT RICSC_SerialNumber__c, Id, RICSC_Account__c, RICSC_GoldenRecord__c,'+
      'RICSC_AmountWithTax__c,RICSC_TransactionNumber__c,RICSC_ExtCreationDate__c,RICSC_Boutique__c, ' +
      'RICSC_CountryOfOrigin__c,RICSC_SalesAssociate__c,RICSC_Channel__c,RICSC_TransactionDate__c,'+
      'RICSC_ProductName__c,RICSC_Maison__c FROM RICSC_Transaction__c '+
      'WHERE RICSC_ExtCreationDate__c >=:ProductPortfolioIntegrationDate AND RICSC_TransactionCategory__c = :salesType';

  public BatchProductPortfolioIntegration(Boolean skipParam, String queryStr) {
    this.query = queryStr == null ? this.query : queryStr;
    skipTriggersOnAsset = skipParam;
  }

  public void execute(SchedulableContext sc) {
    BatchProductPortfolioIntegration b = new BatchProductPortfolioIntegration(false,null);
    Database.executeBatch(b, MAX_SCOPE);
  }

  public Database.QueryLocator start(Database.BatchableContext bc) {
    Date  ProductPortfolioIntegrationDate = GeneralSettings__c.getOrgDefaults().RICSC_ProductPortfolioIntegrationDate__c;
    return Database.getQueryLocator(query);
  }
  public void execute(Database.BatchableContext bc, List<RICSC_Transaction__c> scope)  {
    try {
      if(skipTriggersOnAsset){
        TRG_TriggerDispatcher.skipTriggerMap.put('Asset',true);
      }

      Database.UpsertResult[] upsrList = Database.upsert(ProductPortfolioIntegration.productPortfolioTransactionPropagation(scope),false);
      //UtilityLogger.logAllErrors(srList, false, 'BatchProductPortfolioIntegration','execute');

      if(skipTriggersOnAsset){
        TRG_TriggerDispatcher.skipTriggerMap.put('Asset',false);
      }
    } catch(Exception e) {
      UtilityLogger.logException(e,e.getMessage(),'BatchProductPortfolioIntegration','execute');
    }
  }
  public void finish(Database.BatchableContext bc){

  }
}