unpackaged/main/default/objects/Product2/fields/RICSC_FrontPictureURL__c.field-meta.xml
<CustomField>
        <fullName>RICSC_FrontPictureURL__c</fullName>
        <description>URL of a product front picture</description>
        <label>Front Picture URL</label>
        <type>Url</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/RICSC_Transaction__c.object-meta.xml
<CustomObject>
    <description>capture transaction information.</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{000000000}</displayFormat>
        <label>Transaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_ProductName__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ProductName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the Product</description>
        <label>Product Name</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Names</relationshipLabel>
        <relationshipName>RICSC_ProductNames</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Wishlist__c/RICSC_Wishlist__c.object-meta.xml
<CustomObject>
    <label>Wishlist</label>
    <nameField>
        <displayFormat>Wishlist-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wishlists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RICSC_Wishlist__c/fields/RICSC_ProductName__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ProductName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Name of the product in the wishlist</description>
        <label>Product Name</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Wishlists (Product Name)</relationshipLabel>
        <relationshipName>RICSC_WishlistsProduct</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/classes/ProductPicture_Test.cls
@isTest
public with sharing class ProductPicture_Test {

    static testmethod void getProductPictureInfosForLWC(){
      List<Product2> prod = UtilityTests.getProducts(2);
      prod[0].RICSC_FrontPictureURL__c = 'www.testurl.turl';
      prod[0].Name = 'TestProductWithURL';
      prod[1].Name = 'TestProductWithoutURL';
      insert prod;
      List<Product2> prodId = [SELECT id FROM Product2 WHERE Name = 'TestProductWithURL' OR Name = 'TestProductWithoutURL' ORDER BY Name DESC];

      List<RICSC_Transaction__c> trans = UtilityTests.getTransactions(2);
      trans[0].RICSC_ProductName__c=prodId[0].id;
      trans[1].RICSC_ProductName__c=prodId[1].id;
      insert trans;
      List<RICSC_Transaction__c> tranId = [SELECT id FROM RICSC_Transaction__c WHERE RICSC_ProductName__c =: prodId[0].id OR RICSC_ProductName__c =: prodId[1].id];
      ProductPicture.CustomWrapper transres1 = ProductPicture.getProductURL(tranId[0].id);
      ProductPicture.CustomWrapper transres2 = ProductPicture.getProductURL(tranId[1].id);
      System.assertEquals(transres1.name,'TestProductWithURL');
      System.assertEquals(transres1.url,'www.testurl.turl');
      System.assertEquals(transres2.name,'TestProductWithoutURL');
      System.assertEquals(transres2.url,'');
      List<RICSC_Wishlist__c> wishs = UtilityTests.getWishlists(2);
      wishs[0].RICSC_ProductName__c=prodId[0].id;
      wishs[1].RICSC_ProductName__c=prodId[1].id;
      insert wishs;
      List<RICSC_Wishlist__c> wishId = [SELECT id FROM RICSC_Wishlist__c WHERE RICSC_ProductName__c =: prodId[0].id OR RICSC_ProductName__c =: prodId[1].id];
      ProductPicture.CustomWrapper wishres1 = ProductPicture.getProductURL(wishId[0].id);
      ProductPicture.CustomWrapper wishres2 = ProductPicture.getProductURL(wishId[1].id);
      System.assertEquals(wishres1.name,'TestProductWithURL');
      System.assertEquals(wishres1.url,'www.testurl.turl');
      System.assertEquals(wishres2.name,'TestProductWithoutURL');
      System.assertEquals(wishres2.url,'');
      List<Asset> assets = UtilityTests.getAssets(2);
      assets[0].Product2Id=prodId[0].id;
      assets[0].Name = 'TEstAsset0';
      assets[1].Product2Id=prodId[1].id;
      assets[1].Name = 'TEstAsset1';
      insert assets;
      List<Asset> assetId = [SELECT id FROM Asset WHERE Product2Id =: prodId[0].id OR Product2Id =: prodId[1].id];
      ProductPicture.CustomWrapper assetres1 = ProductPicture.getProductURL(assetId[0].id);
      ProductPicture.CustomWrapper assetres2 = ProductPicture.getProductURL(assetId[1].id);
      System.assertEquals(assetres1.name,'TestProductWithURL');
      System.assertEquals(assetres1.url,'www.testurl.turl');
      System.assertEquals(assetres2.name,'TestProductWithoutURL');
      System.assertEquals(assetres2.url,'');
    }

}