unpackaged/main/default/objects/Product2/fields/RICSC_FrontPictureURL__c.field-meta.xml
<CustomField>
        <fullName>RICSC_FrontPictureURL__c</fullName>
        <description>URL of a product front picture</description>
        <label>Front Picture URL</label>
        <type>Url</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/RICSC_Transaction__c.object-meta.xml
<CustomObject>
    <description>capture transaction information.</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{000000000}</displayFormat>
        <label>Transaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_ProductName__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ProductName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the Product</description>
        <label>Product Name</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Names</relationshipLabel>
        <relationshipName>RICSC_ProductNames</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Wishlist__c/RICSC_Wishlist__c.object-meta.xml
<CustomObject>
    <label>Wishlist</label>
    <nameField>
        <displayFormat>Wishlist-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wishlists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RICSC_Wishlist__c/fields/RICSC_ProductName__c.field-meta.xml
<CustomField>
        <fullName>RICSC_ProductName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Name of the product in the wishlist</description>
        <label>Product Name</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Wishlists (Product Name)</relationshipLabel>
        <relationshipName>RICSC_WishlistsProduct</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/classes/ProductPicture.cls
public with sharing class ProductPicture {
   public class CustomWrapper {
      @AuraEnabled
      public String name {set; get;}
      @AuraEnabled
      public String url {set; get;}

}

  @AuraEnabled(cacheable=true)
    public static CustomWrapper getProductURL(String id) {
      Id obid = (Id) id;
      String objectType = obid.getSObjectType().getDescribe().getName();
      Schema.SObjectType sObjectType = Schema.getGlobalDescribe().get(objectType);
      SObject newSobject = sObjectType.newSObject();
      CustomWrapper product = new CustomWrapper();
      product.name = '';
      product.url = '';
      if(objectType == 'RICSC_Transaction__c'){
        if(Schema.sObjectType.RICSC_Transaction__c.isAccessible()){
          newSobject =[SELECT Id,RICSC_ProductName__r.Name, RICSC_ProductName__r.RICSC_FrontPictureURL__c  FROM RICSC_Transaction__c WHERE id = :Id];
          if(newSobject.getSObject('RICSC_ProductName__r') != null){
            product.name = newSObject.getSobject('RICSC_ProductName__r').get('Name').toString();
          }
          if (newSobject.getSObject('RICSC_ProductName__r') != null && newSObject.getSobject('RICSC_ProductName__r').get('RICSC_FrontPictureURL__c')!=null){
            product.url = newSObject.getSobject('RICSC_ProductName__r').get('RICSC_FrontPictureURL__c').toString();
          }
        }
      }
      else if(objectType == 'RICSC_Wishlist__c'){
        if(Schema.sObjectType.RICSC_Wishlist__c.isAccessible()){
          newSobject =[SELECT Id,RICSC_ProductName__r.Name, RICSC_ProductName__r.RICSC_FrontPictureURL__c  FROM RICSC_Wishlist__c WHERE id = :Id];
          product.name = newSObject.getSobject('RICSC_ProductName__r').get('Name').toString();
          if (newSObject.getSobject('RICSC_ProductName__r') != null && newSObject.getSobject('RICSC_ProductName__r').get('RICSC_FrontPictureURL__c')!=null){
            product.url = newSObject.getSobject('RICSC_ProductName__r').get('RICSC_FrontPictureURL__c').toString();
          }
        }
      }
      else if(objectType == 'Asset'){
        if(Schema.sObjectType.Asset.isAccessible()){
          newSobject =[SELECT Id,Product2.Name, Product2.RICSC_FrontPictureURL__c  FROM Asset WHERE id = :Id];
          product.name = newSObject.getSobject('Product2').get('Name').toString();
          if(newSObject.getSobject('Product2') != null && newSObject.getSobject('Product2').get('RICSC_FrontPictureURL__c')!=null){
            product.url = newSObject.getSobject('Product2').get('RICSC_FrontPictureURL__c').toString();
          }
        }
      }
      return product;
    }

}