unpackaged/main/default/objects/GeneralSettings__c/GeneralSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom Setting used to store general system settings</description>
    <label>General Settings</label>
</CustomObject>

unpackaged/main/default/objects/GeneralSettings__c/fields/Scope__c.field-meta.xml
<CustomField>
        <fullName>Scope__c</fullName>
        <description>The scope used by the system to control deviation from global framework. If not necessary just use -All- value</description>
        <label>Scope</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/TRG_TriggerConf__mdt/TRG_TriggerConf__mdt.object-meta.xml
<CustomObject>
    <label>Trigger Configuration</label>
    <pluralLabel>Trigger Configurations</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/TRG_TriggerConf__mdt/fields/AfterDelete__c.field-meta.xml
<CustomField>
        <fullName>AfterDelete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>AfterDelete Event</description>
        <inlineHelpText>AfterDelete Event</inlineHelpText>
        <label>AfterDelete</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/TRG_TriggerConf__mdt/fields/AfterInsert__c.field-meta.xml
<CustomField>
        <fullName>AfterInsert__c</fullName>
        <defaultValue>false</defaultValue>
        <description>AfterInsert Event</description>
        <inlineHelpText>AfterInsert Event</inlineHelpText>
        <label>AfterInsert</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/TRG_TriggerConf__mdt/fields/AfterUndelete__c.field-meta.xml
<CustomField>
        <fullName>AfterUndelete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>AfterUndelete Event</description>
        <inlineHelpText>AfterUndelete Event</inlineHelpText>
        <label>AfterUndelete</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/TRG_TriggerConf__mdt/fields/AfterUpdate__c.field-meta.xml
<CustomField>
        <fullName>AfterUpdate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>AfterUpdate Event</description>
        <inlineHelpText>AfterUpdate Event</inlineHelpText>
        <label>AfterUpdate</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/TRG_TriggerConf__mdt/fields/BeforeDelete__c.field-meta.xml
<CustomField>
        <fullName>BeforeDelete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>BeforeDelete Event</description>
        <inlineHelpText>BeforeDelete Event</inlineHelpText>
        <label>BeforeDelete</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/TRG_TriggerConf__mdt/fields/BeforeInsert__c.field-meta.xml
<CustomField>
        <fullName>BeforeInsert__c</fullName>
        <defaultValue>false</defaultValue>
        <description>BeforeInsert Event</description>
        <inlineHelpText>BeforeInsert Event</inlineHelpText>
        <label>BeforeInsert</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/TRG_TriggerConf__mdt/fields/BeforeUpdate__c.field-meta.xml
<CustomField>
        <fullName>BeforeUpdate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>BeforeUpdate Event</description>
        <inlineHelpText>BeforeUpdate Event</inlineHelpText>
        <label>BeforeUpdate</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/TRG_TriggerConf__mdt/fields/Class__c.field-meta.xml
<CustomField>
        <fullName>Class__c</fullName>
        <description>The class or inner class that implements TriggerHandlerInterface</description>
        <inlineHelpText>The class or inner class that implements TriggerHandlerInterface</inlineHelpText>
        <label>Class</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/TRG_TriggerConf__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>The record status</description>
        <inlineHelpText>The record status</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/TRG_TriggerConf__mdt/fields/Object__c.field-meta.xml
<CustomField>
        <fullName>Object__c</fullName>
        <description>Object Trigger for to execute this method</description>
        <inlineHelpText>Object Trigger for to execute this method</inlineHelpText>
        <label>Object</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/TRG_TriggerConf__mdt/fields/OrderOfExecution__c.field-meta.xml
<CustomField>
        <fullName>OrderOfExecution__c</fullName>
        <description>The Order of execution for the current method within the object and event trigger.
Integer values are reserved for global methods.
Decimal values are reserved for region specific methods.</description>
        <inlineHelpText>The Order of execution for the current method within the object and event trigger.
Integer values are reserved for global methods.
Decimal values are reserved for region specific methods.</inlineHelpText>
        <label>Order of Execution</label>
        <precision>18</precision>
        <required>true</required>
        <scale>9</scale>
        <type>Number</type>
    </CustomField>

unpackaged/main/default/objects/TRG_TriggerConf__mdt/fields/Scope__c.field-meta.xml
<CustomField>
        <fullName>Scope__c</fullName>
        <description>GL -&gt; Global, DE -&gt; Germany, AP -&gt; Asia/Pacific</description>
        <inlineHelpText>GL -&gt; Global, DE -&gt; Germany, AP -&gt; Asia/Pacific</inlineHelpText>
        <label>Scope</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GL</fullName>
                    <default>true</default>
                    <label>GL</label>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>AP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/classes/TRG_TriggerHandlerConfiguration_Test.cls
@isTest
private class TRG_TriggerHandlerConfiguration_Test{

    @isTest
    static void testTriggerConfigurations(){
        
        Map<String, Schema.SObjectType> globalDesc = Schema.getGlobalDescribe(); 
        String scope = GeneralSettings__c.getInstance().Scope__c;            
        List<TRG_TriggerConf__mdt> configs = [SELECT Id, Object__c, Class__c, Scope__c, OrderOfExecution__c, DeveloperName,
                                                                 AfterDelete__c, AfterInsert__c, AfterUndelete__c, AfterUpdate__c, BeforeDelete__c, BeforeInsert__c, BeforeUpdate__c    
                                                                 FROM TRG_TriggerConf__mdt 
                                                                 WHERE IsActive__c = TRUE]; 
        
        for(TRG_TriggerConf__mdt config: configs){
           
            //Object check
            system.assert(true == globalDesc.containskey(config.Object__c), 'Configured object !'+config.Object__c+'! in field Object__c is not available for this Org. Record DevName: ' +config.DeveloperName);
            
            //Order of execution check (Region specific methods use decimal, GL methods use only integer part)
            if(config.Scope__c == 'GL'){
                system.assert(config.OrderOfExecution__c == config.OrderOfExecution__c.round(System.RoundingMode.DOWN), 'Configured Global (GL) metadata uses decimal (reserved to regional) order of execution. '+config.OrderOfExecution__c+'. Record DevName: ' +config.DeveloperName);
            }else{
                system.assert(config.OrderOfExecution__c != config.OrderOfExecution__c.round(System.RoundingMode.DOWN), 'Configured Region specific metadata does not use decimal (reserved to regional) order of execution. '+config.OrderOfExecution__c+'. Record DevName: ' +config.DeveloperName);
            }
            
            //Check that at least one Event is selected
            system.assert(true == config.AfterDelete__c || config.AfterInsert__c || config.AfterUndelete__c || config.AfterUpdate__c || config.BeforeDelete__c || config.BeforeInsert__c || config.BeforeUpdate__c ,
                             'At least one event must be selected. Record DevName: ' +config.DeveloperName);

            //Class Method Check
            try{
                Object obj = Type.forName(config.Class__c.deleteWhitespace()).newInstance( );
                System.assertEquals( true, obj instanceof TRG_TriggerHandlerInterface);

            }catch(NullPointerException e){
                system.assert(false, 'Configured Class does not exist. Class: '+ config.Class__c.deleteWhitespace() + ' . Record DevName: ' +config.DeveloperName);
            }
        }
    }

}