unpackaged/main/default/objects/GeneralSettings__c/GeneralSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom Setting used to store general system settings</description>
    <label>General Settings</label>
</CustomObject>

unpackaged/main/default/objects/GeneralSettings__c/fields/Logger_DebugEnabled__c.field-meta.xml
<CustomField>
        <fullName>Logger_DebugEnabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If true enables storing of Debug Application Log records</description>
        <label>Logger Debug Enabled</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/GeneralSettings__c/fields/Logger_ExceptionEnabled__c.field-meta.xml
<CustomField>
        <fullName>Logger_ExceptionEnabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If true enables storing of Exception Application Log records</description>
        <label>Logger Exception Enabled</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Custom Object used to store Application Debug and Exception logs</description>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Log__c/fields/Count__c.field-meta.xml
<CustomField>
        <fullName>Count__c</fullName>
        <description>If log type is exception, represents the number of occurrencies of this exception during the day</description>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

unpackaged/main/default/objects/Log__c/fields/DebugLevel__c.field-meta.xml
<CustomField>
        <fullName>DebugLevel__c</fullName>
        <label>DebugLevel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Warning</fullName>
                </value>
                <value>
                    <fullName>Debug</fullName>
                </value>
                <value>
                    <fullName>Info</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Log__c/fields/Limits__c.field-meta.xml
<CustomField>
        <fullName>Limits__c</fullName>
        <label>Limits</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </CustomField>

unpackaged/main/default/objects/Log__c/fields/Message__c.field-meta.xml
<CustomField>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </CustomField>

unpackaged/main/default/objects/Log__c/fields/Source__c.field-meta.xml
<CustomField>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>150</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Log__c/fields/SourceMethod__c.field-meta.xml
<CustomField>
        <fullName>SourceMethod__c</fullName>
        <label>Source Method</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Log__c/fields/StackTrace__c.field-meta.xml
<CustomField>
        <fullName>StackTrace__c</fullName>
        <label>StackTrace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </CustomField>

unpackaged/main/default/objects/Log__c/fields/TransactionID__c.field-meta.xml
<CustomField>
        <fullName>TransactionID__c</fullName>
        <label>Transaction Identifier</label>
        <length>32</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Log__c/fields/Type__c.field-meta.xml
<CustomField>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Debug</fullName>
                </value>
                <value>
                    <fullName>Exception</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Log__c/fields/User__c.field-meta.xml
<CustomField>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Application_Logs</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/classes/UtilityLogger_Test.cls
@isTest
public class UtilityLogger_Test {

    @testSetup static void testSetup(){
        UtilityTests.testSetup();
    }

    /**
    * @method       logInfo
    * @scenario     New log insertion, debugLogEnabled = true
    **/
    @isTest static void testlogInfoDebugEnabled() {

        Integer numOfLogsBeforeDML = [SELECT COUNT() FROM Log__c];

        Test.startTest();
        UtilityLogger.logInfo('msg', 'logLevel', 'sourceClass', 'sourceMethod');
        Test.stopTest();

        Integer numOfLogsAfterDML = [SELECT COUNT() FROM Log__c];

        System.assert(numOfLogsAfterDML > numOfLogsBeforeDML);
    }

    /**
    * @method       logInfo
    * @scenario     Skip new log insertion, debugLogEnabled = false
    **/
    @isTest static void testLogInfoDebugDisabled() {

        // disable debugLog
        GeneralSettings__c generalSetting = GeneralSettings__c.getOrgDefaults();
        generalSetting.Logger_DebugEnabled__c = false;
        upsert generalSetting;

        Integer numOfLogsBeforeDML = [SELECT COUNT() FROM Log__c];

        Test.startTest();
        UtilityLogger.logInfo('msg', 'logLevel', 'sourceClass', 'sourceMethod');
        Test.stopTest();

        Integer numOfLogsAfterDML = [SELECT COUNT() FROM Log__c];

        System.assertEquals(numOfLogsAfterDML, numOfLogsBeforeDML);
    }

    /**
    * @method       logException
    * @scenario     New exception log insertion, debugLogEnabled = true
    **/
    @isTest static void testLogExceptionNewExceptionDebugEnabled() {

        Integer numOfExceptionLogsBeforeDML = [SELECT COUNT() FROM Log__c WHERE Type__c = 'Exception'];

        Test.startTest();
        CalloutException e = new CalloutException();
    	e.setMessage('This is a constructed exception!');
        UtilityLogger.logException(e ,'msg', 'sourceClass', 'sourceMethod');
        Test.stopTest();

        Integer numOfExceptionLogsAfterDML = [SELECT COUNT() FROM Log__c WHERE Type__c = 'Exception'];

        System.assertEquals(numOfExceptionLogsBeforeDML + 1, numOfExceptionLogsAfterDML);
    }

    /**
    * @method       logException
    * @scenario     Exception already exists, debugLogEnabled = true. The Count__c
    *               of the already existing exception should be increased by one,
    *               so it will be equal to 2.
    **/
    @isTest static void testLogExceptionExistingExceptionDebugEnabled() {

        Test.startTest();
        CalloutException e = new CalloutException();
    	e.setMessage('Test exception message');

        List<Log__c> logList = new List<Log__c>();

        Log__c log = new Log__c(
                                StackTrace__c = e.getStackTraceString(),
                                Limits__c = 'getLimits()',
                                Message__c = e.getMessage(),
                                Count__c = 1,
                                Type__c = 'Exception',
                                User__c = Userinfo.getUserId(),
                                DebugLevel__c = 'Error',
                                Source__c = 'sourceClass',
                                SourceMethod__c = 'sourceMethod',
                                TransactionID__c = 'testingIdHere'
                            );
        logList.add(log);
        insert logList;

        UtilityLogger.logException(e ,'msg', 'sourceClass', 'sourceMethod');
        Test.stopTest();

        List<Log__c> logs = [SELECT Count__c FROM Log__c WHERE TransactionID__c = 'testingIdHere' AND Type__c = 'Exception'];

        System.assert(logs[0].Count__c == 2);
    }

    /**
    * @method       logException
    * @scenario     Skip method code, debugLogEnabled = false
    **/
    @isTest static void testLogExceptionDebugDisabled() {
        // disable debugLog
        GeneralSettings__c generalSetting = GeneralSettings__c.getOrgDefaults();
        generalSetting.Logger_ExceptionEnabled__c = false;
        upsert generalSetting;

        Integer numOfExceptionLogsBeforeDML = [SELECT COUNT() FROM Log__c WHERE Type__c = 'Exception'];

        Test.startTest();
        CalloutException e = new CalloutException();
    	e.setMessage('This is a constructed exception!');
        UtilityLogger.logException(e ,'msg', 'sourceClass', 'sourceMethod');
        Test.stopTest();

        Integer numOfExceptionLogsAfterDML = [SELECT COUNT() FROM Log__c WHERE Type__c = 'Exception'];

        System.assertEquals(numOfExceptionLogsBeforeDML, numOfExceptionLogsAfterDML);
    }
}