unpackaged/main/default/objects/RICSC_Transaction__c/RICSC_Transaction__c.object-meta.xml
<CustomObject>
    <description>capture transaction information.</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{000000000}</displayFormat>
        <label>Transaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_AmountWithTax__c.field-meta.xml
<CustomField>
        <fullName>RICSC_AmountWithTax__c</fullName>
        <description>Total amount of the transaction coming from the source system</description>
        <label>Amount With Tax</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_AmountWithTaxEUR__c.field-meta.xml
<CustomField>
        <fullName>RICSC_AmountWithTaxEUR__c</fullName>
        <description>Total amount of the transaction coming from the source system</description>
        <label>Amount With Tax EUR</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_CurrencyKey__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CurrencyKey__c</fullName>
        <description>Currency keycoming from the source system</description>
        <label>Currency Key</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Currency</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_CurrencyRateEUR__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CurrencyRateEUR__c</fullName>
        <description>Currency rate used to convert a local amount to the EUR amounts</description>
        <label>Currency Rate EUR</label>
        <precision>12</precision>
        <scale>6</scale>
        <type>Number</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_Maison__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Maison__c</fullName>
        <description>List of Maisons</description>
        <label>Maison</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Maison</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/globalValueSets/RICSC_Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AWG</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BOV</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BTN</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYR</fullName>
    </customValue>
    <customValue>
        <fullName>BZD</fullName>
    </customValue>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <customValue>
        <fullName>CDF</fullName>
    </customValue>
    <customValue>
        <fullName>CHE</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <description>Unit of measurecoming</description>
    <masterLabel>Currency</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/RICSC_Maison.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cartier</fullName>
    </customValue>
    <customValue>
        <fullName>Jaeger Le Coultre</fullName>
    </customValue>
    <customValue>
        <fullName>Van Cleef &amp; Arpels</fullName>
    </customValue>
    <masterLabel>Maison</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/UtilityTransaction.cls
public without sharing class UtilityTransaction {
  public static void calculateConventionRate(List<RICSC_Transaction__c> transactions, Set<String> currencyISO){
    List<DatedConversionRate> currencyConventionsToCorporateDatedExchangeRates = Utility.currencyConventionsToCorporateDatedExchangeRates(currencyISO);
    Map< String , CurrencyType> currencyConventionsToCorporateCurrencyType = Utility.currencyConventionsToCorporateCurrencyType(currencyISO);
    for(RICSC_Transaction__c tr : transactions){
      Boolean invalidCurrencyOnVCA = true;
      for(DatedConversionRate datedcurrencies : currencyConventionsToCorporateDatedExchangeRates){
        if(tr.RICSC_Maison__c == UtilityConstants.MAISON_VAN_CLEEF_ARPELS &&
          datedcurrencies.IsoCode == tr.RICSC_CurrencyKey__c &&
          datedcurrencies.NextStartDate != null &&
          datedcurrencies.NextStartDate >= tr.RICSC_ExtCreationDate__c &&
          datedcurrencies.StartDate <= tr.RICSC_ExtCreationDate__c
          )
        {
          Double currencyRate = (Double) datedcurrencies.ConversionRate;
          tr.RICSC_AmountWithTaxEUR__c = tr.RICSC_AmountWithTax__c * (Double)(1/currencyRate);
          tr.RICSC_CurrencyRateEUR__c = (Double)(1/currencyRate);
          InvalidCurrencyOnVCA = false;
        }
      }

      if(tr.RICSC_Maison__c == UtilityConstants.MAISON_VAN_CLEEF_ARPELS && InvalidCurrencyOnVCA == true){
          throw new TypeException(Label.Exception_InvalidCurrencyIsoCode);
      }


      if((tr.RICSC_Maison__c == UtilityConstants.MAISON_CARTIER || tr.RICSC_Maison__c == UtilityConstants.MAISON_JAEGER_LE_COULTRE) &&
          currencyConventionsToCorporateCurrencyType.containsKey(tr.RICSC_CurrencyKey__c))
      {
        Double currencyRate = (Double) currencyConventionsToCorporateCurrencyType.get(tr.RICSC_CurrencyKey__c).get('ConversionRate');
        tr.RICSC_AmountWithTaxEUR__c = tr.RICSC_AmountWithTax__c * (Double)(1/currencyRate);
        tr.RICSC_CurrencyRateEUR__c = (Double)(1/currencyRate);
      }else if(tr.RICSC_Maison__c == UtilityConstants.MAISON_CARTIER || tr.RICSC_Maison__c == UtilityConstants.MAISON_JAEGER_LE_COULTRE){
        throw new TypeException(Label.Exception_InvalidCurrencyIsoCode);
      }
    }
  }
}