unpackaged/main/default/objects/RICSC_Transaction__c/RICSC_Transaction__c.object-meta.xml
<CustomObject>
    <description>capture transaction information.</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{000000000}</displayFormat>
        <label>Transaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
    <sharingReasons>
        <fullName>RICSC_VCASharingGolden__c</fullName>
        <label>VCA Sharing Golden</label>
    </sharingReasons>
    <sharingReasons>
        <fullName>RICSC_VCASharingLocal__c</fullName>
        <label>VCA Sharing Local</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_AmountWithTax__c.field-meta.xml
<CustomField>
        <fullName>RICSC_AmountWithTax__c</fullName>
        <description>Total amount of the transaction coming from the source system</description>
        <label>Amount With Tax</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_AmountWithTaxEUR__c.field-meta.xml
<CustomField>
        <fullName>RICSC_AmountWithTaxEUR__c</fullName>
        <description>Total amount of the transaction coming from the source system</description>
        <label>Amount With Tax EUR</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_CurrencyKey__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CurrencyKey__c</fullName>
        <description>Currency keycoming from the source system</description>
        <label>Currency Key</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Currency</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_CurrencyRateEUR__c.field-meta.xml
<CustomField>
        <fullName>RICSC_CurrencyRateEUR__c</fullName>
        <description>Currency rate used to convert a local amount to the EUR amounts</description>
        <label>Currency Rate EUR</label>
        <precision>12</precision>
        <scale>6</scale>
        <type>Number</type>
    </CustomField>

unpackaged/main/default/objects/RICSC_Transaction__c/fields/RICSC_Maison__c.field-meta.xml
<CustomField>
        <fullName>RICSC_Maison__c</fullName>
        <description>List of Maisons</description>
        <label>Maison</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RICSC_Maison</valueSetName>
        </valueSet>
    </CustomField>

unpackaged/main/default/globalValueSets/RICSC_Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AWG</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BOV</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BTN</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYR</fullName>
    </customValue>
    <customValue>
        <fullName>BZD</fullName>
    </customValue>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <customValue>
        <fullName>CDF</fullName>
    </customValue>
    <customValue>
        <fullName>CHE</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <description>Unit of measurecoming</description>
    <masterLabel>Currency</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/RICSC_Maison.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cartier</fullName>
    </customValue>
    <customValue>
        <fullName>Jaeger Le Coultre</fullName>
    </customValue>
    <customValue>
        <fullName>Van Cleef &amp; Arpels</fullName>
    </customValue>
    <masterLabel>Maison</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/BatchConventionRateCalculation.cls
public class BatchConventionRateCalculation implements Database.Batchable<SObject>, Schedulable {

  public static final Integer MAX_SCOPE = 100;
  private String query = 'SELECT Id, RICSC_CurrencyKey__c, RICSC_Maison__c, RICSC_ExtCreationDate__c, RICSC_AmountWithTaxEUR__c, RICSC_AmountWithTax__c, RICSC_CurrencyRateEUR__c FROM RICSC_Transaction__c WHERE RICSC_AmountWithTax__c != null AND RICSC_CurrencyKey__c != null AND RICSC_Maison__c != null';
  private Boolean skipTriggersOnTransaction;

  public BatchConventionRateCalculation(Boolean skipParam, String queryStr) {
    this.query = queryStr == null ? this.query : queryStr;
    skipTriggersOnTransaction = skipParam;
  }

  public Iterable<SObject> start(Database.BatchableContext bc) {
      return Database.getQueryLocator(query);
  }

  public void execute(SchedulableContext sc) {
    BatchConventionRateCalculation b = new BatchConventionRateCalculation(false, null);
    Database.executeBatch(b, MAX_SCOPE);
  }

  public void execute(Database.BatchableContext bc, List<RICSC_Transaction__c> scope) {
    Set<String> currencyISO = new Set<String>();
    for(RICSC_Transaction__c tr : scope){
      currencyISO.add(tr.RICSC_CurrencyKey__c);
    }
    UtilityTransaction.calculateConventionRate(scope, currencyISO);

    if(skipTriggersOnTransaction){
      TRG_TriggerDispatcher.skipTriggerMap.put('RICSC_Transaction__c',true);
    }
    Database.SaveResult[] srList = Database.update(scope,false);
    UtilityLogger.logAllErrors(srList, false, 'BatchConventionRateCalculation', 'execute');
    if(skipTriggersOnTransaction){
      TRG_TriggerDispatcher.skipTriggerMap.put('RICSC_Transaction__c',false);
    }

  }

  public void finish(Database.BatchableContext bc) {
  }
}